import {test} from 'node:test'
import assert from 'node:assert/strict'
import {blank,workedExample,preparationExample,workspaceSchema,saveTestPlan,migrate} from '../src/lib/workspace.ts'
import {WorkspaceWriter,workspaceToken,applyNextAction} from '../src/lib/workspace-writer.ts'
import {preparationLabel,safeLink,executionLabel,bundleSchema} from '../src/lib/preparation-api.ts'

function memory(){const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}}}
test('Madar is valid and isolated from Noura',()=>{const a=preparationExample(),b=workedExample();assert.equal(workspaceSchema.safeParse(a).success,true);assert.equal(a.brief.idea,'Madar Design Studio');assert.equal(a.evidence.length,0);assert.notEqual(a.brief.idea,b.brief.idea);assert.equal(a.setup.length,3)})
test('whitelisted follow-up preserves every other workspace branch',()=>{let w=workedExample();w.legacy={retained:true};w=saveTestPlan(w,w.hypotheses[0]);const a={task:'Confirm applicability',owner:'Founder',due:'',dependency:'Official source check'};const next=applyNextAction(w,workspaceToken(w),a);assert.deepEqual({...next,nextAction:w.nextAction},w);assert.deepEqual(next.nextAction,a)})
test('stale follow-up preview and extra patch keys are rejected',()=>{const w=workedExample(),token=workspaceToken(w);assert.throws(()=>applyNextAction({...w,costs:{...w.costs,price:'13'}},token,w.nextAction));assert.throws(()=>applyNextAction(w,token,{...w.nextAction,evidence:[]} as any))})
test('writer detects competing tab and does not overwrite it',()=>{const store=memory(),one=new WorkspaceWriter(store,'w'),two=new WorkspaceWriter(store,'w'),a=workedExample(),b=blank();assert.equal(one.persist(a,()=>true).ok,true);assert.equal(two.persist(b,()=>true).ok,false);assert.deepEqual(JSON.parse(store.getItem('w')!),a)})
test('writer rejects late session, invalid values, and quota failure',()=>{const s=memory(),writer=new WorkspaceWriter(s,'w');assert.equal(writer.persist(blank(),()=>false).ok,false);assert.equal(writer.persist({version:3} as any,()=>true).ok,false);assert.equal(s.getItem('w'),null);const broken=new WorkspaceWriter({getItem:()=>null,setItem:()=>{throw new Error('Quota')}},'w');assert.match(broken.persist(blank(),()=>true).reason!,/saving failed/)})
test('explicit restore accepts the current baseline; ordinary writes cannot',()=>{const s=memory(),writer=new WorkspaceWriter(s,'w');s.setItem('w','different');assert.equal(writer.persist(blank(),()=>true).ok,false);writer.acceptExplicitReplacement();assert.equal(writer.persist(blank(),()=>true).ok,true)})
test('previous v2 data gains defaults without dropping setup or legacy',()=>{const original=workedExample();original.legacy={old:true};const {profile,savedTests,...old}=original;const restored=migrate(old);assert.deepEqual(restored.setup,original.setup);assert.deepEqual(restored.legacy,original.legacy);assert.equal(restored.savedTests.length,0)})
test('no review label for stale revision or wrong hash',()=>{const b:any={job:{status:'blocked',businessRevision:3},case:{businessRevision:3},pack:{hash:'abc'},review:{valid:true,packHash:'abc',businessRevision:3}};assert.equal(preparationLabel(b),'Reviewed preparation draft: applicability questions open');b.review.packHash='other';assert.equal(preparationLabel(b),'Preparation draft: applicability questions open');b.review.packHash='abc';b.case.businessRevision=4;assert.equal(preparationLabel(b),'Preparation draft: applicability questions open')})
test('modes are explicit and unsafe source links are rejected',()=>{assert.match(executionLabel('deterministic'),/No live AI/);assert.match(executionLabel('live_agent'),/Live model/);assert.equal(safeLink('javascript:alert(1)'),null);assert.equal(safeLink('file:///tmp/test'),null);assert.equal(safeLink('https://moci.gov.kw/'),'https://moci.gov.kw/')})
test('unsupported API bundles fail validation',()=>{assert.equal(bundleSchema.safeParse({job:{status:'ready'}}).success,false)})
