// A model preview, never the authoritative snapshot used to validate or save proposals.
export function workspaceModelContext(workspace:any,query='',maxBytes=11000):any{
 if(!workspace)return null;
 const clip=(value:any,n=600):any=>typeof value==='string'?value.slice(0,n):value;
 const fields=(value:any,n=600)=>value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([,v])=>['string','number','boolean'].includes(typeof v)).map(([k,v])=>[k,clip(v,n)])):value;
 const terms=query.toLowerCase().match(/[\p{L}\p{N}_-]{3,}/gu)||[];
 const rank=(row:any)=>terms.reduce((n:number,word:string)=>n+(JSON.stringify(row).toLowerCase().includes(word)?1:0),0);
 const select=(rows:any[],n:number)=>rows.map((row,index)=>({row,index,score:rank(row)})).sort((a,b)=>b.score-a.score||b.index-a.index).slice(0,n).map(x=>x.row);
 const latest=(rows:any[],n:number)=>rows.slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))).slice(-n);
 const selectedHypotheses=select(workspace.hypotheses||[],5);const adoptedTests=(workspace.hypotheses||[]).filter((h:any)=>h.test?.provenance).slice(-3);
 const hypotheses=[...new Map([...selectedHypotheses,...adoptedTests].map((h:any)=>[h.id,h])).values()].slice(-7);
 const ideaReviewDecisions=latest(workspace.ideaReviewDecisions||[],6).map((d:any)=>({id:d.id,artifactId:d.artifactId,conversationId:d.conversationId,date:d.date,choice:d.choice,reason:clip(d.reason,1200),reasonTruncated:String(d.reason||'').length>1200,selectedOption:clip(d.selectedOption,500),selectedOptionTruncated:String(d.selectedOption||'').length>500,reviewSummary:clip(d.reviewSummary,600),customOption:d.customOption?{title:clip(d.customOption.title,160),kind:d.customOption.kind,tradeoff:clip(d.customOption.tradeoff,320),titleTruncated:String(d.customOption.title||'').length>160,tradeoffTruncated:String(d.customOption.tradeoff||'').length>320}:undefined}));
 const decisions=latest(workspace.decisions||[],6).map((d:any)=>({id:d.id,hypothesisId:d.hypothesisId,date:d.date,outcome:d.outcome,reason:clip(d.reason,700),assumption:clip(d.assumption,280),rule:clip(d.rule,400),evidenceCount:d.evidence?.length||0,evidence:(d.evidence||[]).slice(-2).map((e:any)=>fields(e,180))}));
 const preview:any={updatedAt:workspace.updatedAt,brief:fields(workspace.brief,1600),profile:fields(workspace.profile),costs:workspace.costs,nextAction:fields(workspace.nextAction),projection:{truncated:true,note:'Bounded unverified context. Omitted records/history remain saved. Never infer missing values or claim this is complete.',totalLifecycle:workspace.lifecycle?.length||0,totalHypotheses:workspace.hypotheses?.length||0,totalIdeaReviewDecisions:workspace.ideaReviewDecisions?.length||0,totalDecisions:workspace.decisions?.length||0,ideaReviewDecisionsTruncated:(workspace.ideaReviewDecisions?.length||0)>ideaReviewDecisions.length,decisionsTruncated:(workspace.decisions?.length||0)>decisions.length},hypotheses:hypotheses.map((h:any)=>({...fields(h),test:{...fields(h.test),provenance:fields(h.test?.provenance,240)},evidence:select(h.evidence||[],2).map((e:any)=>fields(e))})),ideaReviewDecisions,decisions,lifecycle:select(workspace.lifecycle||[],10).map((r:any)=>({id:r.id,revision:r.revision,values:fields(r.values,700)}))};
 const bytes=()=>Buffer.byteLength(JSON.stringify(preview));
 while(bytes()>maxBytes&&preview.lifecycle.length)preview.lifecycle.pop();
 while(bytes()>maxBytes&&preview.hypotheses.length){const ordinary=preview.hypotheses.findIndex((h:any)=>!h.test?.provenance);if(ordinary>=0)preview.hypotheses.splice(ordinary,1);else if(preview.hypotheses.length>1){const oldest=preview.hypotheses.findIndex((h:any)=>h.id!==adoptedTests.at(-1)?.id);if(oldest>=0)preview.hypotheses.splice(oldest,1);else break;}else break;}
 while(bytes()>maxBytes&&preview.ideaReviewDecisions.length>1)preview.ideaReviewDecisions.shift();
 while(bytes()>maxBytes&&preview.decisions.length>1)preview.decisions.shift();
 if(bytes()>maxBytes){preview.brief=fields(workspace.brief,400);preview.profile=fields(workspace.profile,200);preview.nextAction=undefined;}
 if(bytes()>maxBytes&&preview.ideaReviewDecisions.length){const d=preview.ideaReviewDecisions.at(-1);d.reason=clip(d.reason,300);d.reasonTruncated=true;d.selectedOption=clip(d.selectedOption,180);d.selectedOptionTruncated=true;d.reviewSummary=clip(d.reviewSummary,180);if(d.customOption){d.customOption.tradeoff=clip(d.customOption.tradeoff,160);d.customOption.tradeoffTruncated=true;}}
 if(bytes()>maxBytes&&preview.decisions.length){const d=preview.decisions.at(-1);d.reason=clip(d.reason,200);d.rule=clip(d.rule,180);d.assumption=clip(d.assumption,160);d.evidence=d.evidence.slice(-1);}
 if(bytes()>maxBytes&&preview.hypotheses.length){const h=preview.hypotheses.find((item:any)=>item.id===adoptedTests.at(-1)?.id);if(h){h.test={method:clip(h.test?.method,180),audience:clip(h.test?.audience,120),rule:clip(h.test?.rule,180),provenance:fields(h.test?.provenance,120)};h.evidence=(h.evidence||[]).slice(-1);for(const key of ['title','reviewReason','area','priority','status'])if(typeof h[key]==='string')h[key]=clip(h[key],120);}}
 return preview;
}
