import {useEffect,useRef,useState} from 'react'
import {ArrowRight,ArrowUpRight,ArrowDownToLine,BookOpen,Building2,Check,ChevronDown,ChevronRight,Compass,FileText,FlaskConical,GitBranch,Layers3,Link2,MapPin,Menu,MoreHorizontal,Plus,Search,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,TriangleAlert,X,Clock3,CornerDownRight} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Badge} from '@/components/ui/badge'
import {Card,CardContent} from '@/components/ui/card'
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs'
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator} from '@/components/ui/dropdown-menu'
import {CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command'
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet'
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip'
import {Checkbox} from '@/components/ui/checkbox'
import {Field,Choice} from '@/components/fields'
import {BriefEditor,EvidenceEditor,HypothesisEditor,EditorFrame} from '@/components/editors'
import {AssumptionPanel,EvidenceNote} from '@/components/assumption-panel'
import {HomeDashboard,shortName,displayDate} from '@/components/home-dashboard'
import {WorkspaceGuide} from '@/components/workspace-guide'
import {ChatWorkspace} from '@/components/chat-workspace'
import {StartPlan} from '@/components/start-plan'
import {PreparationPanel} from '@/components/preparation-panel'
import {WorkspaceWriter,applyNextAction,type WriteResult} from '@/lib/workspace-writer'
import {preparationExample} from '@/lib/workspace'
import type {PreparationSummary} from '@/lib/preparation-api'
import {saveTestPlan} from '@/lib/workspace'
import {KEY,blank,loadWorkspace,migrate,workspaceSchema,workedExample,reviseBrief,recordDecision,nextHypothesis,linked,signal,calculate,formatMoney,download,exportPlan,sectors,today,type Workspace,type Evidence,type Hypothesis,type Brief} from '@/lib/workspace'

type Page='plan'|'today'|'workspace'|'model'|'evidence'|'economics'|'kuwait'
const pages=[{id:'today' as Page,label:'Workspace',icon:Compass},{id:'plan' as Page,label:'Business',icon:Layers3},{id:'evidence' as Page,label:'Library',icon:BookOpen}]
const workspacePages=[{id:'workspace' as Page,label:'This step',icon:FlaskConical},{id:'model' as Page,label:'My idea',icon:FileText},{id:'economics' as Page,label:'Money',icon:SlidersHorizontal},{id:'kuwait' as Page,label:'Kuwait setup',icon:Building2}]
const setupItems=[{id:'activity',title:'Business activity & legal form',question:'Which activity describes your offer, and which formation route applies to your circumstances?',source:'Kuwait Business Center',url:'https://www.moci.gov.kw/ar/e-service/kuwait-business-center/'},{id:'premises',title:'Location & required approvals',question:'Does this activity require premises, sector approvals or specific operating conditions?',source:'Kuwait Business Center',url:'https://www.moci.gov.kw/ar/e-service/kuwait-business-center/'},{id:'operations',title:'Services, documents & follow-up',question:'Which official business services and document follow-ups will you need after choosing your route?',source:'Sahel Business',url:'https://e.gov.kw/sites/kgoenglish/Pages/ApplicationPages/Application-Sahel-Business.aspx'}]
function Brand({language}:{language:'en'|'ar'}){return <img className={`brand-asset ${language==='ar'?'arabic':''}`} src={language==='ar'?'./brand/dukkan-06-arabic-wordmark.svg':'./brand/dukkan-07-english-wordmark.svg'} alt={language==='ar'?'دُكَّان':'Dukkan'}/>}
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Status({h}:{h:Hypothesis}){return <Badge variant="outline" className={`status ${h.reviewReason?'revisit':h.status.toLowerCase().replaceAll(' ','-')}`}><span/>{h.reviewReason?'Review needed':h.status}</Badge>}

export default function App(){
 const [initial]=useState(loadWorkspace),[demo,setDemo]=useState(()=>new URLSearchParams(location.search).has('example'))
 const [madar,setMadar]=useState(()=>new URLSearchParams(location.search).get('example')==='madar')
 const [w,setW]=useState<Workspace>(()=>demo?(madar?preparationExample():workedExample()):initial.workspace),realWorkspace=useRef(initial.workspace),canWrite=useRef(!initial.error)
 const currentWorkspace=useRef(w),session=useRef(0),[sessionId,setSessionId]=useState(0),[saving,setSaving]=useState(false)
 const [writer]=useState(()=>{try{return new WorkspaceWriter(localStorage,KEY)}catch{return null}})
 const lastWrite=useRef<Promise<WriteResult>>(Promise.resolve({ok:true})),writeSerial=useRef(0)
 const [taskHost,setTaskHost]=useState<HTMLDivElement|null>(null)
 const [language,setLanguage]=useState<'en'|'ar'>(()=>{try{return localStorage.getItem('dukkan-language')==='ar'?'ar':'en'}catch{return 'en'}})
 const [preparation,setPreparation]=useState<PreparationSummary|null>(null)
 const [page,setPage]=useState<Page>('today'),[mobileNav,setMobileNav]=useState(false),[search,setSearch]=useState(false),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState(initial.error)
 const [modal,setModal]=useState<''|'brief'|'hypothesis'|'evidence'|'backup'|'about'|'reset'|'restore'|'delete'>(''),[selected,setSelected]=useState(''),[panelTab,setPanelTab]=useState('evidence'),[editNote,setEditNote]=useState<Evidence|undefined>(),[linkId,setLinkId]=useState(''),[incoming,setIncoming]=useState<Workspace|null>(null),[pendingDelete,setPendingDelete]=useState<Evidence|null>(null)
 const titleRef=useRef<HTMLDivElement>(null),[evidenceFilter,setEvidenceFilter]=useState('All notes'),[assumptionFilter,setAssumptionFilter]=useState('All assumptions')
 function say(s:string){const epoch=session.current;void lastWrite.current.then(result=>{if(epoch===session.current)setNotice(result.ok?s:result.reason||'Changes could not be saved.')})}
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return ()=>clearTimeout(t)},[notice])
 useEffect(()=>{try{localStorage.setItem('dukkan-language',language)}catch{}document.documentElement.lang=language==='ar'?'ar':'en-GB'},[language])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 function commit(next:Workspace):Promise<WriteResult>{
  const parsed=workspaceSchema.safeParse({...next,updatedAt:new Date().toISOString()})
  if(!parsed.success)return lastWrite.current=Promise.resolve({ok:false,reason:'Invalid workspace changes were rejected.'})
  const updated=parsed.data,epoch=session.current,serial=++writeSerial.current
  currentWorkspace.current=updated;setW(updated)
  if(demo)return lastWrite.current=Promise.resolve({ok:true})
  realWorkspace.current=updated;setSaving(true)
  const persist=()=>!canWrite.current||!writer?{ok:false,reason:'Browser saving is unavailable. Export a backup before closing.'}:writer.persist(updated,()=>session.current===epoch)
  const pending=navigator.locks?navigator.locks.request(KEY,persist):Promise.resolve({ok:false,reason:'Safe browser saving requires Web Locks. Your edits remain in this tab; export a backup.'})
  lastWrite.current=pending.then(result=>{if(epoch===session.current&&serial===writeSerial.current){setSaving(false);setStorageError(result.ok?'':result.reason||'Saving failed.')}return result}).catch(()=>{const result={ok:false,reason:'Browser saving failed. Export a backup before closing.'};if(epoch===session.current){setSaving(false);setStorageError(result.reason)}return result})
  return lastWrite.current
 }
 function invalidateSession(){const url=new URL(location.href);url.searchParams.delete('conversation');history.replaceState(null,'',url);session.current++;setSessionId(session.current);lastWrite.current=Promise.resolve({ok:true});setSaving(false);setPreparation(null)}
 function replaceWorkspace(next:Workspace){invalidateSession();canWrite.current=true;try{writer?.acceptExplicitReplacement()}catch{canWrite.current=false}return commit(next)}
 function openPreparation(){if(!demo)realWorkspace.current=currentWorkspace.current;invalidateSession();setDemo(true);setMadar(true);const next=preparationExample();currentWorkspace.current=next;setW(next);setSelected('');setPage('kuwait');const url=new URL(location.href);url.searchParams.set('example','madar');history.replaceState(null,'',url)}
 function go(p:Page){setPage(p);setMobileNav(false);requestAnimationFrame(()=>{titleRef.current?.focus();window.scrollTo({top:0,behavior:'instant'})})}
 function openAssumption(h:Hypothesis,tab='evidence'){setSelected(h.id);setPanelTab(tab);go('workspace')}
 function addEvidence(id=''){setEditNote(undefined);setLinkId(id);setModal('evidence')}
 function editEvidence(e:Evidence){setEditNote(e);setLinkId(e.hypothesisId);setModal('evidence')}
 function enterExample(){if(!demo)realWorkspace.current=currentWorkspace.current;invalidateSession();setDemo(true);setMadar(false);const next=workedExample();currentWorkspace.current=next;setW(next);setPage('today')}
 function leaveExample(){invalidateSession();setDemo(false);setMadar(false);currentWorkspace.current=realWorkspace.current;setW(realWorkspace.current);setPage('today');setSelected('');setModal('');const url=new URL(location.href);url.searchParams.delete('example');history.replaceState(null,'',url)}
 const h=w.hypotheses.find(h=>h.id===selected),next=nextHypothesis(w),challengeCount=w.evidence.filter(e=>e.kind!=='Assumption'&&e.signal==='Challenges').length,reviewCount=w.hypotheses.filter(h=>h.reviewReason).length
 const businessName=shortName(w)
 const saveLabel=demo?'Example workspace':saving?'Saving…':storageError?'Not saved':initial.migrated?'Previous work carried forward':'Saved on this device'
 function working(){const current=h||next||w.hypotheses[0];if(!current)return <><PageHeading eyebrow="My plan" title="Start with your idea." description="Open My plan to make your starter plan."/><Button onClick={()=>setModal('brief')}>Describe my idea<ArrowRight size={15}/></Button></>;return <><div className="work-heading"><div><span className="home-eyebrow">Workspace</span><h1>Let’s work through this step.</h1></div><Button variant="outline" onClick={()=>go('plan')}>Back to my plan<ArrowRight size={15}/></Button></div><div className="connected-workspace"><details className="simple-help"><summary>Need help with this step?</summary><WorkspaceGuide key={current.id} workspace={w} hypothesis={current} demo={demo} onTest={()=>openAssumption(current,'test')} onEvidence={()=>openAssumption(current,'evidence')} onBrief={()=>setModal('brief')}/></details><AssumptionPanel embedded key={current.id+panelTab} workspace={w} hypothesis={current} initialTab={panelTab} onClose={()=>go('today')} onSave={draft=>{commit(saveTestPlan(w,draft));say(demo?'Test plan saved for this visit. My plan updated.':'Test plan saved. My plan updated.')}} onAddEvidence={()=>addEvidence(current.id)} onEditEvidence={editEvidence} onDecision={(a,outcome,reason)=>{if(w.decisions.length>=200){say('Export a backup; this version supports 200 decisions.');return}commit(recordDecision(w,a,outcome,reason));say('Decision saved with its evidence snapshot.')}}/></div></>}
 function savedWork(){return <section className="saved-work"><div className="home-section-heading"><h2>Saved work</h2><Button variant="outline" size="sm" onClick={()=>go('economics')}><SlidersHorizontal size={15}/>Cost scenario</Button></div>{preparation&&<button className="saved-test-row" onClick={()=>go('kuwait')}><FileText size={18}/><span><strong>{preparation.label}</strong><small>Madar synthetic preparation · Local service</small></span><ChevronRight size={16}/></button>}{w.savedTests.length?w.savedTests.slice().reverse().map(t=><button key={t.id} className="saved-test-row" onClick={()=>{const a=w.hypotheses.find(h=>h.id===t.hypothesisId);if(a)openAssumption(a,'test')}}><FlaskConical size={18}/><span><strong>{t.title}</strong><small>Test plan · {displayDate(t.date)}{demo?' · This visit only':''}</small></span><ChevronRight size={16}/></button>):<p>Saved test plans will appear here. Your source notes and decisions are below.</p>}</section>}
 function sidebar(mobile=false){return <><div className="agent-brand"><button className="brand-home" aria-label={language==='ar'?'الصفحة الرئيسية':'Dukkan home'} onClick={()=>go('today')}><Brand language={language}/></button><span className="agent-beta">Local</span></div><nav aria-label="Workspace">{pages.map(({id,label,icon:Icon})=><button key={id} aria-label={language==='ar'?id==='today'?'مساحة العمل':id==='plan'?'مشروعي':'المكتبة':label} className={`nav-item ${page===id||(id==='plan'&&['workspace','model','economics','kuwait'].includes(page))?'active':''}`} aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon size={17}/><span>{language==='ar'?id==='today'?'مساحة العمل':id==='plan'?'مشروعي':'المكتبة':label}</span></button>)}</nav>{!mobile&&<div className="agent-task-host" ref={setTaskHost}/>}<div className="sidebar-bottom"><button className="agent-business" onClick={()=>{go('plan')}}><Building2 size={17}/><span><strong>{language==='ar'?'مشروعك':'Your business'}</strong><small>{w.brief.idea?w.brief.idea:language==='ar'?'أضف فكرتك عندما تكون جاهزاً':'Add your idea when you’re ready'}</small></span></button><button className="nav-item" onClick={()=>setModal('about')}><Settings2 size={16}/><span>{language==='ar'?'الإعدادات والمساعدة':'Settings & help'}</span></button><button className="language-switch" onClick={()=>setLanguage(language==='en'?'ar':'en')} aria-label={language==='en'?'Switch to Arabic':'Switch to English'}>{language==='en'?'عربي':'English'}</button></div></>}
 function assumptionRow(a:Hypothesis,i:number){const s=signal(w,a);return <button className="assumption-row" key={a.id} onClick={()=>openAssumption(a)}><span className="row-number">{String(i+1).padStart(2,'0')}</span><span className="assumption-copy"><span className="meta">{a.area}{a.priority==='Critical'?' · Critical':''}</span><strong>{a.title}</strong><span className="row-evidence">{s.total?`${s.total} source notes${s.challenges?` · ${s.challenges} challenging`:''}`:'No linked source notes yet'}</span></span><Status h={a}/><ChevronRight className="row-arrow" size={16}/></button>}
 function overview(){if(w.brief.idea)return <HomeDashboard preparation={preparation?.label} workspace={w} demo={demo} selectedId={selected} onSelectTask={setSelected} onBrief={()=>setModal('brief')} onProfile={profile=>{commit({...w,profile});say('Business context saved.')}} onOpen={openAssumption} onEvidence={()=>go('evidence')} onNote={editEvidence} onCosts={()=>go('economics')} onSetup={()=>go('kuwait')}/>;return <StartPlan onStart={brief=>{commit(reviseBrief(w,brief));say('Your starter plan is ready. Choose a step to begin.')}} onExample={enterExample}/>}
 function model(){const filtered=w.hypotheses.filter(a=>assumptionFilter!=='Needs review'||a.reviewReason||a.status==='Revisit');return <><PageHeading eyebrow="The logic behind the business" title="Your idea and what to check" description="Write down what you think will work. Add notes as you learn." action={<Button onClick={()=>setModal('hypothesis')}><Plus size={15}/>Add a question</Button>}/><div className="model-brief"><div><span className="meta">Working business hypothesis</span><h2>{businessName}</h2><p>{w.brief.problem||'Describe the customer problem in your business brief.'}</p></div><Button variant="outline" onClick={()=>setModal('brief')}>Edit idea<ArrowUpRight size={14}/></Button></div><Tabs value={assumptionFilter} onValueChange={setAssumptionFilter}><TabsList><TabsTrigger value="All assumptions">All assumptions</TabsTrigger><TabsTrigger value="Needs review">Needs review{reviewCount>0?` (${reviewCount})`:''}</TabsTrigger></TabsList></Tabs><div className="assumption-table model-table">{filtered.length?filtered.map(assumptionRow):<div className="empty-state"><Layers3/><h2>{w.hypotheses.length?'No assumptions flagged for review.':'Give the business something testable.'}</h2><p>{w.hypotheses.length?'Changes to your customer, offer or constraints will appear here.':'Start with the claim most likely to change your decision.'}</p></div>}</div><div className="small-guidance"><GitBranch size={18}/><div><strong>Your reasoning should survive a change of direction.</strong><p>When the customer or offer changes, existing assumptions are flagged for review. Previous decisions retain the evidence they were based on.</p></div></div></>}
 function evidence(){const notes=w.evidence.filter(e=>evidenceFilter==='All notes'||e.signal===evidenceFilter);return <><PageHeading eyebrow="Your business memory" title="Your saved work" description="Find your plans, notes and past decisions here." action={<Button onClick={()=>addEvidence()}><Plus size={15}/>Add a note</Button>}/>{savedWork()}<Tabs defaultValue="notebook"><TabsList><TabsTrigger value="notebook">Notebook <span className="tab-count">{w.evidence.length}</span></TabsTrigger><TabsTrigger value="decisions">Decisions <span className="tab-count">{w.decisions.length}</span></TabsTrigger></TabsList><TabsContent value="notebook"><div className="notebook-toolbar"><p>{challengeCount?`${challengeCount} source ${challengeCount===1?'note challenges':'notes challenge'} an assumption.`:'Observations, sources and assumptions stay labelled.'}</p><Choice label="Filter evidence" value={evidenceFilter} onChange={setEvidenceFilter} options={['All notes','Supports','Challenges','Unclear']}/></div><div className="evidence-grid">{notes.map(e=><Card key={e.id}><CardContent><EvidenceNote note={e} assumption={w.hypotheses.find(h=>h.id===e.hypothesisId)?.title||'Not linked to an assumption'} onEdit={()=>editEvidence(e)}/>{e.hypothesisId&&<Button variant="ghost" size="sm" onClick={()=>{const h=w.hypotheses.find(h=>h.id===e.hypothesisId);if(h)openAssumption(h)}}>Follow the connection<ArrowRight size={14}/></Button>}</CardContent></Card>)}</div>{!notes.length&&<div className="empty-state"><BookOpen/><h2>No notes here yet.</h2><p>Add something a customer actually said or did, or a source you can inspect.</p></div>}</TabsContent><TabsContent value="decisions"><div className="decision-timeline">{w.decisions.slice().reverse().map(d=><article key={d.id} className="decision-record"><span className="timeline-dot"><GitBranch size={16}/></span><div className="meta">{new Date(d.date).toLocaleDateString('en-GB')}<Badge variant="outline">{d.outcome}</Badge></div><h2>{d.assumption}</h2><p>{d.reason}</p><details><summary>{d.evidence.length} evidence snapshots · View reasoning</summary><p className="section-copy">Decision rule: {d.rule||'Not recorded'}</p>{d.evidence.map(e=><EvidenceNote key={e.id} note={e}/>)}</details></article>)}</div>{!w.decisions.length&&<div className="empty-state"><GitBranch/><h2>The reasoning starts with your first decision.</h2><p>Open an assumption, review its evidence, then record whether to keep testing, proceed, revise or pause.</p><Button variant="outline" onClick={()=>go('model')}>Review assumptions<ArrowRight size={15}/></Button></div>}</TabsContent></Tabs></>}
 function economics(){const c=calculate(w.costs);return <><PageHeading eyebrow="Money" title="Could the numbers work?" description="Add your best estimates. See what you would need to sell to cover your costs."/><div className="economics-grid"><Card><CardContent><div className="section-label"><h2>A monthly operating scenario</h2><Badge variant="outline">Your estimates</Badge></div><div className="two-fields">{([['price','Selling price per unit'],['variable','Variable cost per unit'],['fixed','Monthly fixed costs'],['units','Units sold per month']] as const).map(([k,label])=><Field key={k} label={label+(k==='units'?'':' (KWD)')} type="number" value={w.costs[k]} onChange={v=>commit({...w,costs:{...w.costs,[k]:v}})} placeholder={k==='units'?'30':'0.000'}/>)}</div><div className="calculation-footnote"><p>Contribution = price − variable cost. Result = units × contribution − fixed costs. Break-even is rounded up.</p><p>Excludes startup investment, financing, tax and cash timing. KWD amounts use three decimal places.</p></div></CardContent></Card><section className="scenario-result" aria-live="polite"><span className="eyebrow">What those numbers mean</span><div className="scenario-main"><strong>{c.valid&&c.breakEven!==null?c.breakEven:'—'}</strong><span>units to break even each month</span></div><div className="scenario-detail"><span>Contribution per unit</span><strong>{c.valid?`KWD ${formatMoney(c.margin)}`:'—'}</strong></div><div className="scenario-detail"><span>Monthly operating result</span><strong>{c.valid?`KWD ${formatMoney(c.result)}`:'—'}</strong></div><p>{c.message}</p></section></div><div className="section-label below"><div><h2>Which number is least certain?</h2><p className="section-copy">Turn the weakest estimate into a cost or supplier check.</p></div><Button variant="outline" onClick={()=>setModal('hypothesis')}><Plus size={14}/>Add an economics assumption</Button></div><div className="assumption-table">{w.hypotheses.filter(h=>h.area==='Economics'||h.area==='Delivery').map(assumptionRow)}</div><NextAction workspace={w} onChange={nextAction=>commit({...w,nextAction})}/></>}
 function kuwaitNotes(){return <><PageHeading eyebrow="Local preparation, with sources" title="Find the route that fits." description="Track the questions that depend on your activity and circumstances. Confirm the answers with the relevant authority."/><div className="local-context"><MapPin size={18}/><span>{w.brief.location||'Kuwait'}</span><span className="context-divider"/><span>{w.brief.sector}</span><Button variant="ghost" size="sm" onClick={()=>setModal('brief')}>Update<ArrowUpRight size={13}/></Button></div><div className="setup-layout"><section>{setupItems.map((item,i)=>{const record=w.setup.find(s=>s.id===item.id)||{id:item.id,done:false,note:'',source:'',date:''};const update=(patch:Partial<typeof record>)=>commit({...w,setup:[...w.setup.filter(s=>s.id!==item.id),{...record,...patch}]});return <article className="setup-item" key={item.id}><div className="setup-number">0{i+1}</div><div className="setup-content"><div className="section-label"><h2>{item.title}</h2><Badge variant="outline">{record.done?'Reviewed by you':'Open question'}</Badge></div><p>{item.question}</p><a className="source-link" href={item.url} target="_blank" rel="noopener noreferrer">{item.source}<ArrowUpRight size={14}/></a><details><summary>Record what you confirmed{record.note?' · Note saved':''}</summary><Field label="Answer or remaining question" multiline value={record.note} onChange={note=>update({note})}/><Field label="Exact source or adviser reference" value={record.source} onChange={source=>update({source})}/><Field label="Date checked" type="date" value={record.date} onChange={date=>update({date})}/><label className="check-label"><Checkbox checked={record.done} onCheckedChange={done=>{if(done&&(!record.note.trim()||!record.source.trim()||!record.date)){say('Add an answer, source and date before marking this reviewed.');return}update({done:!!done})}}/>I reviewed the applicable requirements</label></details></div></article>})}</section><aside className="local-reading"><div className="eyebrow">Market context</div><h2>Find people.<br/>Then hear them out.</h2><p>Ipsos’s Kuwait research identifies social media and word of mouth as common brand information sources. Use that as a starting point for finding customers to speak to.</p><a href="https://www.ipsos.com/en-kw/spotlightkuwait-shopper-behaviour-attitudes" target="_blank" rel="noopener noreferrer">Read the source<ArrowUpRight size={14}/></a><span className="meta">Ipsos · June 2026</span><div className="source-boundary"><ShieldCheck size={17}/><p>Broad market context does not establish demand for your offer. Record business-specific evidence in your notebook.</p></div></aside></div><div className="small-guidance"><Building2 size={18}/><p>Official links are handoffs. Dukkan does not submit applications or confirm eligibility. A reviewed question is your preparation record, not an approval.</p></div><NextAction workspace={w} onChange={nextAction=>commit({...w,nextAction})}/></>}
 function kuwait(){const epoch=session.current;return <Tabs key={'setup-'+sessionId} defaultValue={madar?'preparation':'notes'}><TabsList aria-label="Kuwait setup areas"><TabsTrigger value="notes">Setup notes</TabsTrigger><TabsTrigger value="preparation">Preparation companion</TabsTrigger></TabsList><TabsContent value="notes">{kuwaitNotes()}</TabsContent><TabsContent value="preparation"><PreparationPanel key={sessionId} onProgress={summary=>{if(epoch===session.current)setPreparation(summary)}} active={demo&&madar} workspace={w} onOpen={openPreparation} onApply={async(expected,action)=>{if(epoch!==session.current)return {ok:false,reason:'Workspace session changed. Follow-up was not applied.'};try{return await commit(applyNextAction(currentWorkspace.current,expected,action))}catch(e){return {ok:false,reason:e instanceof Error?e.message:'Invalid follow-up rejected.'}}}}/></TabsContent></Tabs>}
 return <div className={`app-shell agent-ui ${page==='today'?'chat-first-shell':''} ${language==='ar'?'arabic-ui':''}`}><a className="skip-link" href="#workspace-main">Skip to workspace</a><aside className="sidebar" dir={language==='ar'?'rtl':'ltr'}>{sidebar()}</aside><div className="workspace-shell"><header className="workspace-header"><Button className="mobile-menu" size="icon" variant="ghost" aria-label="Open navigation" onClick={()=>setMobileNav(true)}><Menu size={18}/></Button><div className="breadcrumb"><span>{businessName}</span><ChevronRight size={12}/><strong>{[...pages,...workspacePages].find(p=>p.id===page)?.label}</strong></div><div className="header-tools"><button className="search-launch" aria-label="Find in your business" onClick={()=>setSearch(true)}><Search size={15}/><span>Find in your business</span><kbd>⌘ K</kbd></button><span className="save-state"><span className={storageError?'unsaved':''}/>{saveLabel}</span><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label="Workspace actions"><MoreHorizontal size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>{download((demo?'# Worked example — fictional records\n\n':'')+exportPlan(w),'dikan-decision-record.md','text/markdown');say('Decision record downloaded.')}}><ArrowDownToLine size={15}/>Export decision record</DropdownMenuItem><DropdownMenuItem disabled={demo} onSelect={()=>setModal('backup')}><FileText size={15}/>Backup & restore</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>setModal('about')}>About this version</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
 {demo&&<div className="demo-banner" dir={language==='ar'?'rtl':'ltr'}><FlaskConical size={15}/><span><strong>{language==='ar'?'مساحة تجريبية':'Illustrative workspace'}</strong> · {language==='ar'?'بيانات تخيلية. تبقى التغييرات لهذه الزيارة فقط.':'Fictional records. Changes last for this visit.'}</span><Button variant="ghost" size="sm" onClick={leaveExample}>{language==='ar'?'العودة إلى مساحة عملي':'Back to my workspace'}<X size={14}/></Button></div>}{storageError&&!demo&&<div className="storage-banner" role="alert">{storageError}<Button variant="outline" size="sm" onClick={()=>setModal('backup')}>Backup options</Button></div>}
 <main id="workspace-main" ref={titleRef} tabIndex={-1}>{['workspace','model','economics','kuwait'].includes(page)&&<nav className="work-tools" aria-label="Workspace tools">{workspacePages.map(({id,label,icon:Icon})=><Button key={id} variant="ghost" aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon size={15}/>{label}</Button>)}</nav>}<div hidden={page!=='today'}><ChatWorkspace workspaceContext={w} key={sessionId} scope={demo?(madar?'madar':'example'):'personal'} taskHost={taskHost} onActivate={()=>go('today')} language={language} demo={demo} onSaveBrief={brief=>{void commit(reviseBrief(w,brief));say(language==='ar'?'حُفظت فكرة المشروع.':'Business idea saved.')}} onSaveCosts={costs=>{void commit({...w,costs});say(language==='ar'?'حُفظت التقديرات.':'Estimates saved.')}} onSaveTest={test=>{void commit(saveTestPlan(w,test));say(language==='ar'?'حُفظت خطة الاختبار.':'Test plan saved.')}} onOpenEvidence={()=>{addEvidence(w.hypotheses[0]?.id||'')}} onOpenSetup={()=>go('kuwait')}/></div>{page==='today'?null:page==='plan'?overview():page==='workspace'?working():page==='model'?model():page==='evidence'?evidence():page==='economics'?economics():kuwait()}<footer hidden={page==='today'} className="workspace-footer"><span>{demo?'Fictional example · Changes last for this visit':'Local workspace · Saved in this browser'} · No government submission</span><button onClick={()=>setModal('about')}>About this version<Link2 size={12}/></button></footer></main></div>
 <Sheet open={mobileNav} onOpenChange={setMobileNav}><SheetContent side={language==='ar'?'right':'left'} className="mobile-sidebar" dir={language==='ar'?'rtl':'ltr'}><SheetHeader className="sr-only"><SheetTitle>Navigate Dukkan</SheetTitle><SheetDescription>Your business workspace sections</SheetDescription></SheetHeader>{sidebar(true)}</SheetContent></Sheet>
 <CommandDialog open={search} onOpenChange={setSearch} title="Find in your business" description="Search workspace sections and your assumptions."><CommandInput placeholder="Search assumptions, notes or sections…"/><CommandList><CommandEmpty>No matches. Try another word.</CommandEmpty><CommandGroup heading="Your workspace">{[...pages,...workspacePages.filter(p=>p.id!=='workspace')].map(p=><CommandItem key={p.id} onSelect={()=>{setSearch(false);go(p.id)}}>{p.label}</CommandItem>)}</CommandGroup><CommandGroup heading="Assumptions">{w.hypotheses.map(h=><CommandItem key={h.id} onSelect={()=>{setSearch(false);openAssumption(h)}}>{h.title}</CommandItem>)}</CommandGroup><CommandGroup heading="Evidence">{w.evidence.map(e=><CommandItem key={e.id} onSelect={()=>{setSearch(false);editEvidence(e)}}>{e.text}</CommandItem>)}</CommandGroup></CommandList></CommandDialog>
 {modal==='brief'&&<BriefEditor brief={w.brief} onClose={()=>setModal('')} onSave={brief=>{commit(reviseBrief(w,brief));setModal('');say('Brief saved. Changed assumptions are flagged for review.')}}/>}
 {modal==='hypothesis'&&<HypothesisEditor onClose={()=>setModal('')} onSave={h=>{if(w.hypotheses.length>=100){say('This local version supports 100 assumptions.');return}commit({...w,hypotheses:[...w.hypotheses,h]});setModal('');openAssumption(h,'test')}}/>}
 {modal==='evidence'&&<EvidenceEditor workspace={w} initial={editNote} hypothesisId={linkId} onClose={()=>setModal('')} onSave={e=>{if(!editNote&&w.evidence.length>=200){say('This local version supports 200 notes.');return}commit({...w,evidence:editNote?w.evidence.map(n=>n.id===e.id?e:n):[...w.evidence,e]});setModal('');say('Evidence saved and linked.')}} onDelete={e=>{setPendingDelete(e);setModal('delete')}}/>}
 {modal==='delete'&&pendingDelete&&<EditorFrame title="Remove this note?" description="This removes the notebook entry. Existing decisions keep their evidence snapshots." onClose={()=>setModal('')}><p>{pendingDelete.text}</p><div className="editor-footer"><Button variant="outline" onClick={()=>setModal('')}>Keep note</Button><Button variant="destructive" onClick={()=>{commit({...w,evidence:w.evidence.filter(e=>e.id!==pendingDelete.id)});setModal('');say('Note removed. Decision snapshots retained.')}}>Remove note</Button></div></EditorFrame>}
 {modal==='about'&&<EditorFrame title="A workspace for better decisions." description="Dukkan connects business assumptions, local context and the evidence behind your choices." onClose={()=>setModal('')}><div className="about-copy"><p>Built with React and official shadcn/ui components, adapted to the Dukkan identity. Suggested focus uses visible prioritisation rules.</p><p>Chat reports its actual mode: local AI or a scripted demo. The older workspace guide uses rules, not AI. Preparation reports its own execution mode. No government submission, verified adviser network or account sync is provided.</p><p>Business notes stay in this browser. Conversations and draft files are stored by the local service and may expire. Export reviewed files and back up your workspace to keep a copy. Source links open external websites.</p></div><div className="editor-footer">{!demo&&<Button variant="outline" onClick={()=>{setModal('');enterExample()}}>Explore worked example</Button>}<Button onClick={()=>setModal('')}>Back to work</Button></div></EditorFrame>}
 {modal==='backup'&&<EditorFrame title="Keep a copy of your work." description="Backups include your brief, assumptions, linked notes, decisions and source snapshots." onClose={()=>setModal('')}><Button onClick={()=>download(JSON.stringify(w,null,2),'dikan-workspace-v2.json','application/json')}><ArrowDownToLine size={16}/>Download workspace backup</Button><div className="field"><label htmlFor="restore-file">Restore a v1 or v2 Dukkan backup</label><input id="restore-file" type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>4000000)throw new Error();setIncoming(migrate(JSON.parse(await f.text())));setModal('restore')}catch{say('That file is not a valid Dukkan backup.')}e.target.value=''}}/></div><p className="field-hint">Older workspace records are migrated without overwriting the original browser data. Original v1 information is also retained inside the backup.</p><Button variant="ghost" className="delete-note" onClick={()=>setModal('reset')}>Start a new workspace</Button></EditorFrame>}
 {modal==='restore'&&incoming&&<EditorFrame title="Replace this workspace?" description="The imported backup replaces the current v2 records. Download a copy first if you want to keep them." onClose={()=>setModal('')}><div className="editor-footer"><Button variant="outline" onClick={()=>setModal('backup')}>Go back</Button><Button onClick={()=>{replaceWorkspace(incoming);setModal('');setSelected('');go('today');say('Workspace restored.')}}>Restore backup</Button></div></EditorFrame>}
 {modal==='reset'&&<EditorFrame title="Start a new workspace?" description="This clears the current v2 workspace. Your earlier v1 records are untouched. Back up first to retain this version." onClose={()=>setModal('')}><div className="editor-footer"><Button variant="outline" onClick={()=>setModal('backup')}>Keep my work</Button><Button variant="destructive" onClick={()=>{replaceWorkspace(blank());setSelected('');setModal('');go('today')}}>Clear workspace</Button></div></EditorFrame>}
 {notice&&<div className="app-toast" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 </div>
}

function NextAction({workspace,onChange}:{workspace:Workspace;onChange:(a:Workspace['nextAction'])=>void}){return <section className="next-action"><div><span className="eyebrow">Make it practical</span><h2>One next action.</h2><p>Give the next step an owner and a dependency.</p></div><div className="next-action-fields"><Field label="What will you do?" value={workspace.nextAction.task} onChange={task=>onChange({...workspace.nextAction,task})}/><div className="two-fields"><Field label="Owner" value={workspace.nextAction.owner} onChange={owner=>onChange({...workspace.nextAction,owner})}/><Field label="Date (optional)" type="date" value={workspace.nextAction.due} onChange={due=>onChange({...workspace.nextAction,due})}/></div><Field label="What must happen first?" value={workspace.nextAction.dependency} onChange={dependency=>onChange({...workspace.nextAction,dependency})}/></div></section>}
