import { createHash } from 'node:crypto';
export const schemaVersion = 1;
export const toolNames = ['retrieve_guidance','inspect_documents','request_information','assemble_pack','apply_preparation_patch'] as const;
export type ToolName = typeof toolNames[number];
export type Status = 'queued'|'running'|'needs_input'|'blocked'|'retry_wait'|'awaiting_review'|'completed'|'failed'|'cancelled'|'superseded';
export type Fact = {field:string;value:unknown;origin:string;sourceRef:string|null;confirmedBy:string|null;confirmedAt:string|null};
export type CaseSnapshot = {schemaVersion:1;businessId:string;businessRevision:number;facts:Fact[];factsHash:string;documentVersionIds:string[];corrections:unknown[];[key:string]:unknown};
export type DocumentVersion = {id:string;businessId:string;contentHash:string;mime:string;bytes:number;storageKey:string;expiresAt:string;extractionStatus:string;name:string};
export type ToolCall = {jobId:string;callId:string;businessRevision:number;name:ToolName|'prepare_enquiry'|'prepare_application';arguments:Record<string,unknown>};
export type ToolContext = {caseSnapshot:CaseSnapshot;job:Record<string,any>;documents:DocumentVersion[];privateRoot:string;outputDir:string;previousResults:Record<string,any>;signal:AbortSignal};
export type ToolResult = {ok:boolean;data?:any;error?:{code:string;message:string;retryable?:boolean};provenance:unknown[]};
export type ToolExecutor = (call:ToolCall, context:ToolContext)=>Promise<ToolResult>;
export type ModelAdapter = {name:string;version:string;next:(context:{job:Record<string,any>;tools:readonly string[];results:Record<string,any>;signal:AbortSignal})=>Promise<{tool:ToolName;arguments:Record<string,unknown>}|{done:true}>};
export class ApiError extends Error {status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code;}}
export function ensure(condition:unknown,code:string,message:string,status=400):asserts condition {if(!condition)throw new ApiError(status,code,message);}
export function canonical(value:any):string {if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
export function hash(value:any):string{return createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:canonical(value)).digest('hex');}
const transitions:Record<Status,Status[]>={queued:['running','cancelled','superseded','failed'],running:['needs_input','blocked','retry_wait','awaiting_review','failed','cancelled','superseded'],needs_input:['superseded','cancelled'],blocked:['superseded','cancelled'],retry_wait:['running','failed','cancelled','superseded'],awaiting_review:['completed','superseded','cancelled'],completed:['superseded'],failed:['superseded','cancelled'],cancelled:[],superseded:[]};
export function assertTransition(from:Status,to:Status){ensure(transitions[from]?.includes(to),'INVALID_TRANSITION',`Cannot transition ${from} to ${to}`,409);}
export function validateFacts(facts:any):asserts facts is Fact[]{ensure(Array.isArray(facts)&&facts.length<=100,'INVALID_FACTS','facts must be an array, at most 100');const keys=new Set();for(const f of facts){ensure(f&&typeof f.field==='string'&&/^[A-Za-z][A-Za-z0-9_.]{0,99}$/.test(f.field)&&!keys.has(f.field),'INVALID_FACT','Each fact needs a unique field');keys.add(f.field);ensure('value'in f&&typeof f.origin==='string'&&(f.sourceRef===null||typeof f.sourceRef==='string'),'INVALID_FACT','Fact value, origin and sourceRef required');ensure(f.value===null||(typeof f.confirmedBy==='string'&&f.confirmedBy.length>0&&typeof f.confirmedAt==='string'&&!Number.isNaN(Date.parse(f.confirmedAt))),'UNCONFIRMED_FACT','Non-null facts require explicit confirmation');}}
export function validateToolResult(result:any):asserts result is ToolResult{ensure(result&&typeof result.ok==='boolean'&&Array.isArray(result.provenance),'INVALID_TOOL_RESULT','Tool must return ok and provenance',500);if(!result.ok)ensure(result.error&&typeof result.error.code==='string'&&typeof result.error.message==='string','INVALID_TOOL_RESULT','Failed tool requires typed error',500);}

export type PreparationJob = {schemaVersion:1;jobId:string;businessId:string;businessRevision:number;factsHash:string;requirementSetVersion:null;sourceSnapshotHash:string;documentVersionIds:string[];inputHash:string;status:Status;step:string;reasonCode:string|null;executionMode:'deterministic'|'live_agent'|'replay';supersedesJobId:string|null;resultRefs:Record<string,string>;trace:ToolTrace[];questions:unknown[];toolCallCount:number;model: {name:string;version:string}|null;modelTrace?:unknown[];error?:{code:string;message:string}};
export type ToolTrace = {callId:string;name:ToolName;attempt:number;ok:boolean;error:ToolResult['error']|null;at:string;provenance:unknown[]};
export type Pack = {schemaVersion:1;downloadFilename?:'dikan-incomplete-preparation.html';id:string;version:number;jobId:string;businessId:string;businessRevision:number;inputHash:string;factsHash:string;documentVersionIds:string[];createdAt:string;incomplete:true;label:string;checks:unknown[];blockers:unknown[];sources:unknown[];html:string;hash:string};
export type Review = {schemaVersion:1;id:string;packHash:string;businessRevision:number;actor:string;at:string;valid:boolean;kind:'incomplete_draft_review';label:string;invalidatedAt?:string};
export type Handoff = {packHash:string|null;state:'blocked';reasonCode:string;destinationRef:string;exportedAt?:string;exportKind?:'incomplete_preparation_worksheet'};
