import {useState} from 'react'
import {ArrowUpRight,BookOpen,FlaskConical,GitBranch,Link2,Plus,AlertCircle} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Badge} from '@/components/ui/badge'
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet'
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs'
import {Field,Choice} from '@/components/fields'
import {linked,signal,outcomes,type Workspace,type Hypothesis,type Evidence,type Decision} from '@/lib/workspace'

export function EvidenceNote({note,onEdit,assumption}:{note:Evidence;onEdit?:()=>void;assumption?:string}){
 const url=/^https?:\/\//i.test(note.source)?note.source:null
 return <article className="evidence-note"><div className="note-top"><span className={`signal-mark ${note.signal.toLowerCase()}`}/><span className="meta">{note.kind}</span><Badge variant="outline" className={`signal-badge ${note.signal.toLowerCase()}`}>{note.signal}</Badge></div><p className="note-quote">{note.text}</p><div className="note-source">{url?<a href={url} target="_blank" rel="noopener noreferrer">{note.source}<ArrowUpRight size={12}/></a>:<span>{note.source}</span>}<span>{note.date}</span></div>{assumption&&<p className="linked-label"><Link2 size={12}/>{assumption}</p>}{note.limitation&&<p className="field-hint">Limit: {note.limitation}</p>}{onEdit&&<Button variant="ghost" size="sm" onClick={onEdit}>Edit note</Button>}</article>
}
export function AssumptionPanel({workspace,hypothesis,onClose,onSave,onAddEvidence,onEditEvidence,onDecision,initialTab='evidence',embedded=false}:{workspace:Workspace;hypothesis:Hypothesis;onClose:()=>void;onSave:(h:Hypothesis)=>void;onAddEvidence:()=>void;onEditEvidence:(e:Evidence)=>void;onDecision:(h:Hypothesis,outcome:Decision['outcome'],reason:string)=>void;initialTab?:string;embedded?:boolean}){
 const [draft,setDraft]=useState(hypothesis),[tab,setTab]=useState(initialTab),[outcome,setOutcome]=useState<Decision['outcome']>('Keep testing'),[reason,setReason]=useState(''),[error,setError]=useState('')
 const notes=linked(workspace,hypothesis.id),signals=signal(workspace,hypothesis),decisions=workspace.decisions.filter(d=>d.hypothesisId===hypothesis.id)
 const test=(key:keyof Hypothesis['test'],value:string)=>setDraft({...draft,test:{...draft.test,[key]:value}})
 const body=<div className="sheet-scroll">
  {hypothesis.reviewReason&&<div className="review-alert"><AlertCircle size={17}/><p>{hypothesis.reviewReason} Record a decision after your review to clear this flag.</p></div>}
  <div className="connection-strip"><span><BookOpen size={14}/>{signals.total} source notes</span><i/><span><FlaskConical size={14}/>{workspace.savedTests.some(t=>t.hypothesisId===hypothesis.id)?'1 saved test':hypothesis.test.audience&&hypothesis.test.rule?'1 draft test':'No test yet'}</span><i/><span><GitBranch size={14}/>{decisions.length} decisions</span></div>
  <Tabs value={tab} onValueChange={setTab}><TabsList className="panel-tabs"><TabsTrigger value="evidence">Your notes</TabsTrigger><TabsTrigger value="test">Make a plan</TabsTrigger><TabsTrigger value="decide">Choose what’s next</TabsTrigger></TabsList>
   <TabsContent value="evidence"><div className="section-label"><h3>What have you learned?</h3><Button size="sm" onClick={onAddEvidence}><Plus size={14}/>Add a note</Button></div>{notes.length?notes.map(e=><EvidenceNote key={e.id} note={e} onEdit={()=>onEditEvidence(e)}/>):<div className="empty-state"><BookOpen/><h3>No notes for this step yet.</h3><p>Start with a recent customer experience or a source you can return to.</p></div>}<div className="small-guidance"><strong>Ask about the last time.</strong><p>What happened? What did they do instead? What did it cost them? Keep observations distinct from assumptions.</p></div></TabsContent>
   <TabsContent value="test"><form onSubmit={e=>{e.preventDefault();if(!draft.title.trim()){setError('Write the question you want to check.');return}if(!draft.test.audience.trim()||!draft.test.rule.trim()){setError('Add who you’ll ask and what result you’re looking for.');return}onSave({...draft,status:draft.status==='Unexplored'?'Testing':draft.status});setError('')}}><Field label="What do you want to find out?" value={draft.title} onChange={title=>setDraft({...draft,title})} multiline required/><div className="two-fields"><Choice label="Priority" value={draft.priority} onChange={priority=>setDraft({...draft,priority:priority as Hypothesis['priority']})} options={['Critical','Important','Later']}/><Choice label="How will you check?" value={draft.test.method||'Customer conversations'} onChange={v=>test('method',v)} options={['Customer conversations','Observe behaviour','Prototype test','Interest list','Cost or supplier check','Official source check','Other']}/></div><Field label="Who will you ask, or what will you check?" value={draft.test.audience} onChange={v=>test('audience',v)} placeholder="Three people who recently encountered this problem"/><Field label="What would make you keep going or change the idea?" value={draft.test.rule} onChange={v=>test('rule',v)} multiline placeholder="For example: if 3 of 5 people agree to try it, I’ll make a small sample." hint="Choose this before you start. A small test helps you learn; it does not prove everyone will want your idea."/><Field label="What happened?" value={draft.test.result} onChange={v=>test('result',v)} multiline placeholder="Actual findings, including anything that challenges the idea."/><p className="form-error" role="alert">{error}</p><Button type="submit">Save my plan</Button></form></TabsContent>
   <TabsContent value="decide"><h3>What will you do next?</h3><p className="section-copy">Save your choice and why you made it. A copy of your notes stays with it.</p>{signals.challenges>0&&<div className="review-alert"><AlertCircle size={16}/><p>{signals.challenges} source note{signals.challenges===1?'':'s'} challenge this assumption. Address the contradiction in your reasoning.</p></div>}<form onSubmit={e=>{e.preventDefault();if(!reason.trim()){setError('Explain the decision before recording it.');return}if(outcome==='Supported so far'&&!signals.total){setError('Link a customer observation or source before marking this supported.');return}onDecision(hypothesis,outcome,reason);setReason('');setError('')}}><Choice label="Your decision" value={outcome} options={outcomes} onChange={v=>setOutcome(v as Decision['outcome'])}/><Field label="Why this decision?" value={reason} onChange={setReason} multiline required placeholder="What changed your thinking, and what remains uncertain?"/><p className="form-error" role="alert">{error}</p><Button type="submit">Record decision<GitBranch size={14}/></Button></form>{decisions.length>0&&<div className="decision-history"><h3>Previous decisions</h3>{decisions.slice().reverse().map(d=><div key={d.id} className="history-item"><span className="meta">{new Date(d.date).toLocaleDateString('en-GB')} · {d.outcome}</span><p>{d.reason}</p><span className="meta">{d.evidence.length} evidence snapshots retained</span></div>)}</div>}</TabsContent>
  </Tabs>
 </div>
 if(embedded)return <section className="work-document"><header><span className="home-eyebrow">This step</span><h2>{hypothesis.title}</h2><p>{hypothesis.area} · {hypothesis.priority} priority · {hypothesis.status}</p></header>{body}</section>
 return <Sheet open onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="assumption-sheet"><SheetHeader><div className="eyebrow">One assumption, the whole story</div><SheetTitle>{hypothesis.title}</SheetTitle><SheetDescription>{hypothesis.area} · {hypothesis.priority} priority · {hypothesis.status}</SheetDescription></SheetHeader>{body}</SheetContent></Sheet>
}
