import {hasMatchingReview} from './document-revision'
import {useState} from 'react'
import {ChevronRight,MessageCircle,FileText,Users,FlaskConical,ClipboardList,AlertCircle,Calculator,ArrowUpRight,History,X,Compass} from 'lucide-react'
import type {Workspace} from '../lib/workspace'
import type {ChatArtifact} from '../lib/chat-api'
import type {LifecycleRecord} from '../../../shared/lifecycle'
import {evidenceSummary} from '../lib/research'
import {recordImpact,impactLabels} from '../lib/business-impact'
import './business-overview.css'
export const officialDocumentPrompt='Prepare an official business setup document for my saved business. Use only my confirmed facts, leave unknown fields blank, list what is missing, and do not submit anything.'
type Props={language:'en'|'ar';workspace:Workspace;name:string;artifacts:ChatArtifact[];nextTitle:string;nextDescription:string;decision?:{id?:string;label:string;reason:string};onStart:()=>void;onContinue:()=>void;onRecords:()=>void;onMarket:()=>void;onCosts:()=>void;onWork:(row:LifecycleRecord)=>void;onOpenArtifact:(artifact:ChatArtifact)=>void;onLicences:()=>void;onPdf:()=>void;onDraft:(prompt:string)=>void;demo?:boolean}
export function BusinessOverview({language,workspace,name,artifacts,nextTitle,nextDescription,decision,onStart,onContinue,onRecords,onMarket,onCosts,onWork,onOpenArtifact,onLicences,onPdf,onDraft,demo}:Props){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en,[panel,setPanel]=useState<'actions'|'documents'|null>(null)
 const evidence=evidenceSummary(workspace.evidence),open=workspace.lifecycle.filter(r=>!['completed','archived'].includes(r.values.status||''))
 const attention=open.map(row=>({row,impact:recordImpact(workspace,row)})).filter(({row,impact})=>impact.missing||impact.changed.length||row.values.due&&row.values.due<new Date().toISOString().slice(0,10))
 const facts=[{icon:Users,value:evidence.direct,label:tr('Observations','الملاحظات'),action:onMarket},{icon:FlaskConical,value:workspace.savedTests.length,label:tr('Tests','الاختبارات'),action:onMarket},{icon:FileText,value:artifacts.length,label:tr('Documents','المستندات'),action:()=>setPanel('documents')},{icon:ClipboardList,value:open.length,label:tr('Open actions','الإجراءات المفتوحة'),action:()=>setPanel('actions')}]
 const decisionRecord=workspace.lifecycle.find(row=>row.id===decision?.id)
 return <div className="business-overview-page"><header><div><span className="dukkan-kicker">{tr('Business overview','نظرة عامة على المشروع')}</span><h1>{name}</h1><p>{workspace.brief.offer||workspace.brief.idea||tr('Add your idea to start building your business.','أضف فكرتك لتبدأ بناء مشروعك.')}</p></div><button className="overview-primary" onClick={onContinue}><MessageCircle size={18}/>{tr('Continue conversation','تابع المحادثة')}</button></header>
 <section className="overview-metrics" aria-label={tr('Business shortcuts','اختصارات المشروع')}>{facts.map(({icon:Icon,value,label,action})=><button key={label} onClick={action} title={tr('Open ','افتح ')+label}><Icon size={21}/><strong>{value}</strong><span>{label}</span><ArrowUpRight size={15}/></button>)}</section>
 {panel&&<section className="overview-open-panel" aria-label={panel==='actions'?tr('Open actions','الإجراءات المفتوحة'):tr('Document review','مراجعة المستندات')}><header><h2>{panel==='actions'?<ClipboardList size={18}/>:<FileText size={18}/>} {panel==='actions'?tr('Open actions','الإجراءات المفتوحة'):tr('Document review','مراجعة المستندات')}</h2><button title={tr('Close list','إغلاق القائمة')} aria-label={tr('Close list','إغلاق القائمة')} onClick={()=>setPanel(null)}><X size={18}/></button></header>{panel==='actions'?(open.length?open.map(row=><button key={row.id} className="overview-row" onClick={()=>onWork(row)}><ClipboardList size={17}/><strong>{row.values.title}</strong><small>{row.values.due||tr('No due date','دون موعد')}</small><ArrowUpRight size={16}/></button>):<p className="overview-empty">{tr('No open actions. Add one in your business sections.','لا توجد إجراءات مفتوحة. أضف إجراءً في أقسام مشروعك.')}</p>):(artifacts.length?artifacts.slice().reverse().map(item=><button key={item.id} className="overview-row" onClick={()=>onOpenArtifact(item)}><FileText size={17}/><strong>{item.title}</strong><small>{'v'+(item.version||1)+' · '+(hasMatchingReview(item)?tr('Reviewed','تمت المراجعة'):tr('Needs review','يحتاج إلى مراجعة'))}</small><ArrowUpRight size={16}/></button>):<p className="overview-empty">{tr('Documents you prepare with Dukkan appear here for review.','تظهر هنا المستندات التي تجهّزها مع دكان للمراجعة.')}</p>)}</section>}
 <div className="overview-grid"><section className="overview-next"><span>{tr('Next step','الخطوة التالية')}</span><h2>{nextTitle}</h2><p>{nextDescription}</p><button onClick={onStart}><Compass size={17}/>{nextTitle}<ChevronRight size={17}/></button></section>
 <section><h2><AlertCircle size={18}/>{tr('Needs attention','يحتاج إلى مراجعة')}</h2>{attention.length?attention.slice(0,4).map(({row,impact})=><button className="overview-row" key={row.id} onClick={()=>onWork(row)}><AlertCircle size={17}/><strong>{row.values.title}</strong><small>{impact.missing?tr('Review context','راجع المعطيات'):impact.changed.length?tr('Assumptions changed: ','تغيّرت المعطيات: ')+impact.changed.map(k=>impactLabels[k]).join(', '):tr('Overdue','متأخر')}</small><ArrowUpRight size={16}/></button>):<p className="overview-empty">{tr('Nothing needs attention.','لا توجد إجراءات تحتاج إلى مراجعة.')}</p>}</section>
 <section><h2><History size={18}/>{tr('Latest decision','آخر قرار')}</h2>{decision?<button className="overview-row" onClick={()=>decisionRecord?onWork(decisionRecord):onRecords()}><History size={17}/><strong>{decision.label}</strong><small>{decision.reason}</small><ArrowUpRight size={16}/></button>:<p className="overview-empty">{tr('Save a decision after reviewing the evidence.','احفظ قراراً بعد مراجعة الأدلة.')}</p>}</section>
 <section><h2>{tr('Quick actions','إجراءات سريعة')}</h2><div className="overview-shortcuts"><button onClick={onCosts} title={tr('Costs and scenarios','التكاليف والسيناريوهات')}><Calculator size={23}/><span>{tr('Costs','التكاليف')}</span></button><button onClick={onLicences} title={tr('Licence requirements and documents','متطلبات الترخيص والمستندات')}><FileText size={23}/><span>{tr('Licences','التراخيص')}</span></button><button onClick={()=>demo?onPdf():onDraft(officialDocumentPrompt)} title={tr('Prepare a document','جهّز مستنداً')}><FileText size={23}/><span>{tr('Prepare','تجهيز')}</span></button><button onClick={onRecords} title={tr('Saved work and decisions','العمل المحفوظ والقرارات')}><ClipboardList size={23}/><span>{tr('Saved work','العمل المحفوظ')}</span></button></div></section></div></div>
}
