import {useEffect,useRef,useState} from 'react'
import {z} from 'zod'
import {Button} from '@/components/ui/button'
import {EditorFrame} from '@/components/editors'
import {API,bundleSchema,preparationLabel,request,type PreparationBundle} from '@/lib/preparation-api'

const proposalSchema=z.object({expectedRevision:z.number().int().positive(),supersedesJobId:z.string().optional(),executionMode:z.enum(['live_agent','deterministic']).optional(),facts:z.array(z.object({field:z.string(),value:z.string(),origin:z.string(),sourceRef:z.string().nullable(),confirmedBy:z.string().nullable(),confirmedAt:z.string().nullable()})).min(1)})
export type FactAction={endpoint?:string;payload?:unknown;label:string}
export function FactReview({action,conversationId,caseId,onSaved,onClose}:{action:FactAction;conversationId:string;caseId?:string|null;onSaved:()=>Promise<void>;onClose:()=>void}){
 const parsed=proposalSchema.safeParse(action.payload)
 const [facts,setFacts]=useState(()=>parsed.success?parsed.data.facts:[]),[actor,setActor]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false)
 const op=useRef<{key:string;body:unknown}|null>(null),abort=useRef(new AbortController())
 useEffect(()=>{abort.current=new AbortController();return()=>abort.current.abort()},[])
 const allowed=action.endpoint==='/api/conversations/'+encodeURIComponent(conversationId)+'/facts'||!!caseId&&action.endpoint==='/api/cases/'+encodeURIComponent(caseId)+'/answers'
 async function confirm(){if(!parsed.success||!allowed||!actor.trim()||!ack||busy)return;setBusy(true);setError('');op.current??={key:crypto.randomUUID(),body:{...parsed.data,facts:facts.map(f=>({...f,origin:'founder',sourceRef:null,confirmedBy:actor.trim(),confirmedAt:new Date().toISOString()}))}};try{if(!saved){await request(action.endpoint!,z.record(z.string(),z.unknown()),abort.current.signal,op.current.body,op.current.key);setSaved(true)}await onSaved();if(!abort.current.signal.aborted)onClose()}catch(e){if(!abort.current.signal.aborted)setError((e as Error).message)}finally{if(!abort.current.signal.aborted)setBusy(false)}}
 return <EditorFrame title="Check these details" description="These are suggestions, not confirmed facts. Edit anything that is wrong." onClose={onClose}><div className="chat-file-review">{!parsed.success||!allowed?<p role="alert">These details could not be matched to this conversation. Nothing was changed.</p>:<><div className="chat-facts">{facts.map((f,i)=><label key={f.field}>{f.field.replaceAll('_',' ').replaceAll('.',' · ')}<input value={f.value} disabled={busy||!!op.current} onChange={e=>setFacts(old=>old.map((x,n)=>n===i?{...x,value:e.target.value}:x))}/></label>)}</div><label>Your name<input value={actor} onChange={e=>setActor(e.target.value)} disabled={busy||!!op.current}/></label><label className="chat-review-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={busy||!!op.current}/>I checked these details. Save them to this conversation’s case.</label><Button onClick={confirm} disabled={busy||!ack||!actor.trim()}>{busy?'Saving…':saved?'Refresh confirmed details':op.current?'Retry same confirmation':'Confirm details'}</Button><p className="chat-file-boundary">This updates this case only. It does not approve a licence or change your separate plan.</p></>}{error&&<p role="alert">{error}</p>}</div></EditorFrame>
}

const inspectedForms=z.object({documents:z.array(z.object({id:z.string(),name:z.string().optional(),formInspection:z.object({scope:z.string(),fields:z.array(z.object({name:z.string(),value:z.union([z.string(),z.array(z.string()),z.boolean(),z.null()]),populated:z.boolean(),supported:z.boolean()})),blank:z.array(z.string()),unsupported:z.array(z.string())}).nullable().optional()}))})
function DocumentFindings({result}:{result:unknown}){
 const parsed=inspectedForms.safeParse(result);if(!parsed.success)return null
 return <>{parsed.data.documents.filter(d=>d.formInspection?.fields.length).map(d=><section key={d.id} aria-label="PDF field findings"><h4>{d.name||'PDF form'}</h4><p>{d.formInspection!.scope}</p><dl>{d.formInspection!.fields.filter(f=>f.populated).map(f=><div key={f.name}><dt>{f.name}</dt><dd>{Array.isArray(f.value)?f.value.join(', '):String(f.value)}</dd></div>)}</dl><details><summary>Blank fields · {d.formInspection!.blank.length}</summary><ul>{d.formInspection!.blank.map(name=><li key={name}>{name}</li>)}</ul></details>{!!d.formInspection!.unsupported.length&&<p>Unsupported fields: {d.formInspection!.unsupported.join(', ')}</p>}</section>)}</>
}

export function PreparationProgress({jobId,onClose}:{jobId:string;onClose:()=>void}){
 const [data,setData]=useState<PreparationBundle|null>(null),[error,setError]=useState('')
 useEffect(()=>{const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;async function poll(){try{const result=await request('/api/jobs/'+encodeURIComponent(jobId),bundleSchema,abort.signal);if(abort.signal.aborted)return;setData(result);setError('');if(['queued','running','retry_wait'].includes(result.job.status))timer=setTimeout(poll,1500)}catch(e){if(!abort.signal.aborted)setError((e as Error).message)}}void poll();return()=>{abort.abort();clearTimeout(timer)}},[jobId])
 return <EditorFrame title="Preparation progress" description="Progress from the actual preparation job. No government submission." onClose={onClose}><div className="chat-file-review">{data?<><h3>{preparationLabel(data)}</h3><p>{data.job.step}</p>{data.job.questions.map((q,i)=><p key={i}>{String(q.question||q.label||q.message||q.field||'A detail needs checking')}</p>)}<DocumentFindings result={data.job.results?.inspect_documents}/><details><summary>Tool activity · {data.job.trace.length}</summary>{data.job.trace.map(t=><p key={t.callId}>{t.name} · {t.ok?'Completed':'Needs attention'}</p>)}</details>{data.pack&&<iframe title="Preparation draft" sandbox="" src={API+'/api/jobs/'+encodeURIComponent(jobId)+'/draft'}/>}<p className="chat-file-boundary">This is a preview. The existing preparation companion retains its review and export controls.</p></>:<p>Checking preparation…</p>}{error&&<p role="alert">{error}</p>}</div></EditorFrame>
}
