import {chatBlocks} from '@/lib/chat-blocks'
import {EmailWorkspace} from './email-workspace'
import {ArtifactPreview} from './artifact-preview'
import {ChatDocuments} from './chat-documents'
import {ConversationUpdate,ConversationDraft} from '@/components/conversation-cards'
import {conversationStages} from '@/lib/conversation-flow'
import type {WriteResult} from '@/lib/workspace-writer'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {z} from 'zod'
import {Send,ArrowDownToLine,Check,FileText,Loader2,MessageSquare,Plus,X,PanelRight,SquarePen,Search,ClipboardList,Globe,NotebookPen,Archive,ShieldAlert} from 'lucide-react'
import {DraftGroupList} from './work-sidebar'
import {Button} from '@/components/ui/button'
import {FactReview,PreparationProgress,type FactAction} from '@/components/chat-actions'
import {EditorFrame} from '@/components/editors'
import {FounderWorkbench,type Stage} from '@/components/founder-workbench'
import {safeLink} from '@/lib/preparation-api'
import type {Brief,Decision,Hypothesis,Workspace} from '@/lib/workspace'
import {modelSchema,modelLabel,sourceCaveats,mergeById,artifactPath,chatRequest,conversationList,conversationResponse,conversationSchema,turnResponse,turnSchema,chatMessageSchema,verifiedDownload,type ChatArtifact,type ChatMessage,type ChatTurn,type ChatMode,type Conversation,type RequestedAction} from '@/lib/chat-api'

function text(value:unknown){return typeof value==='string'?value:''}
const modelShortlist=['nex-agi/nex-n2.5-pro:free','qwen/qwen3.8-27b:free','google/gemma-4-31b-it:free','inclusionai/ling-3.0-flash-sante:free'] as const
function Bold({children}:{children:string}){return <>{children.split(/(\*\*[^*]+\*\*)/g).map((part,i)=>part.startsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part)}</>}
function Answer({content}:{content:string}){return <div className="chat-answer" dir="auto">{chatBlocks(content).map((block,i)=>{
 if(block.kind==='table')return <div className="chat-table-wrap" key={i} tabIndex={0}><table><thead><tr>{block.headers.map((cell,j)=><th key={j} scope="col"><Bold>{cell}</Bold></th>)}</tr></thead><tbody>{block.rows.map((row,r)=><tr key={r}>{row.map((cell,j)=><td key={j}><Bold>{cell}</Bold></td>)}</tr>)}</tbody></table></div>
 if(block.kind==='list'){const List=block.ordered?'ol':'ul';return <List key={i}>{block.items.map((item,j)=><li key={j}><Bold>{item}</Bold></li>)}</List>}
 if(block.kind==='code')return <pre key={i}><code>{block.text}</code></pre>
 if(block.kind==='heading')return <h3 key={i}><Bold>{block.text}</Bold></h3>
 return <p key={i}><Bold>{block.text}</Bold></p>
 })}</div>}

function Sources({items,language}:{items:Record<string,unknown>[];language:'en'|'ar'}){const tr=(en:string,ar:string)=>language==='ar'?ar:en;return items.length?<details className="chat-sources"><summary>{items.length} {language==='ar'?'مصادر':items.length===1?'source':'sources'}</summary><ol>{items.map((s,i)=>{const url=safeLink(s.url||s.sourceUrl||s.href);const title=text(s.title)||text(s.label)||text(s.sourceID)||text(s.sourceId)||tr('Source ','مصدر ')+(i+1);const limits=sourceCaveats(s.limitations);const rawDate=text(s.capturedAt||s.captureDate);const date=rawDate&&!Number.isNaN(Date.parse(rawDate))?new Date(rawDate).toLocaleDateString(language==='ar'?'ar-KW':'en-GB',{day:'numeric',month:'short',year:'numeric'}):'';return <li key={i}>{url?<a href={url} target="_blank" rel="noopener noreferrer">{title}</a>:<strong>{title}</strong>}{text(s.authority)&&<small>{text(s.authority)}{date?tr(' · Captured ',' · جُمِع في ')+date:''}</small>}{text(s.dataPeriod)&&<small>{tr('Data period: ','الفترة التي تغطيها البيانات: ')}{text(s.dataPeriod)}</small>}{typeof s.page==='number'&&<small>{tr('PDF page: ','صفحة PDF: ')}{s.page}</small>}{limits.map((limit,j)=><p className="chat-source-limit" key={j}>{limit}</p>)}{text(s.excerpt||s.passage||s.quote)&&<details className="chat-source-excerpt"><summary>{tr('Read source extract','اقرأ مقتطف المصدر')}</summary><p>{text(s.excerpt||s.passage||s.quote)}</p></details>}<details className="chat-source-reference"><summary>{tr('Source details','تفاصيل المصدر')}</summary>{text(s.sourceID||s.sourceId)&&<small>{tr('Reference: ','المرجع: ')}{text(s.sourceID||s.sourceId)}</small>}{text(s.localCitation)&&<small>{tr('Recorded location: ','الموقع المسجل: ')}{text(s.localCitation)}</small>}{rawDate&&<small>{tr('Exact capture time: ','وقت الجمع: ')}{rawDate}</small>}{text(s.status)&&<small>{tr('Source classification: ','تصنيف المصدر: ')}{s.status==='not_legislation'?tr('guidance, not legislation','إرشادات وليست تشريعاً'):text(s.status).replaceAll('_',' ')}</small>}{Array.isArray(s.limitations)&&<small>{tr('Recorded flags: ','التنبيهات المسجلة: ')}{s.limitations.filter(x=>typeof x==='string').join('; ')}</small>}</details></li>})}</ol></details>:null}
function FileReview({artifact,onClose,onRevision}:{artifact:ChatArtifact;onClose:()=>void;onRevision:(t:ChatTurn,m:ChatMessage)=>void}){
 const [actor,setActor]=useState(''),[checked,setChecked]=useState(false),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [edits,setEdits]=useState<Record<string,string>>({}),[editing,setEditing]=useState(false)
 const abort=useRef(new AbortController()),editKey=useRef(crypto.randomUUID()),reviewKey=useRef(crypto.randomUUID()),lockedActor=useRef<string|null>(null)
 useEffect(()=>{abort.current=new AbortController();return()=>abort.current.abort()},[artifact])
 async function review(){if(!checked||!actor.trim()||busy)return;setBusy(true);setError('');lockedActor.current??=actor.trim();try{await chatRequest(artifactPath(artifact.reviewUrl,artifact.id,'review'),z.record(z.string(),z.unknown()),abort.current.signal,{hash:artifact.hash,actor:lockedActor.current,acknowledgeDraft:true},reviewKey.current);setReviewed(true)}catch(e){if(!abort.current.signal.aborted)setError((e as Error).message==='Failed to fetch'?'The service is unavailable. Your saved plan has not changed.':(e as Error).message)}finally{if(!abort.current.signal.aborted)setBusy(false)}}
 async function revise(){setBusy(true);setError('');try{const result=await chatRequest('/api/chat/artifacts/'+encodeURIComponent(artifact.id)+'/revise',z.object({turn:turnSchema,message:chatMessageSchema}),abort.current.signal,{hash:artifact.hash,fields:Object.fromEntries(Object.entries(edits).map(([k,v])=>[k,v.trim()?v:null]))},editKey.current);onRevision(result.turn,result.message);onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function exportFile(){setBusy(true);setError('');try{const blob=await verifiedDownload(artifact,abort.current.signal);if(abort.current.signal.aborted)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dikan-'+artifact.kind.replace(/[^a-z0-9-]/gi,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){if(!abort.current.signal.aborted)setError((e as Error).message==='Failed to fetch'?'The service is unavailable. Your saved plan has not changed.':(e as Error).message)}finally{if(!abort.current.signal.aborted)setBusy(false)}}
 return <EditorFrame title={artifact.title} description="Draft for your review. Nothing is sent or submitted." onClose={onClose}><div className="chat-file-review"><ArtifactPreview artifact={artifact} title={artifact.title}/>{artifact.kind==='stage_draft'&&<p className="chat-file-boundary">To change this AI draft, close it and request a fresh stage review. Your saved business details remain editable in the workspace.</p>}{artifact.kind==='application_worksheet'&&artifact.fields&&<><Button variant="outline" onClick={()=>setEditing(!editing)}>Edit fields as a new version</Button>{editing&&<div>{Object.entries(artifact.fields).map(([field,value])=><label key={field}>{field.replaceAll('_',' ')}<input dir="auto" value={edits[field]??value??''} disabled={busy} onChange={e=>{editKey.current=crypto.randomUUID();setEdits({...edits,[field]:e.target.value})}}/></label>)}<Button disabled={busy||!Object.keys(edits).length} onClick={revise}>Save new version</Button></div>}</>}<p className="chat-file-boundary">Check the details and any gaps before keeping this version.</p>{!reviewed?<><label>Your name<input value={actor} disabled={busy||lockedActor.current!==null} onChange={e=>setActor(e.target.value)} autoComplete="name"/></label><label className="chat-review-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={busy}/>I reviewed this draft and understand it may have open questions.</label><Button disabled={!checked||!actor.trim()||busy} onClick={review}>{busy?<Loader2 size={16}/> :<Check size={16}/>}Mark as reviewed</Button></>:<Button disabled={busy} onClick={exportFile}><ArrowDownToLine size={16}/>{busy?'Checking file…':'Download reviewed file'}</Button>}{error&&<p role="alert">{error}</p>}</div></EditorFrame>
}

export function ChatWorkspace({onOpenArtifact,scope,taskHost,onActivate,workspaceContext,language,demo,workspaceArtifacts=[],requested=null,onArtifactsChange=()=>{},onComposerChange=()=>{},onRequestBlocked=()=>{},onSaveBrief,onSaveCosts,onSaveTest,onSaveResult=()=>{},onRecordDecision=()=>{},onAdoptTest=()=>{},onSaveIdeaReview=()=>{},onOpenEvidence,onOpenSetup,onOpenBusiness,onApplyProposal=async()=>({ok:false,reason:"Open this idea in the current Dukkan workspace to save."})}:{onOpenArtifact?:(artifact:ChatArtifact)=>void;onApplyProposal?:(payload:unknown)=>Promise<WriteResult>;workspaceContext:Workspace;scope:string;taskHost:HTMLElement|null;onActivate:()=>void;language:'en'|'ar';demo:boolean;workspaceArtifacts?:ChatArtifact[];requested?:{nonce:number;conversationId?:string;artifactId?:string;prompt?:string;stage?:Stage;requestedAction?:RequestedAction;newChat?:boolean}|null;onArtifactsChange?:()=>void;onComposerChange?:(unsent:boolean)=>void;onRequestBlocked?:(message:string)=>void;onSaveBrief:(brief:Brief)=>void;onSaveCosts:(costs:Workspace['costs'])=>void;onSaveTest:(test:Hypothesis)=>void;onSaveResult?:(hypothesis:Hypothesis)=>void;onRecordDecision?:(hypothesis:Hypothesis,outcome:Decision['outcome'],reason:string)=>void;onAdoptTest?:(artifact:ChatArtifact,proposal:NonNullable<ChatArtifact['proposedTest']>)=>void;onSaveIdeaReview?:(artifact:ChatArtifact,choice:'test'|'revise'|'park',reason:string,selectedOption:string,customOption?:{title:string;kind:'feature'|'expansion'|'pivot';tradeoff:string})=>void;onOpenEvidence:()=>void;onOpenSetup:()=>void;onOpenBusiness?:(stage:Stage)=>void}){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en
 const stageLabels:Record<string,string>={idea:'مراجعة الفكرة',validate:'اختبار الطلب',plan:'تخطيط التكاليف',apply:'تجهيز الترخيص'}
 const [conversations,setConversations]=useState<Conversation[]>([]),[conversation,setConversation]=useState<Conversation|null>(null)
 const [messages,setMessages]=useState<ChatMessage[]>([]),[turns,setTurns]=useState<ChatTurn[]>([]),[artifacts,setArtifacts]=useState<ChatArtifact[]>([])
 const [input,setInput]=useState(''),[mode,setMode]=useState<ChatMode>('live_agent'),[live,setLive]=useState(false),[configuredModelId,setConfiguredModelId]=useState(''),[modelId,setModelId]=useState(''),[catalogue,setCatalogue]=useState<Array<{id:string;freeVerified:boolean}>>([]),[catalogueNote,setCatalogueNote]=useState('checking'),[subscription,setSubscription]=useState(false),[apiCapped,setApiCapped]=useState(false)
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[files,setFiles]=useState(false),[opened,setOpened]=useState<ChatArtifact|null>(null),[factAction,setFactAction]=useState<FactAction|null>(null),[jobId,setJobId]=useState('')
 const [workStage,setWorkStage]=useState<Stage>('idea')
 const [paneTab,setPaneTab]=useState<'agent'|'journey'|'browser'>('agent')
 const [emailDirty,setEmailDirty]=useState(false)
 const [proposalEdits,setProposalEdits]=useState<Record<string,boolean>>({});const proposalDirty=Object.values(proposalEdits).some(Boolean)
 const [showAllTasks,setShowAllTasks]=useState(false)
 const [archiving,setArchiving]=useState(false),[stopping,setStopping]=useState(false)
 const [showArchived,setShowArchived]=useState(false)
 const controller=useRef(new AbortController()),generation=useRef(0),inflight=useRef(false),inputRef=useRef<HTMLTextAreaElement>(null)
 const pending=useRef<{createKey:string;messageKey:string;content:string;mode:ChatMode;modelId:string;workspaceContext:unknown;conversationId?:string;requestedAction?:RequestedAction}|null>(null)
 const nearBottom=useRef(true),modeChosen=useRef(false),bottom=useRef<HTMLDivElement>(null),storageKey='dikan-chat-session:'+scope
 const seenArtifacts=useRef(new Set<string>())
 const handledRequest=useRef<number|null>(null)
 const active=turns.find(t=>t.status==='queued'||t.status==='running')
 const promptBlocked=busy||loading||!!active||!!pending.current||!!input.trim()
 const [historyOpen,setHistoryOpen]=useState(false)
 function offerPrompt(prompt:string,requestedAction?:RequestedAction){if(promptBlocked)return;setPaneTab('journey');setFiles(false);void send(false,prompt,requestedAction)}
 function apply(data:{messages:ChatMessage[];artifacts:ChatArtifact[];turns?:ChatTurn[];turn?:ChatTurn}){if(data.turns){setMessages(data.messages);setArtifacts(data.artifacts)}else{setMessages(old=>mergeById(old,data.messages));setArtifacts(old=>mergeById(old,data.artifacts))}if(data.turns)setTurns(data.turns);if(data.turn)setTurns(old=>[...old.filter(t=>t.id!==data.turn!.id),data.turn!]);if(data.artifacts.some(item=>!seenArtifacts.current.has(item.id))){const incoming=data.artifacts.filter(item=>!seenArtifacts.current.has(item.id));data.artifacts.forEach(item=>seenArtifacts.current.add(item.id));onArtifactsChange();if(!data.turns){const pdf=incoming.filter(item=>item.kind==='official_pdf').at(-1);if(pdf)onOpenArtifact?.(pdf)}}}
 function remember(id:string){try{sessionStorage.setItem(storageKey,id)}catch{}const url=new URL(location.href);url.searchParams.delete('fresh');url.searchParams.set('conversation',id);history.replaceState(null,'',url)}
 async function load(id:string,signal:AbortSignal){const result=await chatRequest('/api/conversations/'+encodeURIComponent(id),conversationResponse,signal);if(signal.aborted)return;setConversation(result.conversation);apply(result);remember(id);return result}
 async function refreshList(signal:AbortSignal){const data=await chatRequest('/api/conversations?workspaceId='+encodeURIComponent(scope),conversationList,signal);if(!signal.aborted)setConversations(data.conversations)}
 async function refreshHealth(signal:AbortSignal){return chatRequest('/api/health',z.object({chat:z.object({executionModes:z.array(z.string()),model:modelSchema.nullable()})}),signal).then(h=>{if(!signal.aborted){const enabled=h.chat.executionModes.includes('live_agent')&&!!h.chat.model;setLive(enabled);setConfiguredModelId(h.chat.model?.version||'');setModelId(current=>current||h.chat.model?.version||'');if(!modeChosen.current)setMode('live_agent')}}).catch(()=>{})}
 const selectedModelUnavailable=!subscription&&['checked','none'].includes(catalogueNote)&&!!modelId&&!catalogue.some(item=>item.id===modelId&&item.freeVerified)
 async function refreshCatalogue(signal:AbortSignal){try{const result=await chatRequest('/api/chat/models',z.object({models:z.array(z.object({id:z.string(),freeVerified:z.boolean()})),checkedAt:z.string(),billing:z.string().optional()}),signal);if(signal.aborted)return;setSubscription(result.billing==='subscription');setApiCapped(result.billing==='api-capped');setCatalogue(result.models);const free=result.models.filter(m=>m.freeVerified).length;setCatalogueNote(free?'checked':'none')}catch{if(!signal.aborted)setCatalogueNote('unavailable')}}
 useEffect(()=>{controller.current=new AbortController();const signal=controller.current.signal;setLoading(true)
  void (async()=>{try{const list=await chatRequest('/api/conversations?workspaceId='+encodeURIComponent(scope),conversationList,signal);if(signal.aborted)return;setConversations(list.conversations);let id=new URLSearchParams(location.search).get('conversation')||'';try{if(!new URLSearchParams(location.search).has('fresh'))id ||= sessionStorage.getItem(storageKey)|| (scope==='legacy'?sessionStorage.getItem('dikan-chat-session:personal')||'':'')}catch{}if(id&&list.conversations.some(item=>item.id===id))await load(id,signal);else if(id){const url=new URL(location.href);url.searchParams.delete('conversation');history.replaceState(null,'',url)}}catch(e){if(!signal.aborted)setError((e as Error).message==='Failed to fetch'?'The service is unavailable. Your saved plan has not changed.':(e as Error).message)}finally{if(!signal.aborted)setLoading(false)}})()
  void refreshHealth(signal);void refreshCatalogue(signal)
  return()=>{controller.current.abort();generation.current++}
 },[storageKey])
 useEffect(()=>{if(!active)return;const signal=controller.current.signal;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const data=await chatRequest('/api/chat/turns/'+encodeURIComponent(active!.id),turnResponse,signal);if(stopped||signal.aborted)return;apply(data);setError('');if(data.turn.status==='queued'||data.turn.status==='running')timer=setTimeout(poll,1400)}catch(e){if(!stopped&&!signal.aborted){setError('Could not check progress. Your request may still be running. '+(e as Error).message);timer=setTimeout(poll,5000)}}}void poll();return()=>{stopped=true;clearTimeout(timer)}},[active?.id])
 useEffect(()=>{if(messages.length&&nearBottom.current)bottom.current?.scrollIntoView({block:'nearest',behavior:'instant'})},[messages.length,active?.events.length])
 useEffect(()=>onComposerChange(!!input.trim()||emailDirty||proposalDirty),[input,emailDirty,proposalDirty,onComposerChange])
 function resetConversationView(){controller.current.abort();controller.current=new AbortController();generation.current++;pending.current=null;setError('');setOpened(null);setFactAction(null);setJobId('');setInput('');setTurns([]);setMessages([]);setArtifacts([]);setConversation(null);const url=new URL(location.href);url.searchParams.delete('conversation');history.replaceState(null,'',url);try{sessionStorage.removeItem(storageKey)}catch{}}
 useEffect(()=>{if(!requested||loading||handledRequest.current===requested.nonce)return;handledRequest.current=requested.nonce;if(requested.stage){setPaneTab('journey');setWorkStage(requested.stage);setFiles(!requested.prompt)}
  if(requested.conversationId){void choose(requested.conversationId,requested.artifactId);return}
  if(requested.newChat){
   if(busy||active||pending.current||input.trim()||emailDirty||proposalDirty){onRequestBlocked(language==='ar'?'لديك طلب لم يكتمل. راجعه قبل إرسال طلب آخر.':'Finish or clear the current message before starting another request.');return}
   onActivate();nearBottom.current=true;resetConversationView();void refreshHealth(controller.current.signal);void refreshList(controller.current.signal).catch(()=>{})
   if(requested.prompt)void send(false,requested.prompt,requested.requestedAction,true);else{setLoading(false);inputRef.current?.focus()}
   return
  }
  if(requested.prompt){if(input.trim()||busy||active||pending.current){onRequestBlocked(language==='ar'?'لديك طلب لم يكتمل. راجعه قبل إرسال طلب آخر.':'Finish or clear the current message before starting another request.');return}void send(false,requested.prompt,requested.requestedAction)}
 },[requested?.nonce,loading])
 async function choose(id:string,artifactId?:string){if(busy||active||pending.current)return;if(input.trim()||emailDirty||proposalDirty){setError(language==='ar'?'لديك رسالة لم تُرسل. أرسلها أو امسحها قبل فتح محادثة أخرى.':'Save or discard your email edits and send or clear the message before opening another chat.');return}onActivate();nearBottom.current=true;if(!id){resetConversationView();void refreshHealth(controller.current.signal);void refreshList(controller.current.signal).catch(()=>{});setLoading(false);inputRef.current?.focus();return}controller.current.abort();controller.current=new AbortController();generation.current++;pending.current=null;setError('');setOpened(null);setFactAction(null);setJobId('');setInput('');setTurns([]);setMessages([]);setArtifacts([]);setConversation(null);void refreshHealth(controller.current.signal);void refreshList(controller.current.signal).catch(()=>{});setLoading(true);const signal=controller.current.signal;try{const result=await load(id,signal);if(artifactId){const item=result?.artifacts.find(file=>file.id===artifactId);if(item)(onOpenArtifact?onOpenArtifact(item):setOpened(item));else setError('This saved version could not be opened. Your other work is unchanged.')}}catch(e){if(!signal.aborted)setError((e as Error).message==='Failed to fetch'?'The service is unavailable. Your saved plan has not changed.':(e as Error).message)}finally{if(!signal.aborted)setLoading(false)}}
 async function send(retry=false,explicit?:string,requestedAction?:RequestedAction,forceNew=false){if(inflight.current||active||loading||(!retry&&!(explicit||input).trim()))return;nearBottom.current=true;inflight.current=true;setBusy(true);setError('');const epoch=generation.current,signal=controller.current.signal
  if(!retry)pending.current={createKey:crypto.randomUUID(),messageKey:crypto.randomUUID(),content:(explicit||input).trim(),mode,modelId,workspaceContext:structuredClone(workspaceContext),conversationId:forceNew?undefined:conversation?.id,requestedAction}
  const op=pending.current;if(!op){inflight.current=false;setBusy(false);return}
  try{if(!op.conversationId){const result=await chatRequest('/api/conversations',z.object({conversation:conversationSchema}),signal,{title:op.content.slice(0,70),workspaceId:scope},op.createKey);if(epoch!==generation.current)return;op.conversationId=result.conversation.id;setConversation(result.conversation);remember(result.conversation.id)}
   const result=await chatRequest('/api/conversations/'+encodeURIComponent(op.conversationId)+'/messages',z.object({turn:turnSchema,message:chatMessageSchema}),signal,{content:op.content,executionMode:op.mode,modelId:op.modelId||undefined,workspaceContext:op.workspaceContext,requestedAction:op.requestedAction},op.messageKey)
   if(epoch!==generation.current)return;setMessages(old=>old.some(m=>m.id===result.message.id)?old:[...old,result.message]);setTurns(old=>[...old.filter(t=>t.id!==result.turn.id),result.turn]);setInput('');pending.current=null;void refreshList(signal).catch(()=>{})
  }catch(e){if(!signal.aborted)setError((e as Error).message==='Failed to fetch'?'The service is unavailable. Your saved plan has not changed.':(e as Error).message)}finally{if(epoch===generation.current){inflight.current=false;setBusy(false)}}
 }
 async function stopTurn(){if(!active||stopping)return;setStopping(true);try{await chatRequest('/api/chat/turns/'+active.id+'/stop',z.object({turn:turnSchema}),controller.current.signal,{workspaceId:scope},crypto.randomUUID());if(conversation)await load(conversation.id,controller.current.signal)}catch(e){setError((e as Error).message)}finally{setStopping(false)}}
 const activity=(t:ChatTurn)=><details className="chat-activity" key={t.id} open={t.id===active?.id?true:undefined}><summary>{t.id===active?.id?<Loader2 size={14} className="chat-spin"/>:t.status==='failed'?<X size={14}/>:<Check size={14}/>} {t.id===active?.id?tr('Working','جارٍ العمل'):t.status==='failed'?tr('Work stopped','توقف العمل'):tr('Activity','النشاط')} · {t.executionMode==='live_agent'?modelLabel(t.model):t.label==='Human field edit · no model inference'?tr('Your field edit','تعديلك للحقول'):tr('Scripted demo','عرض توضيحي مبرمج')}</summary><ol>{t.events.map(e=><li key={e.id}><span className={'activity-dot '+e.type}/><span><strong>{e.label||e.name}</strong><small>{e.name} · {e.type.replaceAll('_',' ')}</small></span></li>)}</ol></details>;
 const earlier=artifacts.filter(a=>artifacts.some(next=>next.supersedesArtifactId===a.id)),latest=artifacts.filter(a=>!earlier.some(old=>old.id===a.id))
 const journeyArtifacts=[...new Map([...workspaceArtifacts,...artifacts].map(item=>[item.id,item])).values()].sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||''))||a.id.localeCompare(b.id))
 const fileButton=(a:ChatArtifact)=>{const worksheet=a.kind==='application_worksheet',filled=a.fields?Object.values(a.fields).filter(v=>typeof v==='string'&&v.trim()).length:0;return <div className="agent-artifact-wrap" key={a.id}><button className="chat-artifact" onClick={()=>onOpenArtifact?onOpenArtifact(a):setOpened(a)}><FileText size={20}/><span><strong>{worksheet?tr('Business setup worksheet','ورقة تجهيز تأسيس المشروع'):a.title}</strong><small>{worksheet?tr('Preparation only','للتجهيز فقط'):tr('Draft','مسودة')}{a.version?tr(' · Version ',' · النسخة ')+a.version:''}{earlier.some(old=>old.id===a.id)?tr(' · Earlier version',' · نسخة سابقة'):tr(' · Open and review',' · افتح وراجع')}</small>{worksheet&&a.fields&&<span className="agent-filled-details">{filled} {tr('details filled','تفاصيل مدخلة')}{a.missingFields?.length?' · '+a.missingFields.length+tr(' still needed',' تفاصيل ما زالت مطلوبة'):''}</span>}</span></button>{!earlier.some(old=>old.id===a.id)&&<ConversationDraft language={language} artifact={a} workspace={workspaceContext} onChoose={(choice,reason,option)=>onSaveIdeaReview(a,choice,reason,option)} onAdopt={()=>onAdoptTest(a,a.proposedTest!)} onDiscuss={prompt=>offerPrompt(prompt)}/>}{worksheet&&a.questions?.[0]&&!earlier.some(old=>old.id===a.id)&&<p className="agent-next-question"><strong>{tr('Next detail','التفصيل التالي')}</strong>{a.questions[0].message}</p>}</div>}


 const empty=!messages.length&&!loading
 const starters:{label:string;icon:typeof Search;prompt:string;action?:RequestedAction}[]=[{label:tr('Research a business','بحث فكرة مشروع'),icon:Search,prompt:'Help me research a business idea in Kuwait. Ask what you need to know first.'},{label:tr('Check setup requirements','مراجعة متطلبات التأسيس'),icon:FileText,prompt:'Help me understand the setup questions for my business in Kuwait. Ask about my activity first.'},{label:tr('Prepare a draft','إعداد مسودة'),icon:FileText,prompt:'Help me prepare an enquiry draft. Ask what it needs to cover before drafting.'},{label:tr('Critique my idea','انقد فكرتي'),icon:ShieldAlert,prompt:'Give me a candid critique of my saved business idea. Include an evidence-readiness score, the critical risks, two options I could take and one small validation test I can run this week. Save it as an idea-stage draft. Do not soften the verdict.',action:{type:'stage_draft',stage:'idea'}}]
 async function archiveTask(task:Conversation,archived:boolean){
  if(busy||active||pending.current||archiving)return
  if(input.trim()){setError('Send or clear your unsent message before archiving a chat.');return}
  setArchiving(true);setError('')
  try{const result=await chatRequest('/api/conversations/'+encodeURIComponent(task.id)+'/archive',z.object({conversation:conversationSchema}),controller.current.signal,{archived,workspaceId:scope},crypto.randomUUID())
   setConversations(rows=>rows.map(row=>row.id===task.id?result.conversation:row))
   if(archived&&conversation?.id===task.id)await choose('')
  }catch(e){setError((e as Error).message)}finally{setArchiving(false)}
 }
 const activeTasks=conversations.filter(task=>!task.archived)
 const archivedTasks=conversations.filter(task=>task.archived)
 const lastUsedAt=activeTasks.map(task=>Date.parse(task.updatedAt)).filter(value=>!Number.isNaN(value)).sort((a,b)=>b-a)[0]
 const lastUsed=lastUsedAt?new Intl.DateTimeFormat(language==='ar'?'ar-KW':'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(lastUsedAt):''
 const visibleTasks=activeTasks.slice().reverse().filter((task,index)=>showAllTasks||index<3||task.id===conversation?.id)
 const taskNavigation=<div className="agent-tasks"><button className="agent-new-task" disabled={busy||archiving} onClick={()=>void choose('')}><SquarePen size={17}/><span>{language==='ar'?'محادثة جديدة':'New chat'}</span><Plus size={14}/></button><div className="agent-section-label">{language==='ar'?'المحادثات الأخيرة':'Recent chats'} <span>{activeTasks.length||''}</span></div><nav aria-label={tr("Business tasks","محادثات المشروع")}>{activeTasks.length?visibleTasks.map(task=><div key={task.id} className="dukkan-chat-row"><button title={task.title} className={conversation?.id===task.id?'selected':''} aria-current={conversation?.id===task.id?'page':undefined} disabled={busy||archiving} onClick={()=>void choose(task.id)}><MessageSquare size={14}/><span>{task.title}</span>{conversation?.id===task.id&&active&&<Loader2 size={12} className="chat-spin"/>}</button><button title={tr("Archive chat","أرشفة المحادثة")} aria-label={`${tr("Archive","أرشفة")} ${task.title}`} disabled={busy||!!active||archiving||demo} onClick={()=>void archiveTask(task,true)}><Archive size={14}/></button></div>):<p className="agent-no-tasks">{language==='ar'?'ستظهر محادثاتك هنا.':'Your chats will appear here.'}</p>}{activeTasks.length>3&&<button className="agent-show-tasks" onClick={()=>setShowAllTasks(!showAllTasks)}>{showAllTasks?tr('Show less','عرض أقل'):`${tr('View all chats','عرض كل المحادثات')} (${activeTasks.length})`}</button>}{archivedTasks.length>0&&<><button onClick={()=>setShowArchived(!showArchived)} aria-expanded={showArchived}>{tr('Archived chats','المحادثات المؤرشفة')} ({archivedTasks.length})</button>{showArchived&&<><p className="agent-no-tasks">{tr('Saved drafts remain in Saved work.','تبقى المسودات المحفوظة في سجل العمل.')}</p>{archivedTasks.map(task=><div className="dukkan-chat-row" key={task.id}><span>{task.title}</span><button disabled={busy||!!active||archiving||demo} onClick={()=>void archiveTask(task,false)}>{tr('Restore','استعادة')}</button></div>)}</>}</>}</nav></div>

 return <section className={`chat-workspace agent-workspace ${empty?'is-new-task':''}`} aria-label={tr("Dukkan conversation","محادثة دكان")} lang={language} dir={language==='ar'?'rtl':'ltr'}>
 {taskHost&&createPortal(taskNavigation,taskHost)}
 {!taskHost&&<details className="chat-history-menu" open={historyOpen} onToggle={e=>setHistoryOpen(e.currentTarget.open)}><summary>{tr('Chats','المحادثات')} ({activeTasks.length}){lastUsed?<span className="chat-history-last">{' · '}{tr('last used ','آخر استخدام ')}{lastUsed}</span>:null}</summary>{taskNavigation}</details>}
 <header className="agent-task-header"><div className="agent-task-name"><span className="agent-task-label">{language==='ar'?'مهمة':'Task'}</span><h1>{conversation?.title||(language==='ar'?'مهمة جديدة':'New task')}</h1></div>{!taskHost&&!historyOpen&&<button type="button" className="agent-header-new-chat" aria-label={language==='ar'?'محادثة جديدة':'New chat'} title={language==='ar'?'محادثة جديدة':'New chat'} disabled={busy||archiving} onClick={()=>void choose('')}><SquarePen size={14}/><span>{language==='ar'?'محادثة جديدة':'New chat'}</span></button>}<div className="agent-mobile-task-picker" hidden={!taskHost}><select aria-label={tr("Conversation","المحادثة")} value={conversation?.id||''} disabled={busy||loading} onChange={e=>void choose(e.target.value)}><option value="">{language==='ar'?'مهمة جديدة':'New task'}</option>{activeTasks.map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void choose('')}><Plus size={16}/>{language==='ar'?'جديد':'New'}</Button></div><div className="agent-task-controls"><span className="agent-run-state">{active?<><Loader2 size={13} className="chat-spin"/>{language==='ar'?'جارٍ العمل':tr('Working','جارٍ العمل')}</>:conversation?language==='ar'?'محفوظ':'Saved':language==='ar'?'مساحة خاصة':'Private workspace'}</span>{!onOpenArtifact&&<Button variant="ghost" size="sm" aria-label={onOpenArtifact?(language==='ar'?'افتح العمل الجاري':'Open active work'):(language==='ar'?'إظهار مساحة العمل':'Toggle work pane')} aria-expanded={onOpenArtifact?undefined:files} onClick={()=>onOpenArtifact?onOpenBusiness?.(workStage):setFiles(!files)}><PanelRight size={16}/><span>{language==='ar'?'العمل':'Active work'}</span></Button>}</div></header>
 <div className={`agent-stage ${files&&!onOpenArtifact?'has-outputs':''}`}><div className="agent-conversation">
 <div className="chat-stream" onScroll={e=>{const el=e.currentTarget;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<120}}>
 {empty&&<div className="agent-welcome"><span className="dukkan-welcome-door" aria-hidden="true"/><h2>{language==='ar'?'بماذا نبدأ؟':'What are we working on?'}</h2><p>{language==='ar'?'اشرح فكرتك، وسنختبرها ونحسب تكلفتها ونجهّز التأسيس معاً.':'Tell me your idea and I’ll help you test it, cost it and prepare setup.'}</p></div>}
 {loading&&<p className="chat-loading" role="status">{tr('Opening your task…','جارٍ فتح المحادثة…')}</p>}
 {messages.map(m=>{const turn=turns.find(t=>t.id===m.turnId);return <article key={m.id} className={'chat-message '+m.role}><div className="chat-speaker">{m.role==='user'?tr('You','أنت'):tr('Dukkan','دكان')}{m.role==='assistant'&&<span>{turn?.status==='failed'?tr('Could not finish','تعذّر إكمال الطلب'):turn?.model?.name==='synthetic-fixture'?tr('Synthetic test · no live AI','اختبار اصطناعي · دون ذكاء اصطناعي مباشر'):turn?.executionMode==='live_agent'?modelLabel(turn.model):turn?.label==='Human field edit · no model inference'?tr('Your field edit','تعديلك للحقول'):tr('Scripted demo','عرض توضيحي مبرمج')}</span>}</div>{m.role==='assistant'&&artifacts.some(a=>a.turnId===m.turnId)?<><details className="chat-response-details"><summary>{tr('Read Dukkan’s response','اقرأ رد دكان')}</summary><Answer content={m.content}/></details></>:<UserMessageContent content={m.content} language={language}/>}<Sources items={m.citations} language={language}/>{m.role==='assistant'&&turn&&turn.events.length>0&&activity(turn)}{m.actions.map((a,i)=>a.type==='workspace_update'?<ConversationUpdate language={language} onDirty={dirty=>setProposalEdits(prev=>({...prev,[m.id+'-'+i]:dirty}))} key={m.id+'-'+i} payload={a.payload} workspace={workspaceContext} onSave={onApplyProposal} onDiscuss={prompt=>offerPrompt(prompt)}/>:a.type==='open_preparation'&&a.jobId?<Button key={i} variant="outline" onClick={()=>setJobId(a.jobId!)}>{a.label}</Button>:a.type==='confirm_facts'?<Button key={i} variant="outline" onClick={()=>setFactAction(a)}>{a.label}</Button>:a.type==='review_artifact'?null:<p className="chat-followup" key={i}><strong>{a.label}</strong><br/>{tr('Review the proposed details, then reply below. Your business record is not changed automatically.','راجع التفاصيل المقترحة ثم أجب أدناه. لا يتغير سجل مشروعك تلقائياً.')}</p>)}{m.role==='assistant'&&artifacts.filter(a=>a.turnId===m.turnId).map(fileButton)}</article>})}
 {turns.filter(t=>t.events.length&&!messages.some(m=>m.role==='assistant'&&m.turnId===t.id)).map(activity)}
 {conversation&&<EmailWorkspace language={language} key={conversation.id} onDirty={setEmailDirty} conversationId={conversation.id} refresh={turns.map(t=>t.id+':'+t.status).join('|')}/>}
 {active&&!active.events.length&&<p className="chat-loading" role="status"><Loader2 size={15} className="chat-spin"/>{active.status==='queued'?tr('Your request is queued.','طلبك في قائمة الانتظار.'):tr('Dukkan is working on your request.','دكان يعمل على طلبك.')}</p>}
 {artifacts.filter(a=>!messages.some(m=>m.role==='assistant'&&m.turnId===a.turnId)).map(fileButton)}

 <div ref={bottom}/></div>
 <div className="chat-compose-wrap">
  {error&&<div className="chat-error" role="alert"><span>{error}</span>{pending.current&&!active&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void send(true)}>{tr('Retry same request','إعادة محاولة الطلب نفسه')}</Button>}{!pending.current&&<Button size="sm" variant="ghost" onClick={()=>void choose(conversation?.id||'')}>{tr('Reconnect','إعادة الاتصال')}</Button>}</div>}
  <form className="chat-composer" onSubmit={e=>{e.preventDefault();void send()}}>
   <label className="sr-only" htmlFor="chat-message">{tr('Message Dukkan','راسل دكان')}</label>
   <textarea ref={inputRef} id="chat-message" dir="auto" rows={2} maxLength={12000} placeholder={tr("Ask Dukkan or describe a change…","اسأل دكان أو اشرح التعديل المطلوب…")} value={input} disabled={busy||!!pending.current} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/>
   <div className="chat-compose-actions"><ChatDocuments language={language} caseId={conversation?.caseId||''} disabled={busy||!!active||!!pending.current||loading} onAsk={prompt=>offerPrompt(prompt)}/><details className="composer-settings"><summary aria-label={tr('Model settings','إعدادات النموذج')}>{selectedModelUnavailable?tr('Choose a model','اختر نموذجاً'):tr('Model','النموذج')}</summary><div><label><span className="sr-only">{tr('AI model','نموذج الذكاء الاصطناعي')}</span><select aria-label={tr("AI model","نموذج الذكاء الاصطناعي")} value={modelId} disabled={busy||!!active||!!pending.current||!live} onChange={e=>setModelId(e.target.value)}>
    {configuredModelId&&<option value={configuredModelId}>{(subscription||catalogue.some(item=>item.id===configuredModelId&&item.freeVerified))?tr('Configured','المحدد'):tr('Not verified available','غير متحقق من توفره')} · {configuredModelId}</option>}
    {Array.from(new Set([...modelShortlist,...catalogue.filter(item=>item.freeVerified).map(item=>item.id)])).filter(id=>id!==configuredModelId&&catalogue.some(item=>item.id===id&&item.freeVerified)).map(id=><option key={id} value={id}>{id} · {apiCapped?tr('within price caps','ضمن حدود السعر'):tr('verified free','تم التحقق من مجانيته')}</option>)}
   </select></label>{selectedModelUnavailable&&<p role="status">{tr('The selected model is not permitted by the current catalogue and price limits. Choose another listed model before sending.','النموذج المحدد غير مسموح وفق القائمة وحدود السعر الحالية. اختر نموذجاً آخر من القائمة قبل الإرسال.')}</p>}{catalogueNote==='unavailable'&&<p role="status">{tr('Could not refresh the model catalogue. Availability is unknown.','تعذّر تحديث قائمة النماذج. التوفر غير معلوم.')}</p>}<button type="button" disabled={busy||!!active} onClick={()=>{setCatalogueNote('checking');void refreshCatalogue(controller.current.signal)}}>{tr('Refresh models','تحديث النماذج')}</button><p>{subscription?tr('Uses your Codex subscription and its usage limits.','يستخدم اشتراك Codex وحدود الاستخدام الخاصة به.'):apiCapped?tr('Hosted API models must meet the server price caps. No provider fallback.','يجب أن تلتزم نماذج API بحدود السعر على الخادم. لا يُستخدم مزود بديل.'):tr('Only verified free models are accepted. No paid fallback.','تُقبل النماذج التي تم التحقق من مجانيتها فقط. لا يُستخدم بديل مدفوع.')}</p></div></details>{active&&<Button type="button" variant="outline" disabled={stopping} onClick={()=>void stopTurn()}>{stopping?tr('Stopping…','جارٍ الإيقاف…'):tr('Stop','إيقاف')}</Button>}<Button type="submit" size="icon" aria-label={tr("Send message","إرسال الرسالة")} disabled={busy||!!active||loading||!input.trim()||!!pending.current}>{busy?<Loader2 size={17} className="chat-spin"/>:<Send size={17}/>}</Button></div>
  </form>
 </div>

 {empty&&<div className="agent-starters">{starters.map(({label,icon:Icon,prompt,action})=><button key={label} disabled={promptBlocked} onClick={()=>offerPrompt(prompt,action)}><Icon size={16}/><span>{label}</span></button>)}</div>}
 </div>
 <aside className="agent-outputs" aria-label={tr("Founder work pane","عمل المؤسس")} hidden={!files||!!onOpenArtifact}>
  <div className="agent-output-heading"><h2>{language==='ar'?'مساحة العمل':'Workspace'}</h2><Button variant="ghost" size="icon" aria-label={language==='ar'?'إغلاق مساحة العمل':'Close work pane'} onClick={()=>setFiles(false)}><X size={16}/></Button></div>
  <nav className="dukkan-pane-tabs" aria-label={tr("Workspace panes","مساحات العمل")}>
   <button aria-current={paneTab==='agent'?'page':undefined} onClick={()=>setPaneTab('agent')}><ClipboardList size={16}/>{language==='ar'?'الوكيل':'Agent'}</button>
   <button aria-current={paneTab==='journey'?'page':undefined} onClick={()=>setPaneTab('journey')}><NotebookPen size={16}/>{language==='ar'?'الرحلة':'Journey'}</button>
   <button aria-current={paneTab==='browser'?'page':undefined} onClick={()=>setPaneTab('browser')}><Globe size={16}/>{language==='ar'?'المعاينة':'Preview'}</button>
  </nav>
  {paneTab==='journey'?(onOpenBusiness?<div className="dukkan-pane-body"><h3>{language==='ar'?'مساحة المشروع':'Business workspace'}</h3><p>{language==='ar'?'راجع الفكرة والاختبارات والأدلة والقرارات في مساحة مشروعك.':'Review the idea, tests, evidence and decisions in your business workspace.'}</p><Button onClick={()=>onOpenBusiness(workStage)}>{language==='ar'?'افتح مساحة المشروع':'Open business workspace'}</Button></div>:<FounderWorkbench stepsDisabled={promptBlocked} onAskSteps={(prompt,stage)=>offerPrompt(prompt,stage==='apply'?undefined:{type:'stage_draft',stage})} workspace={workspaceContext} artifacts={journeyArtifacts} demo={demo} language={language} stage={workStage} onStageChange={setWorkStage} onSaveBrief={onSaveBrief} onSaveCosts={onSaveCosts} onSaveTest={onSaveTest} onSaveResult={onSaveResult} onRecordDecision={onRecordDecision} onAdoptTest={onAdoptTest} onSaveIdeaReview={onSaveIdeaReview} onOpenEvidence={onOpenEvidence} onOpenSetup={onOpenSetup} onOpenArtifact={item=>{if(item.conversationId===conversation?.id)(onOpenArtifact?onOpenArtifact(item):setOpened(item));else void choose(item.conversationId,item.id)}} onPrepareDraft={()=>offerPrompt('Prepare a business setup application worksheet for my Kuwait business using my saved brief. Fill only known fields, leave unknown fields blank and list what is missing. Ask at most one essential question. Do not submit anything.',{type:'application_worksheet'})}/>):
   <div className="dukkan-pane-body">{paneTab==='agent'?<>
    <h3>{language==='ar'?'مهام الوكيل':'Agent tasks'}</h3><p>{language==='ar'?'اختر ما تريد تحضيره. ستراجع كل نتيجة قبل استخدامها.':'Choose what to prepare. You review every result before using it.'}</p>
    <button className="dukkan-agent-action" disabled={promptBlocked} onClick={()=>offerPrompt('Prepare a business setup application worksheet for my idea in Kuwait. Use my saved brief, fill only known fields, leave unknown fields blank and list what is missing. Cite current official requirements where possible. Ask at most one essential question. Do not submit anything.',{type:'application_worksheet'})}><FileText size={19}/><span><strong>{language==='ar'?'جهّز مسودة الطلب':'Prepare application draft'}</strong><small>{language==='ar'?'املأ ما هو معروف واترك الباقي للمراجعة':'Use known details; flag what is missing'}</small></span></button>
    <button className="dukkan-agent-action" disabled={promptBlocked} onClick={()=>offerPrompt('Check official Kuwait setup requirements relevant to my saved business idea. Show sources, unknowns and the next question I should answer. Do not claim eligibility.')}><Search size={19}/><span><strong>{language==='ar'?'تحقق من المتطلبات':'Check requirements'}</strong><small>{language==='ar'?'مصادر وأسئلة مفتوحة':'Sources and open questions'}</small></span></button>
    <div className="dukkan-agent-files"><h4>{language==='ar'?'مسودات هذه المحادثة':'Drafts in this chat'}</h4>{artifacts.length?<DraftGroupList items={artifacts} language={language} rowClassName="dukkan-document-row" onOpen={a=>onOpenArtifact?onOpenArtifact(a):setOpened(a)}/>:<p className="dukkan-empty-document">{language==='ar'?'لا توجد مسودات بعد.':'No drafts yet.'}</p>}</div><p className="dukkan-agent-boundary">{language==='ar'?'لا يتم إرسال أي طلب تلقائياً.':'Nothing is submitted automatically.'}</p>
   </>:<><h3>{language==='ar'?'معاينة المستند':'Document preview'}</h3><p>{language==='ar'?'عاين مسودتك المحلية. المواقع الرسمية تفتح بشكل منفصل.':'Preview your local draft. Official sites open separately.'}</p>{latest.length?(()=>{const a=latest.at(-1)!;return <><div className="dukkan-browser-bar"><span>{a.title}</span><Button variant="outline" size="sm" onClick={()=>onOpenArtifact?onOpenArtifact(a):setOpened(a)}>{a.kind==='stage_draft'?(language==='ar'?'افتح المسودة':'Open draft'):(language==='ar'?'راجع الحقول':'Review fields')}</Button></div><ArtifactPreview className="dukkan-browser-preview" title={a.title} artifact={a} language={language}/></>})():<p className="dukkan-empty-document">{language==='ar'?'لا توجد مسودة للمعاينة.':'No draft to preview yet.'}</p>}<div className="dukkan-official-links"><a href="https://www.moci.gov.kw/ar/e-service/kuwait-business-center/" target="_blank" rel="noopener noreferrer"><Globe size={14}/>Kuwait Business Center</a><a href="https://e.gov.kw/sites/kgoenglish/Pages/ApplicationPages/Application-Sahel-Business.aspx" target="_blank" rel="noopener noreferrer"><Globe size={14}/>Sahel Business</a></div><p className="dukkan-agent-boundary">{language==='ar'?'روابط رسمية فقط، لا توجد تعبئة أو إرسال مباشر.':'Official links only. There is no live form filling or submission.'}</p></>}</div>}
 </aside>
 </div>
 {factAction&&conversation&&<FactReview action={factAction} conversationId={conversation.id} caseId={conversation.caseId} onClose={()=>setFactAction(null)} onSaved={async()=>{await load(conversation.id,controller.current.signal)}}/>} {jobId&&<PreparationProgress jobId={jobId} onClose={()=>setJobId('')}/>} {opened&&<FileReview key={opened.id+opened.hash} artifact={opened} onRevision={(turn,message)=>{setTurns(old=>mergeById(old,[turn]));setMessages(old=>mergeById(old,[message]))}} onClose={()=>setOpened(null)}/>}</section>
}

function UserMessageContent({content,language}:{content:string;language:'en'|'ar'}){const [expanded,setExpanded]=useState(false);let fields:Record<string,unknown>|null=null;const correction=content.startsWith('Document field corrections: '),fixture=content.startsWith('Explicitly fictional Chinese company demonstration.');if(correction||fixture){try{const value=JSON.parse(content.slice(content.indexOf('{')));if(value&&typeof value==='object'&&!Array.isArray(value))fields=value}catch{}}if(!fields)return <Answer content={content}/>;return <div className="chat-field-summary"><p>{correction?(language==='ar'?'تعديل الحقول: ':'Updated fields: ')+Object.keys(fields).join(', '):(language==='ar'?'تجهيز نموذج الشركة التخيلية باستخدام ':'Prepare the fictional company form with ')+Object.keys(fields).length+(language==='ar'?' حقلاً اصطناعياً.':' synthetic fields.')}</p><button onClick={()=>setExpanded(!expanded)}>{expanded?(language==='ar'?'إخفاء القيم':'Hide values'):(language==='ar'?'عرض القيم':'Show values')}</button>{expanded&&<dl>{Object.entries(fields).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl>}</div>}
