import {useEffect,useState} from 'react'
import {Archive,ArchiveRestore,Check,Copy} from 'lucide-react'
import {calculate,formatMoney,type Workspace} from '../lib/workspace'
import type {WriteResult} from '../lib/workspace-writer'
import {Button} from './ui/button'
export function CostScenarios({workspace,onSave,unsaved,language='en',onDirty=()=>{}}:{onDirty?:(value:boolean)=>void;language?:'en'|'ar';unsaved:boolean;workspace:Workspace;onSave:(w:Workspace)=>Promise<WriteResult>}){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en
 const [name,setName]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showArchived,setShowArchived]=useState(false)
 useEffect(()=>{onDirty(!!name||!!note||busy)},[name,note,busy]);useEffect(()=>()=>onDirty(false),[])
 async function save(next:Workspace){setBusy(true);setError('');try{const result=await onSave(next);if(!result.ok)throw Error(result.reason||'Could not save scenario.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function capture(){if(unsaved){setError('Save or discard your current edits first.');return}if(!calculate(workspace.costs).valid){setError('Save complete, valid cost estimates before capturing a scenario.');return}if(workspace.costScenarios.length>=30){setError('Scenario limit reached. Export your business record before creating more.');return}if(await save({...workspace,costScenarios:[...workspace.costScenarios,{id:crypto.randomUUID(),name:name.trim(),note:note.trim(),date:new Date().toISOString(),archived:false,costs:{...workspace.costs}}]})){setName('');setNote('')}}
 return <details className="dukkan-cost-scenarios"><summary><Copy size={16}/> {tr('Saved scenarios','السيناريوهات المحفوظة')} · {workspace.costScenarios.filter(s=>!s.archived).length}</summary>{unsaved&&<p role="status">{tr('Save or discard cost edits first.','احفظ تعديلات التكاليف أو تجاهلها أولاً.')}</p>}<p>{tr('Saved estimates for the same time period.','تقديرات محفوظة للفترة الزمنية نفسها.')}</p><form onSubmit={e=>{e.preventDefault();void capture()}}><label>{tr('Scenario name','اسم السيناريو')}<input aria-label="Scenario name" maxLength={80} required value={name} onChange={e=>setName(e.target.value)}/></label><label>{tr('Assumptions and time period','الافتراضات والفترة الزمنية')}<textarea aria-label="Scenario assumptions" required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button type="submit" disabled={busy||unsaved||!name.trim()||!note.trim()}><Copy size={16}/>{tr('Save current estimates','حفظ التقديرات الحالية')}</Button></form>{workspace.costScenarios.filter(s=>showArchived||!s.archived).map(s=>{const result=calculate(s.costs);return <article key={s.id}><h3>{s.name}{s.archived?tr(' · Archived',' · مؤرشف'):''}</h3><p>{s.note}</p><small>{s.date.slice(0,10)} · {tr('Founder estimate','تقدير صاحب المشروع')}</small><dl><dt>{tr('Price / unit cost','السعر / تكلفة الوحدة')}</dt><dd>KWD {s.costs.price} / {s.costs.variable}</dd><dt>{tr('Fixed costs / planned units','التكاليف الثابتة / الوحدات المخططة')}</dt><dd>KWD {s.costs.fixed} / {s.costs.units}</dd>{result.valid&&<><dt>{tr('Contribution per unit','العائد لكل وحدة')}</dt><dd>KWD {formatMoney(result.margin)}</dd><dt>{tr('Break-even volume','حجم التعادل')}</dt><dd>{result.breakEven===null?tr('Not reachable with these unit economics','لا تتحقق بهذه المدخلات'):result.breakEven+tr(' units',' وحدة')}</dd><dt>{tr('Scenario result','نتيجة السيناريو')}</dt><dd>KWD {formatMoney(result.result)}</dd></>}</dl>{!s.archived&&<Button variant="outline" disabled={busy||unsaved} onClick={()=>void save({...workspace,costs:{...s.costs}})}><Check size={16}/>{tr('Use these assumptions','استخدام هذه الافتراضات')}</Button>}<Button variant="ghost" disabled={busy} onClick={()=>void save({...workspace,costScenarios:workspace.costScenarios.map(x=>x.id===s.id?{...x,archived:!x.archived}:x)})}>{s.archived?<ArchiveRestore size={16}/>:<Archive size={16}/>} {s.archived?tr('Restore scenario','استعادة السيناريو'):tr('Archive scenario','أرشفة السيناريو')}</Button></article>})}<label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>{tr('Show archived scenarios','عرض السيناريوهات المؤرشفة')}</label>{error&&<p role="alert">{error}</p>}</details>
}
