import {useEffect,useRef,useState,type ReactNode} from 'react'
import {Mouse,DoorOpen} from 'lucide-react'
import {entranceMotion} from '@/lib/entrance-motion'
import {readIdea,readIdeas} from '@/lib/idea-folders'
import './door-entrance.css'

type Language='en'|'ar'
const copy={
 en:{welcome:'Welcome to Dukkan',heading:'From idea to licence',description:'Shape your idea, test it, and keep your plan and evidence together.',begin:'Begin',resume:'Resume workspace',scroll:'Scroll to open the door',note:'Build your business one decision at a time.',label:'Welcome to Dukkan. Scroll to open the door, or choose Begin.'},
 ar:{welcome:'مرحباً بك في دُكّان',heading:'من الفكرة إلى الرخصة',description:'رتّب فكرتك، واختبرها، واحتفظ بخطتك وأدلتك في مكان واحد.',begin:'ابدأ',resume:'تابع مساحة العمل',scroll:'مرّر لفتح الباب',note:'ابنِ مشروعك، قراراً بعد قرار.',label:'مرحباً بك في دُكّان. مرّر لفتح الباب أو اختر ابدأ.'}
} as const

function savedIdeaExists(){try{const ideas=readIdeas();return Boolean(readIdea(ideas.selectedId).workspace.brief.idea.trim())}catch{return false}}

function DoorLeaf({side}:{side:'left'|'right'}){
 const id='timber-'+side
 return <svg viewBox="0 0 120 370" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id={id} x1="0" x2="1"><stop stopColor="#956b42"/><stop offset=".2" stopColor="#b48958"/><stop offset=".7" stopColor="#ba905f"/><stop offset="1" stopColor="#8b603b"/></linearGradient><pattern id={id+'-grain'} width="17" height="90" patternUnits="userSpaceOnUse"><path d="M3-10C12 12-4 32 4 58S3 91 8 106M12-6C3 27 20 37 12 77" fill="none" stroke="#513b28" strokeWidth=".55" opacity=".23"/></pattern></defs><rect width="120" height="370" fill={`url(#${id})`}/><rect width="120" height="370" fill={`url(#${id}-grain)`}/><rect x="4" y="4" width="112" height="362" fill="none" stroke="#d0ab78" strokeWidth="2"/><rect x="10" y="10" width="100" height="350" fill="none" stroke="#725034" strokeWidth="2"/>{[19,102,185,268].map(y=><g key={y}><rect x="17" y={y} width="86" height="72" fill="#a77b4d" fillOpacity=".35" stroke="#725133" strokeWidth="1"/><path d={`M18 ${y+71}V${y+1}H102`} fill="none" stroke="#d5ad73" strokeWidth="1.4"/>{[19,30,41,52,63,74,85,98].map(x=><g key={x}><circle cx={x} cy={y+3} r="1.2" fill="#61472f"/><circle cx={x} cy={y+68} r="1.2" fill="#61472f"/></g>)}{[18,32,47,59].map(d=><g key={d}><circle cx="20" cy={y+d} r="1.2" fill="#61472f"/><circle cx="100" cy={y+d} r="1.2" fill="#61472f"/></g>)}</g>)}{[95,178,261].map(y=><g key={y}><rect x="8" y={y} width="104" height="7" fill="#936639"/><path d={`M8 ${y+1}H112`} stroke="#c69c64"/>{[14,40,80,106].map(x=><circle key={x} cx={x} cy={y+4} r="1.5" fill="#4d422e"/>)}</g>)}<g transform={`translate(${side==='left'?102:18} 181)`}><rect x="-4" y="-6" width="8" height="22" rx="2" fill="#5f5136"/><circle cy="3" r="6" fill="none" stroke="#3e392b" strokeWidth="2.4"/><circle cy="-4" r="1.6" fill="#d5b171"/></g></svg>
}
function DoorFrame(){return <svg className="door-frame" viewBox="0 0 400 500" aria-hidden="true"><defs><linearGradient id="stone" x1="0" x2="1"><stop stopColor="#e0c8a9"/><stop offset=".5" stopColor="#f0e0c8"/><stop offset="1" stopColor="#d4b693"/></linearGradient></defs><path d="M45 58H355V462H320V94H80V462H45Z" fill="url(#stone)" stroke="#ba9973" strokeWidth="1"/><path d="M72 91H328L320 104H80Z" fill="#a88662"/><path d="M72 91V459L80 449V104Z" fill="#d1b48d"/><path d="M328 91V459L320 449V104Z" fill="#b79670"/>{[109,146,183,220,257,294,331,368,405,442].map((y,i)=><g key={y} stroke="#bfa382" strokeWidth=".9"><path d={`M45 ${y}H72M328 ${y}H355`}/><path d={`M${i%2?57:64} ${y}v-36M${i%2?339:346} ${y}v-36`}/><path d={`M46 ${y+1}H71M329 ${y+1}H354`} stroke="#f4e7d3"/></g>)}<rect x="39" y="49" width="322" height="9" fill="#ecdac0" stroke="#bfa17b"/><rect x="49" y="59" width="302" height="8" fill="#f3e6d1"/><path d="M82 69H318V94H82Z" fill="#c4a17a" stroke="#b58e62"/>{[90,124,158,192,226,260,294].map(x=><path key={x} d={`M${x} 70V93`} stroke="#dfc5a2"/>)}<path d="M80 450H320L338 463H62Z" fill="#d4b997" stroke="#b59670"/><path d="M40 463H360" stroke="#b39470" strokeWidth="2"/></svg>}

export function DoorEntrance({children,replay=0}:{children:ReactNode;replay?:number}){
 const [visible,setVisible]=useState(()=>{const query=new URLSearchParams(location.search);if(query.has('conversation')||query.get('intro')==='0')return false;if(query.get('intro')==='1')return true;try{return !sessionStorage.getItem('dukkan-entered')}catch{return true}})
 const [language,setLanguage]=useState<Language>(()=>{try{return localStorage.getItem('dukkan-language')==='ar'?'ar':'en'}catch{return 'en'}})
 const [hasWork,setHasWork]=useState(savedIdeaExists)
 const scroller=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null),raf=useRef(0),entered=useRef(false)
 const t=copy[language]
 useEffect(()=>{if(replay>0){entered.current=false;setHasWork(savedIdeaExists());setVisible(true);requestAnimationFrame(()=>scroller.current?.scrollTo({top:0}))}},[replay])
 function chooseLanguage(next:Language){
  setLanguage(next)
  try{localStorage.setItem('dukkan-language',next)}catch{}
  document.documentElement.lang=next==='ar'?'ar':'en-GB'
  document.documentElement.dir=next==='ar'?'rtl':'ltr'
  window.dispatchEvent(new CustomEvent('dukkan-language-change',{detail:next}))
 }
 function enter(){if(entered.current)return;entered.current=true;try{sessionStorage.setItem('dukkan-entered','1')}catch{}const url=new URL(location.href);url.searchParams.delete('intro');history.replaceState(null,'',url);setVisible(false);requestAnimationFrame(()=>(document.querySelector<HTMLTextAreaElement>('.dukkan-onboarding textarea')||document.getElementById('chat-message'))?.focus({preventScroll:true}))}
 function begin(){const node=scroller.current;if(!node||window.matchMedia('(prefers-reduced-motion: reduce)').matches){enter();return}node.scrollTo({top:node.scrollHeight-node.clientHeight,behavior:'smooth'})}
 useEffect(()=>{if(!visible)return;scroller.current?.focus({preventScroll:true});return()=>cancelAnimationFrame(raf.current)},[visible])
 function scroll(){if(raf.current)return;raf.current=requestAnimationFrame(()=>{raf.current=0;const el=scroller.current,node=stage.current;if(!el||!node)return;const readingSpace=Math.max(0,node.clientHeight-el.clientHeight);const motion=entranceMotion((el.scrollTop-readingSpace)/Math.max(1,el.scrollHeight-el.clientHeight-readingSpace));node.style.setProperty('--door-angle',motion.angle+'deg');node.style.setProperty('--door-scale',String(motion.scale));node.style.setProperty('--door-fade',String(motion.fade));node.style.setProperty('--door-copy',String(motion.copy));node.dataset.phase=motion.phase;if(motion.progress>=.995)enter()})}
 return <><div className="entrance-app" inert={visible} aria-hidden={visible||undefined}>{children}</div>{visible&&<div className="door-entrance" dir={language==='ar'?'rtl':'ltr'} lang={language} ref={scroller} tabIndex={0} onScroll={scroll} aria-label={t.label}><div className="door-scroll-track"><div className="door-stage" ref={stage} data-phase="closed"><header className="door-header"><img className="door-brand-logo" src="./brand/dukkan-05-bilingual-wordmark.svg" alt={language==='ar'?'دُكّان — Dukkan':'Dukkan — دُكّان'}/><div className="door-language" role="group" aria-label={language==='ar'?'اختر اللغة':'Choose language'}><button type="button" aria-pressed={language==='en'} onClick={()=>chooseLanguage('en')}>English</button><button type="button" aria-pressed={language==='ar'} onClick={()=>chooseLanguage('ar')} lang="ar">العربية</button></div></header><main className="door-copy"><span>{t.welcome}</span><h1>{t.heading}</h1><p>{t.description}</p><button className="door-primary" type="button" onClick={begin}><DoorOpen size={17}/>{hasWork?t.resume:t.begin}</button><small>{t.note}</small></main><div className="door-camera" aria-hidden="true"><div className="door-ground"/><div className="door-building"><div className="door-interior"><div className="door-inner-light"/><div className="door-inner-floor"/></div><div className="door-leaves"><div className="door-leaf left"><DoorLeaf side="left"/></div><div className="door-leaf right"><DoorLeaf side="right"/></div></div><DoorFrame/></div></div><div className="door-footer"><div className="door-scroll-cue"><Mouse size={15}/><span>{t.scroll}</span></div></div></div></div></div>}</>
}
