import {useState} from 'react'
import {Button} from '@/components/ui/button'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'
import {Field,Choice} from '@/components/fields'
import {areas,kinds,sectors,today,uid,newHypothesis,type Workspace,type Brief,type Evidence,type Hypothesis} from '@/lib/workspace'
export function EditorFrame({title,description,onClose,children}:{title:string;description:string;onClose:()=>void;children:React.ReactNode}){return <Dialog open onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function BriefEditor({brief,onClose,onSave}:{brief:Brief;onClose:()=>void;onSave:(b:Brief)=>void}){const [b,setB]=useState(brief);const edit=(k:keyof Brief,v:string)=>setB({...b,[k]:v});return <EditorFrame title="Your business, in your words." description="Changing your customer, problem, offer or boundaries flags existing assumptions for review." onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(b.idea.trim())onSave(b)}}><Field label="Business or idea name" value={b.idea} onChange={v=>edit('idea',v)} required/><div className="two-fields"><Choice label="Business activity" value={b.sector} options={sectors} onChange={v=>edit('sector',v)}/><Field label="Location" value={b.location} onChange={v=>edit('location',v)}/></div><Field label="Your first customer" value={b.customer} onChange={v=>edit('customer',v)} placeholder="One specific group you can reach"/><Field label="The problem they face" value={b.problem} onChange={v=>edit('problem',v)} multiline/><Field label="What they do instead" value={b.alternative} onChange={v=>edit('alternative',v)}/><Field label="Your smallest useful offer" value={b.offer} onChange={v=>edit('offer',v)} multiline/><Field label="Budget, time and constraints" value={b.boundary} onChange={v=>edit('boundary',v)} multiline/><div className="editor-footer"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Save business brief</Button></div></form></EditorFrame>}
export function EvidenceEditor({workspace,initial,hypothesisId,onClose,onSave,onDelete}:{workspace:Workspace;initial?:Evidence;hypothesisId?:string;onClose:()=>void;onSave:(e:Evidence)=>void;onDelete?:(e:Evidence)=>void}){
 const [note,setNote]=useState<Evidence>(initial||{id:uid(),hypothesisId:hypothesisId||'',kind:'Customer conversation',text:'',source:'',date:today(),signal:'Unclear',limitation:''}),[error,setError]=useState('')
 const edit=(k:keyof Evidence,v:string)=>setNote({...note,[k]:v});const names=new Map(workspace.hypotheses.map(h=>[h.id,h.title]))
 return <EditorFrame title={initial?'Edit evidence':'Capture something real.'} description="Record what happened, where it came from and which assumption it informs." onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(!note.text.trim()||!note.source.trim()){setError('Add an observation and its source.');return}onSave(note)}}><div className="field"><label htmlFor="evidence-link">Link to an assumption</label><select id="evidence-link" value={note.hypothesisId} onChange={e=>edit('hypothesisId',e.target.value)}><option value="">Unlinked note</option>{[...names].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></div><div className="two-fields"><Choice label="Kind of evidence" value={note.kind} options={kinds} onChange={v=>edit('kind',v)}/><Choice label="Signal" value={note.signal} options={['Supports','Challenges','Unclear']} onChange={v=>edit('signal',v)}/></div><Field label="What did you learn?" value={note.text} onChange={v=>edit('text',v)} multiline required/><Field label="Source or reference" value={note.source} onChange={v=>edit('source',v)} placeholder="Anonymous interview note, observation or source URL" required/><Field label="Date observed or published" value={note.date} onChange={v=>edit('date',v)} type="date" required/><Field label="Limitations (optional)" value={note.limitation} onChange={v=>edit('limitation',v)} placeholder="What can’t this tell you?"/><p className="form-error" role="alert">{error}</p><div className="editor-footer">{initial&&onDelete&&<Button className="delete-note" variant="ghost" type="button" onClick={()=>onDelete(initial)}>Remove note</Button>}<Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Save evidence</Button></div></form></EditorFrame>
}
export function HypothesisEditor({onClose,onSave}:{onClose:()=>void;onSave:(h:Hypothesis)=>void}){const [h,setH]=useState(newHypothesis());return <EditorFrame title="What needs to be true?" description="Choose a claim you could support or challenge with real evidence." onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(h.title.trim())onSave(h)}}><Field label="Assumption" value={h.title} onChange={title=>setH({...h,title})} multiline required placeholder="Customers will pay enough to cover the full delivery cost."/><div className="two-fields"><Choice label="Area" value={h.area} options={areas} onChange={area=>setH({...h,area:area as Hypothesis['area']})}/><Choice label="Priority" value={h.priority} options={['Critical','Important','Later']} onChange={priority=>setH({...h,priority:priority as Hypothesis['priority']})}/></div><div className="editor-footer"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit">Add assumption</Button></div></form></EditorFrame>}
