import {useEffect,useState} from 'react'
import {z} from 'zod'
import {chatRequest} from '../lib/chat-api'
const emailSchema=z.object({id:z.string(),to:z.string(),subject:z.string(),body:z.string(),hash:z.string(),status:z.string(),review:z.object({hash:z.string(),sender:z.string().nullable()}).nullable(),receipt:z.object({provider:z.string(),messageId:z.string(),sender:z.string()}).nullable(),error:z.string().nullable().optional()})
const statusSchema=z.object({configured:z.boolean(),provider:z.string().nullable(),sender:z.string().nullable(),reason:z.string().nullable()})
type Email=z.infer<typeof emailSchema>
export function EmailWorkspace({language,conversationId,refresh,onDirty}:{language:'en'|'ar';conversationId:string;refresh:string;onDirty:(dirty:boolean)=>void}){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en
 const [dirtyIds,setDirtyIds]=useState<Record<string,boolean>>({})
 useEffect(()=>onDirty(Object.values(dirtyIds).some(Boolean)),[dirtyIds])
 const [emails,setEmails]=useState<Email[]>([]),[status,setStatus]=useState<z.infer<typeof statusSchema>|null>(null),[error,setError]=useState('')
 useEffect(()=>{const controller=new AbortController();void Promise.all([chatRequest('/api/conversations/'+encodeURIComponent(conversationId)+'/emails',z.object({emails:z.array(emailSchema)}),controller.signal),chatRequest('/api/email/status',statusSchema,controller.signal)]).then(([data,capability])=>{if(!controller.signal.aborted){setEmails(data.emails);setStatus(capability);setError('')}}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[conversationId,refresh])
 if(!emails.length)return error?<details className="email-workspace"><summary>{tr('Email drafts unavailable','مسودات البريد غير متاحة')}</summary><p>{error}</p></details>:null
 return <section className="email-workspace" aria-label={tr('Saved email drafts','مسودات البريد المحفوظة')}><h2>{tr('Outreach drafts','مسودات التواصل')}</h2>{emails.map(email=><EmailDraft language={language} key={email.id+email.hash} email={email} onDirty={dirty=>setDirtyIds(old=>old[email.id]===dirty?old:{...old,[email.id]:dirty})} sender={status?.sender||null} configured={!!status?.configured} onUpdate={updated=>setEmails(old=>old.map(item=>item.id===updated.id?updated:item))}/>)}<p>{(status?.reason?tr(status.reason,'اربط مزوّد بريد ومرسلاً موثّقاً للإرسال من دكان.'):null)||tr('Sending requires your explicit approval for the reviewed recipient and message.','يتطلب الإرسال موافقتك الصريحة على المستلم والرسالة بعد مراجعتهما.')}</p></section>
}
function EmailDraft({language,email,sender,configured,onUpdate,onDirty}:{language:'en'|'ar';onDirty:(dirty:boolean)=>void;email:Email;sender:string|null;configured:boolean;onUpdate:(email:Email)=>void}){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en
 const statuses:Record<string,string>={draft:'مسودة',reviewed:'تمت المراجعة',sending:'جارٍ الإرسال',sent:'قبله مزوّد البريد',failed:'تعذّر الإرسال',unknown:'نتيجة الإرسال غير معروفة'}
 const [editing,setEditing]=useState(false),[to,setTo]=useState(email.to),[subject,setSubject]=useState(email.subject),[body,setBody]=useState(email.body),[busy,setBusy]=useState(false),[error,setError]=useState(''),[approved,setApproved]=useState(false)
 const dirty=editing&&(to!==email.to||subject!==email.subject||body!==email.body)
 useEffect(()=>{onDirty(dirty||busy);const warn=(event:BeforeUnloadEvent)=>{if(dirty||busy){event.preventDefault();event.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty,busy])
 const locked=['sending','sent','unknown'].includes(email.status),reviewed=email.review?.hash===email.hash&&email.review.sender===sender
 async function act(action:'edit'|'review'|'send'){if(busy)return;setBusy(true);setError('');try{const result=await chatRequest('/api/emails/'+encodeURIComponent(email.id)+'/'+action,z.object({email:emailSchema}),new AbortController().signal,{expectedHash:email.hash,...(action==='edit'?{to,subject,body}:action==='send'?{approval:approved}:{})},crypto.randomUUID());onUpdate(result.email);setEditing(false);setApproved(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <article className="email-draft"><header><strong>{email.subject}</strong><span>{email.status==='sent'?tr('Provider accepted · delivery unconfirmed','قبله مزوّد البريد · لم يُؤكد التسليم'):language==='ar'?(statuses[email.status]||email.status):email.status}</span></header><p>{tr('From: ','من: ')}{sender||tr('Sender not connected','المرسل غير متصل')}</p>{editing?<><label>{tr('To','إلى')}<input dir="ltr" value={to} onChange={e=>setTo(e.target.value)}/></label><label>{tr('Subject','الموضوع')}<input dir="auto" value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>{tr('Message','الرسالة')}<textarea dir="auto" rows={8} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy} onClick={()=>void act('edit')}>{tr('Save draft','حفظ المسودة')}</button><button disabled={busy} onClick={()=>{setTo(email.to);setSubject(email.subject);setBody(email.body);setEditing(false)}}>{tr('Cancel edit','إلغاء التعديل')}</button></>:<><p>{tr('To: ','إلى: ')}{email.to}</p><pre dir="auto">{email.body}</pre>{!locked&&<div className="email-actions"><button disabled={busy} onClick={()=>setEditing(true)}>{tr('Edit draft','تعديل المسودة')}</button><button disabled={busy||reviewed} onClick={()=>void act('review')}>{reviewed?tr('Reviewed','تمت المراجعة'):tr('Mark reviewed','تسجيل المراجعة')}</button></div>}{!locked&&configured&&reviewed&&<><label className="email-approval"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>{tr('Send this exact message to ','أرسل هذه الرسالة كما هي إلى ')}{email.to}{tr(' from ',' من ')}{sender}</label><button disabled={busy||!approved} onClick={()=>void act('send')}>{tr('Approve and send','اعتماد وإرسال')}</button></>}</>}{email.receipt&&<p>{tr('Receipt: ','إيصال: ')}{email.receipt.provider} · {email.receipt.messageId}</p>}{(error||email.error)&&<p role="alert">{error||email.error}</p>}</article>
}
