import {useEffect,useState} from 'react'
import {parseCsv,previewFinance,applyFinanceImport,importFields,type ColumnMap,type ImportPreview} from '../lib/finance-import'
import {download,type Workspace} from '../lib/workspace'
import type {WriteResult} from '../lib/workspace-writer'
export function FinanceImport({workspace,language,onSave,onDirty,onClose}:{workspace:Workspace;language:'en'|'ar';onSave:(w:Workspace)=>Promise<WriteResult>;onDirty:(v:boolean)=>void;onClose:()=>void}){
 const t=(en:string,ar:string)=>language==='ar'?ar:en
 const [rows,setRows]=useState<string[][]>([]),[source,setSource]=useState(''),[basis,setBasis]=useState<'actual'|'simulated'>('actual'),[mapping,setMapping]=useState<ColumnMap>({reference:-1,date:-1,title:-1,direction:-1,amount:-1}),[preview,setPreview]=useState<ImportPreview|null>(null),[snapshot,setSnapshot]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const labels={reference:t('Transaction reference','مرجع المعاملة'),date:t('Date','التاريخ'),title:t('Description','الوصف'),direction:t('Income / expense','دخل / مصروف'),amount:t('Amount (KWD)','المبلغ (د.ك)')}
 useEffect(()=>{onDirty(rows.length>0||busy);const warn=(e:BeforeUnloadEvent)=>{if(rows.length||busy){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[rows,busy,onDirty])
 useEffect(()=>()=>onDirty(false),[onDirty])
 function fail(e:unknown){setError(language==='ar'?'تعذّر الاستيراد. راجع تنسيق الأعمدة والتواريخ والمبالغ والمراجع الفريدة. لم تُحفظ أي معاملات. '+(e instanceof Error?e.message:''):e instanceof Error?e.message:'Import failed.')}
 async function load(file?:File){if(!file)return;setBusy(true);setError('');setPreview(null);setRows([]);try{if(file.size>200000)throw Error('Use a CSV file smaller than 200 KB.');const parsed=parseCsv(await file.text());setRows(parsed);setSource(file.name.replace(/\.csv$/i,''));setMapping(Object.fromEntries(importFields.map(f=>[f,parsed[0].findIndex(v=>v.toLowerCase()===f)])) as ColumnMap)}catch(e){fail(e)}finally{setBusy(false)}}
 async function review(){setBusy(true);setError('');setPreview(null);const current=JSON.stringify(workspace);try{const result=await previewFinance(rows,mapping,source,basis,workspace.lifecycle);setPreview(result);setSnapshot(current)}catch(e){fail(e)}finally{setBusy(false)}}
 async function save(){if(!preview)return;setBusy(true);setError('');try{if(JSON.stringify(workspace)!==snapshot)throw Error('Business records changed. Preview this import again.');const result=await onSave({...workspace,lifecycle:applyFinanceImport(workspace.lifecycle,preview,new Date().toISOString())});if(!result.ok)throw Error(result.reason||'Save failed.');onClose()}catch(e){fail(e)}finally{setBusy(false)}}
 return <section className="finance-import" aria-label={t('Import financial records','استيراد معاملات مالية')}><header><h2>{t('Import financial records','استيراد معاملات مالية')}</h2><button disabled={busy} onClick={onClose}>{t('Cancel import','إلغاء الاستيراد')}</button></header><p>{t('Review KWD transactions before saving. Imported records start as prepared; they enter actual cash flow only after review and completion.','راجع المعاملات بالدينار الكويتي قبل حفظها. تبدأ كسجلات مُعدّة ولا تدخل التدفق النقدي الفعلي إلا بعد المراجعة وتسجيل اكتمالها.')}</p><button disabled={busy} onClick={()=>download('reference,date,title,direction,amount\nDEMO-001,2026-01-01,Synthetic example,income,0.999\n','dukkan-finance-template.csv','text/csv')}>{t('Download CSV template','تنزيل قالب CSV')}</button><label>{t('CSV file','ملف CSV')}<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{void load(e.target.files?.[0]);e.target.value=''}}/></label>
 {rows.length>0&&<><label>{t('Source name (keep this consistent for duplicate checks)','اسم المصدر (ثبّته للتحقق من التكرار)')}<input value={source} maxLength={200} disabled={busy} onChange={e=>{setSource(e.target.value);setPreview(null)}}/></label><label>{t('Data basis','أساس البيانات')}<select value={basis} disabled={busy} onChange={e=>{setBasis(e.target.value as 'actual'|'simulated');setPreview(null)}}><option value="actual">{t('Actual, reported by you','فعلي، حسب بياناتك')}</option><option value="simulated">{t('Simulated test data','بيانات محاكاة')}</option></select></label><div className="finance-import-mapping">{importFields.map(field=><label key={field}>{labels[field]}<select value={mapping[field]} disabled={busy} onChange={e=>{setMapping({...mapping,[field]:Number(e.target.value)});setPreview(null)}}><option value={-1}>{t('Choose column','اختر العمود')}</option>{rows[0].map((name,i)=><option key={i} value={i}>{name}</option>)}</select></label>)}</div><p>{t('Dates: YYYY-MM-DD. Direction: income or expense. Non-negative amounts with up to three decimals. Each transaction needs a stable, unique reference.','التاريخ: YYYY-MM-DD. نوع التدفق: income أو expense. المبلغ غير سالب وبحد أقصى ثلاث خانات عشرية. لكل معاملة مرجع ثابت وفريد.')}</p><button disabled={busy} onClick={()=>void review()}>{busy?t('Checking…','جارٍ التحقق…'):t('Preview import','معاينة الاستيراد')}</button></>}
 {preview&&<><p role="status">{preview.rows.filter(r=>!r.duplicate).length} {t('new records','سجلات جديدة')} · {preview.rows.filter(r=>r.duplicate).length} {t('duplicates skipped','سجلات مكررة ستُتجاوز')}</p><p dir="auto">{t('New-row totals','إجماليات الصفوف الجديدة')}: {t('Income','الدخل')} KWD {preview.income.toFixed(3)} · {t('Expenses','المصروفات')} KWD {preview.expenses.toFixed(3)}</p><div className="finance-import-table"><table><thead><tr><th>{labels.reference}</th><th>{labels.date}</th><th>{labels.title}</th><th>{labels.direction}</th><th>{labels.amount}</th><th>{t('Action','الإجراء')}</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.id}><td>{row.reference}</td><td>{row.values.date}</td><td>{row.values.title}</td><td>{row.values.direction==='income'?t('Income','دخل'):t('Expense','مصروف')}</td><td>{row.values.amount}</td><td>{row.duplicate?t('Skip existing','تجاوز الموجود'):t('Save prepared','حفظ كمُعدّ')}</td></tr>)}</tbody></table></div><button disabled={busy||preview.rows.every(r=>r.duplicate)} onClick={()=>void save()}>{t('Save reviewed rows','حفظ الصفوف بعد مراجعتها')}</button></>}{error&&<p role="alert">{error}</p>}</section>
}
