import {evidenceNeedsReview} from '@/lib/research'
import {ResearchWorkflow} from '@/components/research-workflow'
import {SetupTracker} from '@/components/setup-tracker'
import type {WriteResult} from '@/lib/workspace-writer'
import type {Evidence} from '@/lib/workspace'
import {useEffect,useState} from 'react'
import {BookOpen,Check,FileText,FlaskConical,Lightbulb,Scale,MessageCircle,PenLine,Plus} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {calculate,nextHypothesis,newHypothesis,type Brief,type Decision,type Hypothesis,type Workspace} from '@/lib/workspace'
import {safeLink} from '@/lib/preparation-api'
import type {ChatArtifact} from '@/lib/chat-api'
import {parseDraftSections} from '@/lib/draft-sections'
import {IdeaReview} from '@/components/idea-review'
import {TestProposal} from '@/components/test-proposal'
import journey from '../../../knowledge/market/phase-map.json'

export type Stage='idea'|'validate'|'plan'|'apply'
type Language='en'|'ar'
type ProposedTest=NonNullable<ChatArtifact['proposedTest']>
type Props={workspace:Workspace;artifacts:ChatArtifact[];demo:boolean;language:Language;stage:Stage;onStageChange:(stage:Stage)=>void;onSaveBrief:(brief:Brief)=>void;onSaveCosts:(costs:Workspace['costs'])=>void;onSaveTest:(test:Hypothesis)=>void;onSaveResult:(test:Hypothesis)=>void;onRecordDecision:(test:Hypothesis,outcome:Decision['outcome'],reason:string)=>void;onAdoptTest:(artifact:ChatArtifact,proposal:ProposedTest)=>void;onSaveIdeaReview:(artifact:ChatArtifact,choice:'test'|'revise'|'park',reason:string,selectedOption:string,customOption?:{title:string;kind:'feature'|'expansion'|'pivot';tradeoff:string})=>void;onOpenEvidence:()=>void;onOpenSetup:()=>void;onOpenArtifact:(artifact:ChatArtifact)=>void;onPrepareDraft:()=>void;onAskSteps:(prompt:string,stage:Stage)=>void;stepsDisabled?:boolean;focus?:string;onSaveEvidence?:(note:Evidence)=>Promise<WriteResult>;onSaveSetup?:(items:Workspace['setup'])=>Promise<WriteResult>}
const text={
 en:{journey:'Your idea',idea:'Challenge',validate:'Test demand',plan:'Plan costs',apply:'Prepare setup',ideaTitle:'Is this idea worth testing?',validateTitle:'Will customers act on it?',planTitle:'Can this business work financially?',applyTitle:'Application preparation',ask:'Draft this with Dukkan',edit:'Edit saved details',save:'Save changes',note:'Add evidence note',test:'Save a test',draft:'Prepare application draft',none:'Nothing drafted yet. Dukkan can create a first version from your saved idea.',assumptions:'Assumptions to test',unknowns:'Still unknown',sources:'Sources',review:'AI draft for review. It does not change your confirmed business record.',sample:'Fictional example',local:'Your business record',costs:'Cost scenario',breakEven:'Break-even units per month',notForecast:'Your estimates, not a demand forecast.',requirements:'Check current official requirements before using any draft.',noSubmit:'Nothing is submitted automatically.'},
 ar:{journey:'فكرتك',idea:'الفكرة',validate:'التحقق',plan:'الخطة',apply:'التقديم',ideaTitle:'هل تستحق الفكرة الاختبار؟',validateTitle:'هل سيتفاعل العملاء معها؟',planTitle:'هل يمكن أن تنجح مالياً؟',applyTitle:'تجهيز الطلب',ask:'اكتب مسودة مع دُكَّان',edit:'عدّل التفاصيل المحفوظة',save:'احفظ التغييرات',note:'أضف دليلًا',test:'احفظ اختبارًا',draft:'جهّز مسودة الطلب',none:'لا توجد مسودة بعد. يمكن لدُكَّان إنشاء نسخة أولى من فكرتك المحفوظة.',assumptions:'افتراضات تحتاج اختبارًا',unknowns:'ما زال مجهولًا',sources:'المصادر',review:'مسودة بالذكاء الاصطناعي للمراجعة. لا تغير سجل مشروعك المؤكد.',sample:'مثال تخيلي',local:'سجل مشروعك',costs:'سيناريو التكاليف',breakEven:'وحدات التعادل شهرياً',notForecast:'تقديراتك وليست توقعاً للطلب.',requirements:'تحقق من المتطلبات الرسمية الحالية قبل استخدام أي مسودة.',noSubmit:'لا يتم تقديم أي طلب تلقائياً.'}
} as const

function DraftLine({value}:{value:string}){return <>{value.split(/(\*\*[^*]+\*\*)/g).map((part,index)=>part.startsWith('**')&&part.endsWith('**')?<strong key={index}>{part.slice(2,-2)}</strong>:part)}</>}

export function FounderWorkbench({workspace,artifacts,demo,language,stage,onStageChange,onSaveBrief,onSaveCosts,onSaveTest,onSaveResult,onRecordDecision,onAdoptTest,onSaveIdeaReview,onOpenEvidence,onOpenArtifact,onPrepareDraft,onAskSteps,stepsDisabled,focus='',onSaveEvidence,onSaveSetup}:Props){
 const t=text[language]
 const [brief,setBrief]=useState(workspace.brief)
 const [costs,setCosts]=useState(workspace.costs)
 const [testDraft,setTestDraft]=useState<Hypothesis|null>(null)
 const [emptyTest]=useState(()=>newHypothesis(''))
 const [resultDraft,setResultDraft]=useState('')
 const [decisionOutcome,setDecisionOutcome]=useState<Decision['outcome']>('Keep testing')
 const [decisionReason,setDecisionReason]=useState('')
 const [saved,setSaved]=useState(false)
 const [saving,setSaving]=useState(false)
 const [saveError,setSaveError]=useState('')
 useEffect(()=>setSaved(false),[stage])
 useEffect(()=>setBrief(workspace.brief),[workspace.brief])
 useEffect(()=>setCosts(workspace.costs),[workspace.costs])
 const draft=artifacts.filter(item=>item.kind==='stage_draft'&&item.stage===stage&&!artifacts.some(newer=>newer.supersedesArtifactId===item.id)).at(-1)
 const worksheets=artifacts.filter(item=>item.kind==='application_worksheet'&&!artifacts.some(newer=>newer.supersedesArtifactId===item.id))
 const guidance=journey.webappStages[stage]
 const scenario=calculate(workspace.costs)
 const ideaChoice=draft&&stage==='idea'?workspace.ideaReviewDecisions.filter(item=>item.artifactId===draft.id).at(-1):undefined
 const testAlreadyAdopted=draft?workspace.hypotheses.some(item=>item.test.provenance?.artifactId===draft.id):false
 const focusTest=workspace.savedTests.at(-1)
 const focusHypothesis=workspace.hypotheses.find(item=>item.id===focusTest?.hypothesisId)||nextHypothesis(workspace)
 const lastDecision=workspace.decisions.filter(item=>item.hypothesisId===focusHypothesis?.id).at(-1)
 const freshTest=!!focusHypothesis?.test.result.trim()&&lastDecision?.outcome==='Keep testing'
 const editableTest=testDraft||focusHypothesis||emptyTest
 const stages:[Stage,string,typeof Lightbulb][]=[['idea',t.idea,Lightbulb],['validate',t.validate,FlaskConical],['plan',t.plan,Scale],['apply',t.apply,FileText]]
 const stageStatus=(id:Stage)=>{const ar=language==='ar';if(id==='idea')return workspace.ideaReviewDecisions.length?(ar?'قرار محفوظ':'Decision saved'):artifacts.some(a=>a.stage==='idea'&&a.ideaReview)?(ar?'بانتظار قرارك':'Needs your decision'):(ar?'بانتظار المراجعة':'Needs critique');if(id==='validate')return lastDecision?(ar?'قرار مسجّل':'Decision recorded'):focusHypothesis?.test.result.trim()?(ar?'نتيجة مسجّلة':'Result recorded'):focusTest?(ar?'خطة اختبار':'Test planned'):(ar?'لم يبدأ الاختبار':'No test yet');if(id==='plan')return scenario.valid?(ar?'تقديرات متاحة':'Estimates entered'):(ar?'تقديرات ناقصة':'Needs estimates');return worksheets.length?(ar?'مسودة جاهزة':'Draft prepared'):(ar?'لم تُجهّز مسودة':'No draft yet')}
 const prompt=`Create an output-led ${stage} draft for my Kuwait business idea. Use my saved business context. ${stage==='idea'?'Challenge the idea candidly across customer need, differentiation, economics, feasibility and evidence. Score evidence readiness with reasons, give critical risks and realistic feature, expansion or pivot options. Do not call the score a success probability.':stage==='validate'?'Separate public context from actual customer results; identify the key untested assumption and propose one small customer experiment with editable hypothesis, method, audience and decision rule. Do not call it validation until a founder records a result.':stage==='plan'?'Use the saved test result and founder decision before planning. If no real result exists, mark the plan as exploratory. Show direction, competitors or alternatives, and a cost scenario with clearly labelled assumptions; do not mix budget with revenue.':'Show known, missing and pending application details; do not submit anything.'} Use relevant Kuwait sources and cite them. Clearly label assumptions and unknowns. Ask at most one essential question. Use the ${guidance.phases.join(' and ')} phases as preparation guidance, not official requirements. Reply in ${language==='ar'?'Arabic':'English'}.`
 async function saveChange(action:()=>unknown,done:()=>void=()=>{}){
  if(saving)return
  setSaving(true);setSaved(false);setSaveError('')
  try{const result=await action() as WriteResult|undefined;if(result?.ok){done();setSaved(true)}else if(result&&!result.ok)setSaveError(result.reason||'Saving failed. Your draft is still here.')}
  catch(e){setSaveError((e as Error).message)}finally{setSaving(false)}
 }
 function saveBrief(){if(brief.idea.trim())void saveChange(()=>onSaveBrief(brief))}
 function saveCosts(){void saveChange(()=>onSaveCosts(costs))}
 return <div className="founder-workbench" lang={language} dir={language==='ar'?'rtl':'ltr'}>
  {saveError&&<p role="alert">{saveError}</p>}{saving&&<p role="status">Saving…</p>}<div className="founder-workbench-top"><span className="founder-overline">{t.journey}</span><span className="founder-data-label">{demo?t.sample:t.local}</span></div>
  <nav className="founder-stages" aria-label={t.journey}>{stages.map(([id,label,Icon])=><button key={id} type="button" aria-current={stage===id?'step':undefined} className={stage===id?'active':''} onClick={()=>{onStageChange(id);setSaved(false)}}><span className="founder-stage-icon"><Icon size={16}/></span><span>{label}</span><small>{stageStatus(id)}</small></button>)}</nav>
  <div className="founder-workbench-scroll"><section className="founder-output">
   <div className="founder-output-heading"><span dir="ltr">{stage==='idea'?'01':stage==='validate'?'02':stage==='plan'?'03':'04'} / 04</span><h2>{stage==='idea'?t.ideaTitle:stage==='validate'?t.validateTitle:stage==='plan'?t.planTitle:t.applyTitle}</h2></div>
   <div className="founder-stage-purpose"><p>{language==='ar'?(stage==='idea'?'راجع نقاط الضعف والأدلة والخيارات قبل أن تختار اختبار الفكرة أو تعديلها أو إيقافها.':stage==='validate'?'اختر اختباراً صغيراً، نفّذه مع عملاء حقيقيين، ثم سجّل ما حدث وقرارك.':stage==='plan'?'استخدم ما تعلمته لتقدير السعر والتكاليف ونقطة التعادل.':'جهّز المعلومات والمستندات الناقصة وراجع المتطلبات لدى الجهة الرسمية.'):(stage==='idea'?'Challenge the weak points, review the evidence and compare options. Then choose: test, revise or park.':stage==='validate'?'Choose a small test, run it with real customers, then record what happened and decide what to change.':stage==='plan'?'Use what you learned to estimate price, costs and break-even. Check the assumptions before committing money.':'Prepare the missing details and documents. Verify the requirements with the relevant official service.')}</p><span>{language==='ar'?'المخرج المحفوظ: ':'Saved outcome: '}{language==='ar'?(stage==='idea'?'مراجعة الفكرة وقرارك':stage==='validate'?'خطة اختبار ونتيجة وقرار':stage==='plan'?'تقديرات وخطة قابلة للمراجعة':'مسودة تجهيز وقائمة النواقص'):(stage==='idea'?'critique + your decision':stage==='validate'?'test plan + observed result + decision':stage==='plan'?'cost scenario + reviewed plan':'preparation draft + missing information')}</span></div>
   {focusHypothesis&&evidenceNeedsReview(workspace,focusHypothesis)&&<p className="dukkan-research-gap" role="status">{language==='ar'?'تغيّرت الأدلة منذ القرار الأخير. راجع القرار قبل الاعتماد على هذه الخطة.':'Evidence has changed since the last decision. Review that decision before relying on this plan.'}</p>}
   {stage==='idea'&&draft?.ideaReview&&<IdeaReview key={draft.id} artifact={draft} language={language} decision={ideaChoice} onSave={(choice,reason,selectedOption,customOption)=>onSaveIdeaReview(draft,choice,reason,selectedOption,customOption)}/>}
   {stage==='idea'&&draft&&!draft.ideaReview&&<p className="founder-output-caveat">{language==='ar'?'هذه مسودة قديمة لا تتضمن مراجعة نقدية منظمة. يمكنك طلب مراجعة جديدة.':'This older draft has no structured critique. You can request a new review.'}</p>}
   {stage==='idea'&&!draft&&<div className="founder-record"><strong>{workspace.brief.idea||t.none}</strong>{workspace.brief.customer&&<p>{language==='ar'?'لمن: ':'For: '}{workspace.brief.customer}</p>}{workspace.brief.problem&&<p>{language==='ar'?'المشكلة: ':'Problem: '}{workspace.brief.problem}</p>}{workspace.brief.offer&&<p>{language==='ar'?'المنتج: ':'Offer: '}{workspace.brief.offer}</p>}</div>}
   {stage==='validate'&&draft?.proposedTest&&<TestProposal key={draft.id} artifact={draft} language={language} adopted={testAlreadyAdopted} onSave={proposal=>onAdoptTest(draft,proposal)}/>}
   {stage==='validate'&&!draft&&<div className="founder-record"><strong>{workspace.hypotheses[0]?.title|| (language==='ar'?'ما الافتراض الذي يجب اختباره؟':'Which assumption matters most?')}</strong><p>{workspace.evidence.length?`${workspace.evidence.length} ${language==='ar'?'ملاحظات محفوظة':'saved evidence notes'}`:language==='ar'?'لا يوجد دليل محفوظ بعد.':'No evidence saved yet.'}</p>{workspace.savedTests[0]&&<p>{language==='ar'?'الاختبار: ':'Test: '}{workspace.savedTests[0].title}</p>}</div>}
   {stage==='plan'&&!draft&&<div className="founder-record"><strong>{workspace.brief.offer|| (language==='ar'?'لم يُحدّد العرض بعد.':'The offer is not defined yet.')}</strong><p>{language==='ar'?'البدائل أو المنافسون: غير مدروسة بعد.':'Competitors or alternatives: not researched yet.'}</p></div>}
   {stage==='plan'&&<div className="founder-validation-bridge"><span>{language==='ar'?'ما الذي تعلّمته حتى الآن؟':'What validation has shown'}</span>{focusHypothesis?.test.result.trim()?<><strong>{lastDecision?.outcome|| (language==='ar'?'لم يُحفظ قرار بعد':'No decision saved yet')}</strong><p>{focusHypothesis.test.result}</p><small>{language==='ar'?'نتيجة أدخلها المؤسس، وليست تحققاً مستقلاً.':'Founder-reported result, not independent verification.'}</small></>:<><strong>{language==='ar'?'لا توجد نتيجة اختبار محفوظة':'No test result saved'}</strong><p>{language==='ar'?'عامل أي خطة هنا كسيناريو استكشافي حتى تسجّل ما حدث فعلاً.':'Treat any plan here as exploratory until you record what actually happened.'}</p></>}</div>}
   {stage==='plan'&&<div className="founder-cost-summary"><span>{t.costs}</span><strong>{scenario.valid&&scenario.breakEven!==null?`${scenario.breakEven} ${t.breakEven}`:language==='ar'?'أضف تقديراتك':'Add your estimates'}</strong><small>{t.notForecast}</small></div>}
   {stage==='apply'&&<div className="founder-record"><strong>{t.requirements}</strong><p>{t.noSubmit}</p>{worksheets.map(item=><button className="founder-worksheet" key={item.id} onClick={()=>onOpenArtifact(item)}><FileText size={17}/><span><strong>{item.title}</strong><small>{item.missingFields?.length?`${item.missingFields.length} ${language==='ar'?'حقول ناقصة':'missing fields'}`:language==='ar'?'راجع المسودة':'Review draft'}</small></span></button>)}</div>}
   {stage==='apply'&&onSaveSetup&&<SetupTracker items={workspace.setup} language={language} onSave={onSaveSetup}/>}
   {stage==='apply'?<Button className="founder-primary-action" disabled={stepsDisabled} onClick={onPrepareDraft}><FileText size={16}/>{t.draft}</Button>:<Button className="founder-primary-action" disabled={stepsDisabled} onClick={()=>onAskSteps(prompt,stage)}><MessageCircle size={16}/>{language==='ar'?(stage==='idea'?'اطلب مراجعة نقدية':stage==='validate'?'اقترح اختباراً للعملاء':'جهّز مسودة الخطة'):(stage==='idea'?(draft?'Request a fresh critique':'Get an idea critique'):stage==='validate'?'Suggest a customer test':'Draft a business plan')}</Button>}
   <details className="founder-guidance"><summary>{guidance.heading[language]}</summary><p>{language==='ar'?'إرشادات للتحضير، وليست متطلبات رسمية.':'Preparation guidance, not official requirements.'}</p><ol>{guidance.steps[language].map(item=><li key={item}>{item}</li>)}</ol><p><strong>{language==='ar'?'المعلومات اللازمة: ':'Information needed: '}</strong>{guidance.needed[language]}</p></details>
   {stage==='idea'&&<details className="founder-edit-details" open={focus==='reviseIdea'||focus==='revise'}><summary><PenLine size={15}/>{t.edit}</summary><form className="founder-form" onSubmit={event=>{event.preventDefault();saveBrief()}}>{([['idea',language==='ar'?'الفكرة':'The idea'],['customer',language==='ar'?'لمن':'Who it is for'],['problem',language==='ar'?'المشكلة':'Problem'],['offer',language==='ar'?'المنتج':'Offer']] as const).map(([field,label])=><label key={field}>{label}<textarea rows={2} dir="auto" value={brief[field]} onChange={event=>{setSaved(false);setBrief({...brief,[field]:event.target.value})}}/></label>)}<Button type="submit" disabled={saving||!brief.idea.trim()||JSON.stringify(brief)===JSON.stringify(workspace.brief)}><Check size={15}/>{t.save}</Button></form></details>}
   {(stage==='validate'||stage==='plan')&&onSaveEvidence&&<ResearchWorkflow key={focusHypothesis?.id||'unlinked'} workspace={workspace} hypothesis={focusHypothesis} language={language} artifacts={artifacts} onSave={onSaveEvidence} compact={stage==='plan'}/>}
   {stage==='validate'&&<div className="founder-validation-actions">
    <>{!onSaveEvidence&&<button onClick={onOpenEvidence}><Plus size={15}/>{t.note}</button>}</>
    {editableTest&&<details className="founder-edit-details" open={focus==='designTest'||!focusTest||freshTest}><summary><PenLine size={15}/>{freshTest?(language==='ar'?'صمّم الاختبار التالي':'Design the next test'):t.test}</summary><form className="founder-form" onSubmit={event=>{event.preventDefault();if(testDraft){void saveChange(()=>onSaveTest(testDraft),()=>setTestDraft(null))}}}>{freshTest&&<p>{language==='ar'?'هذا اختبار جديد. تبقى النتائج والقرارات السابقة محفوظة.':'This starts a new test. Earlier results and decisions stay saved.'}</p>}<label>{language==='ar'?'ما الافتراض الذي تختبره؟':'What are you testing?'}<textarea rows={2} value={editableTest.title} onChange={event=>{const current=testDraft||(freshTest?{...newHypothesis(focusHypothesis?.title||''),status:'Testing' as const}:editableTest);setTestDraft({...current,title:event.target.value})}}/></label>{(['method','audience','rule'] as const).map(field=><label key={field}>{language==='ar'?field==='method'?'الطريقة':field==='audience'?'من تسأل':'قاعدة القرار':field==='method'?'Method':field==='audience'?'Who to ask':'Decision rule'}<textarea rows={2} value={testDraft?testDraft.test[field]:freshTest?'':editableTest.test[field]} onChange={event=>{const current=testDraft||(freshTest?{...newHypothesis(focusHypothesis?.title||''),status:'Testing' as const}:editableTest);setTestDraft({...current,test:{...current.test,[field]:event.target.value}})}}/></label>)}<Button type="submit" disabled={saving||!testDraft?.title.trim()||!testDraft.test.method.trim()||!testDraft.test.audience.trim()||!testDraft.test.rule.trim()}><Check size={15}/>{t.test}</Button></form></details>}
    {focusTest&&focusHypothesis&&<details className="founder-edit-details" open={!focusHypothesis.test.result||focus==='recordResult'}><summary><FlaskConical size={15}/>{language==='ar'?'سجّل ما حدث':'Record what happened'}</summary><form className="founder-form" onSubmit={event=>{event.preventDefault();if(resultDraft.trim()){void saveChange(()=>onSaveResult({...focusHypothesis,test:{...focusHypothesis.test,result:resultDraft.trim()}}),()=>setResultDraft(''))}}}><p>{language==='ar'?'أضف ما لاحظته فعلاً، وليس ما توقعت حدوثه.':'Write what you actually observed, not what you expected.'}</p><label>{language==='ar'?'نتيجة الاختبار':'Test result'}<textarea rows={3} dir="auto" value={resultDraft} placeholder={focusHypothesis.test.result||''} onChange={event=>setResultDraft(event.target.value)}/></label><Button type="submit" disabled={saving||!resultDraft.trim()}><Check size={15}/>{t.save}</Button></form></details>}
    {focusHypothesis?.test.result.trim()&&<details className="founder-edit-details" open={!lastDecision||focus==='decide'||focus==='review'||evidenceNeedsReview(workspace,focusHypothesis)}><summary><Scale size={15}/>{language==='ar'?'حدّد الخطوة التالية':'Decide the next move'}</summary><form className="founder-form" onSubmit={event=>{event.preventDefault();if(decisionReason.trim()){void saveChange(()=>onRecordDecision(focusHypothesis,decisionOutcome,decisionReason.trim()),()=>setDecisionReason(''))}}}><p>{language==='ar'?'النتيجة ملاحظة أدخلتها أنت، وليست تحققاً مستقلاً.':'This result is your account, not independent verification.'}</p><label>{language==='ar'?'قرارك':'Your decision'}<select value={decisionOutcome} onChange={event=>setDecisionOutcome(event.target.value as Decision['outcome'])}>{(['Keep testing','Supported so far','Revise the idea','Pause the idea'] as const).map(outcome=><option key={outcome} value={outcome}>{language==='ar'?({'Keep testing':'واصل الاختبار','Supported so far':'مدعومة حتى الآن','Revise the idea':'عدّل الفكرة','Pause the idea':'أوقف الفكرة مؤقتاً'}[outcome]):outcome}</option>)}</select></label><label>{language==='ar'?'السبب':'Why'}<textarea rows={2} dir="auto" value={decisionReason} onChange={event=>setDecisionReason(event.target.value)}/></label><Button type="submit" disabled={saving||!decisionReason.trim()}><Check size={15}/>{language==='ar'?'احفظ القرار':'Save decision'}</Button></form></details>}
    {lastDecision&&<p className="founder-inline-success"><Check size={14}/>{language==='ar'?'آخر قرار: ':'Last decision: '}{lastDecision.outcome}</p>}
   </div>}
   {stage==='plan'&&<details className="founder-edit-details" open={!scenario.valid}><summary><PenLine size={15}/>{t.edit}</summary><form className="founder-form" onSubmit={event=>{event.preventDefault();saveCosts()}}>{([['price','Price per unit (KWD)'],['variable','Cost per unit (KWD)'],['fixed','Fixed costs per month (KWD)'],['units','Units per month']] as const).map(([field,label])=><label key={field}>{language==='ar'?({price:'سعر الوحدة (د.ك)',variable:'تكلفة الوحدة (د.ك)',fixed:'التكاليف الثابتة شهرياً (د.ك)',units:'عدد الوحدات شهرياً'}[field]):label}<input type="number" min="0" step={field==='units'?'1':'0.001'} value={costs[field]} onChange={event=>{setSaved(false);setCosts({...costs,[field]:event.target.value})}}/></label>)}<Button type="submit" disabled={JSON.stringify(costs)===JSON.stringify(workspace.costs)}><Check size={15}/>{t.save}</Button></form></details>}
   {draft?<details className="founder-stage-draft" open={false}><summary className="founder-draft-label"><BookOpen size={15}/><strong>{draft.title}</strong><small>{stage==='idea'&&draft.ideaReview?language==='ar'?'المسودة الكاملة':'Full brief':language==='ar'?'مسودة':'Draft'}</small></summary><div className="founder-draft-content" dir="auto">{draft.content?parseDraftSections(draft.content).map((section,index)=><section className="founder-draft-section" key={index}>{section.heading&&<h3>{section.heading}</h3>}{section.lines.map((line,i)=><p key={i}><DraftLine value={line}/></p>)}</section>):<p>{language==='ar'?'افتح المسودة لقراءة التفاصيل.':'Open the draft to read the details.'}</p>}</div>{!!draft.assumptions?.length&&<div className="founder-draft-list"><strong>{t.assumptions}</strong><ul>{draft.assumptions.map((item,index)=><li key={index}>{item}</li>)}</ul></div>}{!!draft.unknowns?.length&&<div className="founder-draft-list"><strong>{t.unknowns}</strong><ul>{draft.unknowns.map((item,index)=><li key={index}>{item}</li>)}</ul></div>}{!!draft.citations?.length&&<details className="founder-draft-sources"><summary>{t.sources} · {draft.citations.length}</summary><ul>{draft.citations.map((source,index)=>{const url=safeLink(source.url||source.sourceUrl);const label=String(source.title||source.label||`Source ${index+1}`);return <li key={index}>{url?<a href={url} target="_blank" rel="noopener noreferrer">{label}</a>:label}</li>})}</ul></details>}<Button variant="outline" onClick={()=>onOpenArtifact(draft)}><FileText size={15}/>{language==='ar'?'افتح المسودة':'Open draft'}</Button><p className="founder-output-caveat">{t.review}</p></details>:null}
   {saved&&<p className="founder-inline-success" role="status"><Check size={14}/>{language==='ar'?'تم الحفظ':'Saved'}</p>}
  </section></div>
 </div>
}
