import {useEffect,useState} from 'react'
import {z} from 'zod'
const schema=z.object({provenance:z.string(),leads:z.array(z.object({id:z.string(),name:z.string(),sourceURL:z.string().url(),checkedAt:z.string(),publicContact:z.string(),evidence:z.string(),fit:z.string(),qualificationGap:z.string(),draft:z.object({subject:z.string(),body:z.string()})}))})
export function PearlResearch({language,onDraft}:{language:'en'|'ar';onDraft:(prompt:string)=>void}){
 const tr=(en:string,ar:string)=>language==='ar'?ar:en
 const [data,setData]=useState<z.infer<typeof schema>|null>(null),[error,setError]=useState('')
 useEffect(()=>{const c=new AbortController();void fetch(new URL('demo/pearl-delta/leads-and-drafts.json',new URL(import.meta.env.BASE_URL,location.href)),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Research file unavailable');return r.json()}).then(raw=>{if(!c.signal.aborted)setData(schema.parse(raw))}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[])
 return <section className="pearl-research"><h2>{tr('Potential Kuwait partners','شركاء محتملون في الكويت')}</h2><p>{tr('Prepared externally by Codex. ','أُعدّ البحث خارج دكان بواسطة Codex. ')}{data?.provenance}</p>{error&&<p role="alert">{error}</p>}{data?.leads.map(lead=><details key={lead.id}><summary>{lead.name}<span>{tr('Researched · not contacted','تم البحث · لم يتم التواصل')}</span></summary><p>{lead.evidence}</p><p>{lead.qualificationGap}</p><a href={lead.sourceURL} target="_blank" rel="noreferrer">{tr('Public source · checked ','مصدر عام · تاريخ المراجعة ')}{lead.checkedAt}</a><p>{lead.publicContact}</p><h3>{lead.draft.subject}</h3><pre>{lead.draft.body}</pre>{/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(lead.publicContact)?<button onClick={()=>onDraft('Prepare a saved email draft only for this fictional demonstration. Do not send it. Recipient: '+lead.publicContact+'\nSubject: '+lead.draft.subject+'\nBody:\n'+lead.draft.body)}>{tr('Prepare this draft in chat','جهّز هذه المسودة في المحادثة')}</button>:<p>{tr('No verified email address. Use the source to qualify a contact first.','لا يوجد بريد إلكتروني متحقق منه. راجع المصدر لتحديد جهة الاتصال أولاً.')}</p>}</details>)}</section>
}
