import {useState} from 'react'
import {ArrowRight,Check,CheckCheck,FileText,Globe,Link2,LockKeyhole,Mail,MapPin,MessageSquare,MousePointer2,Search,ShieldCheck,Store,Users,WalletCards} from 'lucide-react'
import {Dialog,DialogContent,DialogDescription,DialogTitle} from './ui/dialog'
import './phase-previews.css'
import mociLogo from '../assets/official-routes/moci.png'
import sahelLogo from '../assets/official-routes/sahel.svg'
import sahelBusinessLogo from '../assets/official-routes/sahel-business.svg'

export type PhasePreviewId='marketplace'|'investors'|'funding'|'incubator'|'marketing'|'connectors'|'intelligence'|'simulation'|'email'|'browser'|'handoff'|'teams'|'languages'
type Props={id:PhasePreviewId;language:'en'|'ar'}
const names:Record<PhasePreviewId,[string,string]>={marketplace:['Service marketplace','سوق الخدمات'],investors:['Investor matching','التواصل مع المستثمرين'],funding:['Crowdfunding','التمويل الجماعي'],incubator:['Programme workspace','مساحة البرنامج'],marketing:['Campaign studio','استوديو الحملات'],connectors:['Business connections','ربط أنظمة الأعمال'],intelligence:['Local intelligence','المعلومات المحلية'],simulation:['Market scenarios','سيناريوهات السوق'],email:['Reviewed email','بريد للمراجعة'],browser:['Visible browser actions','إجراءات المتصفح الظاهرة'],handoff:['Official handoff','التسليم الرسمي'],teams:['Team workspace','مساحة الفريق'],languages:['Multilingual workspace','مساحة متعددة اللغات']}

function PreviewCanvas({id,language}:Props){
 const ar=language==='ar',tr=(en:string,arabic:string)=>ar?arabic:en
 const row=(label:string,detail:string,Icon=FileText)=><div className="phase-mock-row" key={label}><Icon size={17}/><div><strong>{label}</strong><small>{detail}</small></div></div>
 const lines=<div className="phase-mock-lines" aria-hidden="true"><i/><i/><i/></div>
 return <div className={'phase-mock phase-mock-'+id} dir={ar?'rtl':'ltr'}>
  <div className="phase-mock-bar"><span>DUKKAN</span><small>{tr('Future concept','تصور مستقبلي')}</small></div>
  <div className="phase-mock-content"><div className="phase-mock-title"><strong>{names[id][ar?1:0]}</strong><span>{tr('Preview','تصور')}</span></div>
   {id==='marketplace'&&<><div className="phase-mock-search"><Search size={14}/>{tr('Find support for your next step','ابحث عن دعم لخطوتك القادمة')}</div><div className="phase-mock-two">{row(tr('Design services','خدمات التصميم'),tr('Provider verification pending','التحقق من مقدم الخدمة معلق'),Store)}{row(tr('Business mentors','مرشدو الأعمال'),tr('Profile and criteria to review','ملف ومعايير للمراجعة'),Users)}</div></>}
   {id==='investors'&&<><div className="phase-mock-tags"><span>{tr('Sector','القطاع')}</span><span>{tr('Stage','المرحلة')}</span><span>{tr('Geography','الموقع')}</span></div>{row(tr('Match criteria','معايير المطابقة'),tr('Explain why a profile may fit','اشرح أسباب تطابق الملف'),Search)}{row(tr('Introduction draft','مسودة التعارف'),tr('Review before sharing','راجع قبل المشاركة'),MessageSquare)}</>}
   {id==='funding'&&<><div className="phase-mock-cover"><WalletCards size={28}/><strong>{tr('Campaign draft','مسودة حملة')}</strong></div><div className="phase-mock-two">{row(tr('Use of funds','استخدام الأموال'),tr('Budget to review','ميزانية للمراجعة'))}{row(tr('Milestones','المراحل'),tr('Evidence and delivery plan','الأدلة وخطة التنفيذ'))}</div></>}
   {id==='incubator'&&<div className="phase-mock-timeline">{row(tr('Application pack','ملف الانضمام'),tr('Prepared for review','معدّ للمراجعة'))}{row(tr('Mentor review','مراجعة المرشد'),tr('Feedback and next action','ملاحظات وخطوة تالية'),MessageSquare)}{row(tr('Milestone evidence','أدلة الإنجاز'),tr('Attach actual results','أرفق النتائج الفعلية'),CheckCheck)}</div>}
   {id==='marketing'&&<><div className="phase-mock-two"><div className="phase-mock-post"><div className="phase-mock-cover"><Globe size={23}/></div><strong>{tr('Campaign draft','مسودة حملة')}</strong>{lines}</div><div className="phase-mock-post"><small>{tr('Experiment plan','خطة تجربة')}</small><strong>{tr('Audience → message → review','جمهور ← رسالة ← مراجعة')}</strong>{lines}</div></div><div className="phase-mock-action">{tr('Review before publishing','راجع قبل النشر')}</div></>}
   {id==='connectors'&&<>{row(tr('Point of sale','نقطة البيع'),tr('Not connected','غير متصل'),Store)}{row(tr('Accounting','المحاسبة'),tr('Choose an authorised account','اختر حساباً مصرحاً به'),WalletCards)}<div className="phase-mock-action"><Link2 size={14}/>{tr('Review permissions','راجع الصلاحيات')}</div></>}
   {id==='intelligence'&&<div className="phase-mock-two"><div className="phase-mock-map" aria-hidden="true"><MapPin size={24}/><MapPin size={17}/><MapPin size={20}/></div><div>{row(tr('Location evidence','أدلة الموقع'),tr('Source · date · coverage','المصدر · التاريخ · التغطية'),MapPin)}{row(tr('Local updates','مستجدات محلية'),tr('Check freshness','راجع حداثة البيانات'),Search)}</div></div>}
   {id==='simulation'&&<><div className="phase-mock-tags"><span>{tr('Assumption A','افتراض أ')}</span><span>{tr('Assumption B','افتراض ب')}</span></div><svg className="phase-mock-chart" viewBox="0 0 320 96" role="img" aria-label={tr('Illustrative scenario curves, no forecast data','منحنيات توضيحية دون بيانات توقعات')}><path d="M15 10V80H310" stroke="#d6dfd8" fill="none"/><path d="M15 72C80 65 135 58 190 38S280 30 310 14" stroke="#204638" strokeWidth="3" fill="none"/><path d="M15 72C80 62 125 75 190 58S260 60 310 50" stroke="#b7a27d" strokeWidth="2" strokeDasharray="6 5" fill="none"/></svg><small>{tr('Illustration only. Simulation is not customer evidence.','توضيح فقط. المحاكاة ليست دليلاً من العملاء.')}</small></>}
   {id==='email'&&<><div className="phase-mock-mail"><Mail size={19}/><div><small>{tr('To: choose a recipient','إلى: اختر مستلماً')}</small><strong>{tr('Your reviewed document','مستندك بعد المراجعة')}</strong>{lines}</div></div><div className="phase-mock-two"><span className="phase-mock-chip"><FileText size={14}/>{tr('Exact reviewed version','النسخة المراجعة')}</span><span className="phase-mock-chip"><LockKeyhole size={14}/>{tr('Sender not connected','البريد غير متصل')}</span></div></>}
   {id==='browser'&&<><div className="phase-mock-browser">https://<span>{tr('selected official website','الموقع الرسمي المختار')}</span><ShieldCheck size={14}/></div>{row(tr('Open the selected page','افتح الصفحة المختارة'),tr('Visible action log','سجل إجراءات ظاهر'),MousePointer2)}{row(tr('Review the next action','راجع الإجراء التالي'),tr('Approval before consequential steps','موافقة قبل الخطوات المؤثرة'),ShieldCheck)}</>}
   {id==='handoff'&&<><OfficialRouteMarks language={language}/>{row(tr('Source check','فحص المصادر'),tr('Eligibility remains to be checked','الأهلية تتطلب التحقق'),Search)}{row(tr('Reviewed document pack','حزمة مستندات مراجعة'),tr('Prepared · not submitted','معدّة · لم تُقدّم'))}{row(tr('Official receipt','الإيصال الرسمي'),tr('Only after actual submission','بعد تقديم فعلي فقط'),ShieldCheck)}</>}
   {id==='teams'&&<><div className="phase-mock-roles">{[tr('Owner','المالك'),tr('Editor','محرر'),tr('Viewer','مشاهد')].map((role,index)=><div key={role}><span><Users size={17}/></span><strong>{role}</strong><small>{tr('Proposed role','دور مقترح')} {index+1}</small></div>)}</div>{row(tr('Shared business context','سياق مشروع مشترك'),tr('Permissions and activity history','الصلاحيات وسجل النشاط'),LockKeyhole)}</>}
   {id==='languages'&&<><div className="phase-mock-two"><div className="phase-mock-language"><small>English</small><strong>Your business idea</strong>{lines}</div><div className="phase-mock-language" dir="rtl"><small>العربية</small><strong>فكرة مشروعك</strong>{lines}</div></div><div className="phase-mock-action"><Globe size={14}/>{tr('Translation quality review','مراجعة جودة الترجمة')}</div></>}
  </div><div className="phase-mock-foot"><LockKeyhole size={11}/>{tr('Design preview · no connected service','تصور تصميم · لا توجد خدمة متصلة')}</div>
 </div>
}

export function PhaseDesignPreview({id,language}:Props){
 const [open,setOpen]=useState(false),ar=language==='ar'
 return <><button className="phase-preview-open" aria-label={(ar?'شاهد تصميم ':'View design: ')+names[id][ar?1:0]} onClick={()=>setOpen(true)}><PreviewCanvas id={id} language={language}/><span>{ar?'افتح التصور':'Explore design'}<ArrowRight size={14}/></span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="phase-design-dialog" dir={ar?'rtl':'ltr'}><DialogTitle>{names[id][ar?1:0]}</DialogTitle><DialogDescription>{ar?'تصور لميزة مخططة، دون خدمات متصلة أو إجراءات فعلية.':'A design representation of a planned feature. No service is connected and no action is executed.'}</DialogDescription><PreviewCanvas id={id} language={language}/></DialogContent></Dialog></>
}

export function FundingDesign({language,imageUrl}:{language:'en'|'ar';imageUrl?:string}){
 const ar=language==='ar',tr=(en:string,arabic:string)=>ar?arabic:en
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'campaign'|'readiness'|'handoff'>('campaign')
 const tabs=[['campaign',tr('Campaign','الحملة')],['readiness',tr('Readiness','الاستعداد')],['handoff',tr('Provider handoff','التسليم للجهة')]] as const
 return <section className="phase-funding-feature" aria-labelledby="funding-concept-title"><div><span className="dukkan-kicker">{tr('A closer look','نظرة أقرب')}</span><h2 id="funding-concept-title">{tr('Crowdfunding, from idea to campaign','التمويل الجماعي، من الفكرة إلى الحملة')}</h2><p>{tr('Shape the story, connect the evidence and budget, then review a provider route before any launch.','جهّز قصة المشروع واربط الأدلة والميزانية، ثم راجع مسار الجهة قبل إطلاق أي حملة.')}</p><span className="phase-concept-label">{tr('Future design · no live campaign','تصور مستقبلي · لا توجد حملة فعلية')}</span><button className="phase-concept-primary" onClick={()=>{setTab('campaign');setOpen(true)}}>{tr('Explore crowdfunding design','استكشف تصميم التمويل الجماعي')}<ArrowRight size={16}/></button></div><button className="phase-funding-image" aria-label={tr('Enlarge crowdfunding concept image','تكبير صورة تصور التمويل الجماعي')} onClick={()=>{setTab('campaign');setOpen(true)}}>{imageUrl?<img src={imageUrl} alt={tr('Dukkan crowdfunding preparation concept: campaign draft, readiness checks and provider handoff','تصور دكان لإعداد حملة تمويل جماعي وفحص الاستعداد والتسليم للجهة')} loading="lazy"/>:<PreviewCanvas id="funding" language={language}/>}</button>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="phase-design-dialog phase-funding-dialog" dir={ar?'rtl':'ltr'}><DialogTitle>{tr('Crowdfunding design preview','تصور تصميم التمويل الجماعي')}</DialogTitle><DialogDescription>{tr('Explore the proposed preparation flow. No campaign is live, no provider is connected and no funds are collected.','استكشف مسار الإعداد المقترح. لا توجد حملة فعلية أو جهة متصلة، ولا تُجمع أموال.')}</DialogDescription><div className="phase-design-tabs" role="tablist" aria-label={tr('Crowdfunding preparation steps','خطوات إعداد التمويل الجماعي')}>{tabs.map(([id,label])=><button key={id} role="tab" id={'funding-tab-'+id} aria-selected={tab===id} aria-controls={'funding-design-'+id} onClick={()=>setTab(id)}>{label}</button>)}</div><div role="tabpanel" id={'funding-design-'+tab} aria-labelledby={'funding-tab-'+tab}>
   {tab==='campaign'&&<>{!imageUrl&&<PreviewCanvas id="funding" language={language}/>} {imageUrl&&<img className="phase-funding-full-image" src={imageUrl} alt={tr('Crowdfunding campaign preparation screen concept','تصور شاشة إعداد حملة تمويل جماعي')}/>}<div className="phase-design-steps"><span><FileText size={18}/>{tr('Story and evidence','قصة المشروع والأدلة')}</span><span><WalletCards size={18}/>{tr('Budget and use of funds','الميزانية واستخدام الأموال')}</span><span><Check size={18}/>{tr('Delivery milestones','مراحل التنفيذ')}</span></div></>}
   {tab==='readiness'&&<div className="phase-funding-readiness">{[[tr('Customer evidence','أدلة العملاء'),tr('Attach real test results; identify assumptions.','أرفق نتائج الاختبارات الفعلية وحدد الافتراضات.')],[tr('Funding goal','هدف التمويل'),tr('Derive it from a reviewed budget and delivery plan.','استمده من ميزانية وخطة تنفيذ مراجعتين.')],[tr('Campaign route','مسار الحملة'),tr('Check the provider, permissions and route requirements.','تحقق من الجهة والصلاحيات ومتطلبات المسار.')],[tr('Founder review','مراجعة المؤسس'),tr('Review wording, promises and documents before handoff.','راجع النص والالتزامات والمستندات قبل التسليم.')]].map(([title,detail])=><div key={title}><ShieldCheck size={19}/><strong>{title}</strong><p>{detail}</p><small>{tr('Planned review step','خطوة مراجعة مقترحة')}</small></div>)}</div>}
   {tab==='handoff'&&<div className="phase-funding-handoff"><div className="phase-design-steps"><span><FileText size={20}/>{tr('Reviewed pack','حزمة مراجعة')}</span><ArrowRight size={19}/><span><Search size={20}/>{tr('Provider route check','فحص مسار الجهة')}</span><ArrowRight size={19}/><span><ShieldCheck size={20}/>{tr('Founder approval','موافقة المؤسس')}</span></div><p>{tr('The proposed Dukkan workflow prepares the campaign and records a handoff. A launch or collection of funds would happen only through a connected, authorised route with its own requirements.','مسار دكان المقترح يجهّز الحملة ويسجل التسليم. إطلاق الحملة أو جمع الأموال يتم عبر مسار مصرح ومتصل وفق متطلباته.')}</p><button disabled>{tr('Provider integration planned','الربط بالجهة مخطط')}</button></div>}
  </div></DialogContent></Dialog>
 </section>
}

export function OfficialRouteMarks({language}:{language:'en'|'ar'}){const ar=language==='ar';return <div className="phase-official-routes"><div className="phase-route-marks">{[[mociLogo,'MOCI','https://www.moci.gov.kw/en/e-service/kuwait-business-center/'],[sahelLogo,'Sahel','https://www.e.gov.kw/sites/kgoarabic/Pages/ApplicationPages/Application-Sahel.aspx'],[sahelBusinessLogo,'Sahel Business','https://www.e.gov.kw/sites/kgoarabic/Pages/ApplicationPages/Application-Sahel-Business.aspx']].map(([image,label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer"><img src={image} alt={label}/><span>{label}</span></a>)}</div><small>{ar?'وجهات رسمية مقترحة. الربط مخطط؛ لا شراكة أو تقديم فعلي.':'Proposed official destinations. Integration planned; no partnership or submission.'}</small></div>}
