import {useState} from 'react'
import {BookOpen,Download,Plus,Users} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {download,today,uid,type Evidence,type Hypothesis,type Workspace} from '@/lib/workspace'
import {evidenceOrigin,evidenceReport,evidenceSummary,researchPack,researchQuestions} from '@/lib/research'
import {safeLink} from '@/lib/preparation-api'
import type {WriteResult} from '@/lib/workspace-writer'
import {sourceCaveats,type ChatArtifact} from '@/lib/chat-api'

type Props={workspace:Workspace;hypothesis?:Hypothesis;language:'en'|'ar';artifacts:ChatArtifact[];onSave:(note:Evidence)=>Promise<WriteResult>;compact?:boolean}
export function ResearchWorkflow({workspace,hypothesis:h,language,artifacts,onSave,compact=false}:Props){
 const ar=language==='ar',[collect,setCollect]=useState(false),[pack,setPack]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const fresh=():Evidence=>({id:uid(),hypothesisId:h?.id||'',kind:'Customer conversation',origin:'unclassified',text:'',source:'',date:today(),signal:'Unclear',limitation:''})
 const [note,setNote]=useState<Evidence>(fresh)
 const notes=workspace.evidence.filter(n=>n.hypothesisId===h?.id),summary=evidenceSummary(notes)
 const citations=artifacts.flatMap(a=>a.citations||[]).filter((c,i,all)=>all.findIndex(other=>String(other.url||other.sourceUrl||other.title)===String(c.url||c.sourceUrl||c.title))===i)
 async function save(event:React.FormEvent){event.preventDefault();if(!h||busy)return;setBusy(true);setError('');try{const result=await onSave({...note,hypothesisId:h.id,text:note.origin==='simulated'&&!/^SIMULATED:/i.test(note.text)?'SIMULATED: '+note.text:note.text});if(result.ok){setCollect(false);setNote(fresh())}else setError(result.reason||'Could not save. Your entry is still here.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="dukkan-research" aria-label={ar?'أدلة العملاء':'Customer evidence'}>
  <div className="dukkan-research-heading"><div><span className="dukkan-kicker">{ar?'من الافتراض إلى الدليل':'From assumption to evidence'}</span><h3>{ar?'ماذا قال العملاء وفعلوا؟':'What did customers say and do?'}</h3></div><Users size={22}/></div>
  <p>{ar?'سجّل ما جمعته بنفسك. تُعرض أبحاث السوق والمحاكاة منفصلة عن ملاحظات العملاء.':'Record evidence you collected. Public research and simulations remain separate from customer observations.'}</p>
  <div className="dukkan-evidence-counts"><span><strong>{summary.direct}</strong>{ar?'ملاحظات مباشرة':'Direct notes'}</span><span><strong>{summary.challenges}</strong>{ar?'ملاحظات معارضة':'Challenging notes'}</span><span><strong>{summary.simulated}</strong>{ar?'محاكاة':'Simulated notes'}</span></div>
  <p className="dukkan-research-caveat">{ar?'الأعداد للملاحظات وليست لأشخاص مختلفين أو نسبة نجاح. الملاحظات المباشرة مصنّفة من المؤسس ولم تُتحقق مستقلاً.':'Counts are notes, not unique people or a success rate. Direct notes are classified by the founder, not independently verified.'}{summary.unclassified>0&&` ${summary.unclassified} ${ar?'ملاحظات قديمة غير مصنّفة.':'older notes have no origin classification.'}`}</p>
  {!h?<p>{ar?'احفظ افتراضاً أو اختباراً أولاً لربط الأدلة به.':'Save an assumption or test first so evidence can be linked to it.'}</p>:<>
   <p><strong>{ar?'مرتبط بـ: ':'Evidence for: '}</strong>{h.title}</p><div className="dukkan-research-actions">{!compact&&<Button variant="outline" onClick={()=>setPack(!pack)}><BookOpen size={16}/>{ar?'جهّز بحث العملاء':'Prepare customer research'}</Button>}<Button onClick={()=>{setNote(fresh());setCollect(true);setError('')}}><Plus size={16}/>{ar?'سجّل ملاحظة عميل':'Record customer evidence'}</Button><Button variant="ghost" onClick={()=>download(evidenceReport(workspace,h),'dukkan-decision-record.md','text/markdown')}><Download size={16}/>{ar?'صدّر سجل القرار':'Export decision record'}</Button></div>
   {pack&&<div className="dukkan-research-pack"><h4>{ar?'حزمة البحث لهذا الاختبار':'Research pack for this test'}</h4><strong>{h.title}</strong><p>{ar?'من تسأل: ':'Who to approach: '}{h.test.audience||workspace.brief.customer|| (ar?'لم يُحدد بعد':'Not defined yet')}</p><p>{ar?'قاعدة القرار: ':'Decision rule: '}{h.test.rule|| (ar?'حددها قبل جمع الردود':'Set this before collecting responses')}</p><ol>{researchQuestions(workspace,ar).map(q=><li key={q}>{q}</li>)}</ol><p>{ar?'تواصل مع أشخاص من الفئة المحددة عبر قنواتك أو جهات تسمح بالبحث. اطلب المشاركة طوعياً وسجّل الملاحظات بمراجع مجهولة.':'Reach people in the defined audience through your own channels or venues that permit research. Ask for voluntary participation and use anonymous references.'}</p><Button variant="outline" onClick={()=>download(researchPack(workspace,h,ar),'dukkan-customer-research.md','text/markdown')}><Download size={16}/>{ar?'نزّل الدعوة والأسئلة':'Download invitation and questions'}</Button><small>{ar?'تراجع الدعوة وترسلها بنفسك. لا توجد شبكة مشاركين متصلة أو دعوات مرسلة تلقائياً.':'Review and send the invitation yourself. No participant network is connected and no invitations are sent automatically.'}</small></div>}
   {collect&&<form className="founder-form dukkan-research-form" onSubmit={save}><h4>{ar?'ملاحظة مرتبطة بالاختبار':'Evidence linked to this test'}</h4><label>{ar?'مصدر الملاحظة':'Evidence origin'}<select required value={note.origin} onChange={e=>setNote({...note,origin:e.target.value as Evidence['origin']})}><option value="unclassified" disabled>{ar?'اختر المصدر':'Choose an origin'}</option><option value="real">{ar?'ملاحظة حقيقية أدخلها المؤسس':'Real observation reported by founder'}</option><option value="simulated">{ar?'مثال أو محاكاة':'Example or simulation'}</option></select></label><label>{ar?'النوع':'Kind'}<select value={note.kind} onChange={e=>setNote({...note,kind:e.target.value as Evidence['kind']})}>{(['Customer conversation','Observation','Published source','Assumption'] as const).map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></label><label>{ar?'ما الذي قاله أو فعله الشخص فعلاً؟':'What did the person actually say or do?'}<textarea required maxLength={11000} rows={3} value={note.text} onChange={e=>setNote({...note,text:e.target.value})}/></label><label>{ar?'مرجع مجهول أو رابط المصدر':'Anonymous reference or source link'}<input required maxLength={500} placeholder={ar?'مثلاً: المقابلة 01':'For example: Interview 01'} value={note.source} onChange={e=>setNote({...note,source:e.target.value})}/></label><label>{ar?'تاريخ الملاحظة':'Observation date'}<input type="date" required max={today()} value={note.date} onChange={e=>setNote({...note,date:e.target.value})}/></label><label>{ar?'علاقتها بالافتراض':'How does it affect the assumption?'}<select value={note.signal} onChange={e=>setNote({...note,signal:e.target.value as Evidence['signal']})}><option value="Supports">{ar?'يدعم':'Supports'}</option><option value="Challenges">{ar?'يعارض':'Challenges'}</option><option value="Unclear">{ar?'غير واضح':'Unclear'}</option></select></label><label>{ar?'القيود أو التفسير البديل':'Limitations or alternative explanation'}<textarea rows={2} maxLength={2000} value={note.limitation} onChange={e=>setNote({...note,limitation:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<div className="dukkan-research-actions"><Button type="submit" disabled={busy||note.origin==='unclassified'||!note.text.trim()||!note.source.trim()}>{busy?(ar?'جارٍ الحفظ':'Saving…'):(ar?'احفظ الدليل':'Save evidence')}</Button><Button variant="ghost" type="button" disabled={busy} onClick={()=>setCollect(false)}>{ar?'إلغاء':'Cancel'}</Button></div></form>}
  </>}
  {summary.direct===0&&<p className="dukkan-research-gap">{ar?'لم تُسجّل ملاحظات مباشرة مصنّفة كحقيقية لهذا الاختبار. أي استنتاج عن الطلب يظل افتراضاً.':'No direct notes are classified as real for this test. Any demand conclusion remains an assumption.'}</p>}
  {notes.length>0&&<details className="dukkan-evidence-ledger"><summary>{ar?'سجل الأدلة':'Evidence ledger'} · {notes.length}</summary>{notes.map(n=><article key={n.id}><header><strong>{n.source||n.kind}</strong><span>{evidenceOrigin(n)} · {n.signal}</span></header><p dir="auto">{n.text}</p><button className="dukkan-evidence-edit" onClick={()=>{setNote({...n,origin:n.origin||'unclassified'});setCollect(true);setError('')}}>{ar?'راجع الملاحظة':'Review note'}</button><small>{n.date}{n.limitation?' · '+n.limitation:''}</small></article>)}</details>}
  {citations.length>0&&<details className="dukkan-evidence-ledger"><summary>{ar?'السياق العام من المصادر':'Public research context'} · {citations.length}</summary><p>{ar?'هذه المصادر لا تثبت الطلب على مشروعك. راجع تاريخ المعلومة ونطاقها.':'These sources do not establish demand for your business. Check the observation date and scope.'}</p>{citations.map((c,i)=>{const url=safeLink(c.url||c.sourceUrl);return <article key={i}>{url?<a href={url} target="_blank" rel="noopener noreferrer">{String(c.title||c.label||'Source')}</a>:String(c.title||c.label||'Source')}<small>{ar?'فترة البيانات: ':'Data period: '}{String(c.dataPeriod||c.publicationDate||(ar?'غير مذكورة':'Not stated'))}</small><small>{ar?'تاريخ جمع المصدر: ':'Source captured: '}{String(c.capturedAt||'').slice(0,10)||(ar?'غير مذكور':'Not stated')}</small>{sourceCaveats(c.limitations).map(note=><small key={note}>{note}</small>)}</article>})}</details>}
 </section>
}
