import {createSiliconFlowModel,siliconflowConfig} from '../src/siliconflow.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createApp} from '../src/server.ts';
import {createChatModel} from '../src/chat-model.ts';
import {hash} from '../contracts/index.ts';
import {executeTool} from '../tools/index.ts';
import type {ChatModel} from '../contracts/chat.ts';
import type {ToolExecutor} from '../contracts/index.ts';
const cite={id:'source-test',title:'Captured setup guidance',url:'https://www.moci.gov.kw/',excerpt:'Contact the authority to clarify the applicable route.'};
const fakeTools:ToolExecutor=async(call,ctx)=>({ok:true,provenance:[],data:call.name==='prepare_enquiry'?{title:'Neutral draft',html:'<!doctype html><meta charset="utf-8"><h1>Neutral enquiry</h1><p>Unknown legal form. Not sent.</p>',body:String((call.arguments.fields as any)?.userRequest),citations:[cite],missingFields:['legal_form']}: {query:call.arguments.query,citations:[cite],sources:[cite],activationState:'inactive',blockers:[],requirements:[]}});
async function harness(t:any,chatModel?:ChatModel,executor=fakeTools){const root=mkdtempSync(resolve(tmpdir(),'dikan-chat-'));let app=await createApp({allowDeterministicTests:true,expireCases:true,privateRoot:root,chatModel,executor});async function listen(){await new Promise<void>(r=>app.server.listen(0,'127.0.0.1',r));}await listen();t.after(async()=>{await new Promise<void>(r=>app.server.close(()=>r()));rmSync(root,{recursive:true,force:true});});let n=0;async function api(path:string,method='GET',data?:any,key?:string){const r=await fetch(`http://127.0.0.1:${(app.server.address() as any).port}${path}`,{method,headers:{'Content-Type':'application/json','Idempotency-Key':key||`test-${++n}`},...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};}async function done(id:string){for(let i=0;i<250;i++){const r=await api(`/api/chat/turns/${id}`);if(!['queued','running'].includes(r.data.turn.status))return r.data;await new Promise(r=>setTimeout(r,10));}throw Error('turn timed out');}async function restart(){await new Promise<void>(r=>app.server.close(()=>r()));app=await createApp({allowDeterministicTests:true,expireCases:true,privateRoot:root,chatModel,executor});await listen();}return {api,done,restart,root,get app(){return app;}};}
test('actual chat HTTP lifecycle, explicit test label, review bytes, isolation, restart, expiry and idempotency',async t=>{const h=await harness(t);const a=await h.api('/api/conversations','POST',{title:'Pearl North'});const id=a.data.conversation.id;const initial=await h.api(`/api/conversations/${id}`);assert.deepEqual(initial.data.case.facts,[]);const other=(await h.api('/api/conversations','POST',{title:'Other'})).data.conversation;const path=`/api/conversations/${id}/messages`;const started=await h.api(path,'POST',{content:'Please draft an enquiry about my digital marketing studio',executionMode:'deterministic'},'same');assert.equal(started.status,202);assert.equal((await h.api(path,'POST',{content:'Please draft an enquiry about my digital marketing studio',executionMode:'deterministic'},'same')).data.turn.id,started.data.turn.id);assert.equal((await h.api(path,'POST',{content:'different',executionMode:'deterministic'},'same')).status,409);const settled=await h.done(started.data.turn.id);assert.equal(settled.turn.status,'completed');assert.match(settled.turn.label,/test mode/);assert.equal(settled.messages.at(-1).citations[0].id,cite.id);assert.deepEqual(settled.turn.events.map((e:any)=>e.type),['tool_started','tool_completed','tool_started','tool_completed','tool_started','tool_completed']);const artifact=settled.artifacts[0];assert.equal((await h.api(artifact.exportUrl)).status,409);assert.equal((await h.api(artifact.reviewUrl,'POST',{hash:'wrong',actor:'Tester',acknowledgeDraft:true})).status,409);assert.equal((await h.api(artifact.reviewUrl,'POST',{hash:artifact.hash,actor:'Tester',acknowledgeDraft:true})).status,200);assert.equal(hash((await h.api(artifact.exportUrl)).data),artifact.hash);await h.restart();assert.equal((await h.api(`/api/conversations/${id}`)).data.messages.length,2);assert.equal((await h.api(`/api/conversations/${other.id}`)).data.messages.length,0);const limit=await h.api(path,'POST',{content:'Send that enquiry to the official contact now.',executionMode:'deterministic'});const stopped=await h.done(limit.data.turn.id);assert.match(stopped.messages.at(-1).content,/cannot send email/);assert.equal(stopped.artifacts.length,0);const facts=[{field:'business.name',value:'Pearl North',origin:'founder',sourceRef:null,confirmedBy:'Tester',confirmedAt:new Date().toISOString()}];assert.equal((await h.api(`/api/conversations/${id}/facts`,'POST',{expectedRevision:1,facts})).status,200);assert.equal((await h.api(artifact.exportUrl)).status,409);const c=h.app.store.get('case',other.caseId);c.expiresAt='2000-01-01T00:00:00Z';h.app.store.put('case',c.businessId,c.businessId,c);assert.equal((await h.api(`/api/conversations/${other.id}`)).status,404);});
test('model receives previous conversation and confirmed facts; proposals do not mutate facts',async t=>{const contexts:any[]=[];const model:ChatModel={name:'test',version:'stub',async respond(input){contexts.push(structuredClone(input.messages));const last=input.messages.at(-1);if(last.role==='user'&&last.content.includes('correct'))return {content:'',calls:[{name:'propose_facts',arguments:{facts:[{field:'premises.unit',value:'12'}]}}],usage:{test:true}};if(last.role==='user')return {content:'',calls:[{name:'retrieve_guidance',arguments:{query:last.content}}],usage:{test:true}};return {content:'The source is captured and applicability needs confirmation.',calls:[],usage:{test:true}};}};const h=await harness(t,model);const c=(await h.api('/api/conversations','POST',{})).data.conversation;const path=`/api/conversations/${c.id}/messages`;const first=await h.api(path,'POST',{content:'My studio is Pearl North, no legal form chosen',executionMode:'live_agent'});await h.done(first.data.turn.id);const next=await h.api(path,'POST',{content:'Please correct premises unit to 12',executionMode:'live_agent'});const result=await h.done(next.data.turn.id);assert.equal(result.turn.status,'needs_input');assert.deepEqual(result.case.facts,[]);assert.ok(contexts.at(-1).some((m:any)=>m.content.includes('Pearl North')));const action=result.messages.at(-1).actions[0];assert.equal(action.payload.facts[0].confirmedBy,null);assert.equal((await h.api(action.endpoint,'POST',action.payload)).status,400);assert.equal(h.app.store.all('chat_message',c.caseId).length,4);});
test('busy turns are rejected and unavailable model failures persist without fallback',async t=>{let release!:()=>void;const wait=new Promise<void>(r=>release=r);const model:ChatModel={name:'test',version:'stub',async respond(){await wait;throw Error('offline');}};const h=await harness(t,model);const c=(await h.api('/api/conversations','POST',{})).data.conversation;const path=`/api/conversations/${c.id}/messages`;const first=await h.api(path,'POST',{content:'Research setup',executionMode:'live_agent'});assert.equal((await h.api(path,'POST',{content:'Concurrent',executionMode:'live_agent'})).data.error.code,'TURN_BUSY');release();const failed=await h.done(first.data.turn.id);assert.equal(failed.turn.status,'failed');assert.equal(failed.turn.executionMode,'live_agent');assert.equal(failed.artifacts.length,0);assert.equal(failed.turn.events.at(-1).type,'error');});
test('native chat adapter strips thinking, keeps only usage and fails visibly when offline',async()=>{let request:any;const model=createChatModel({fetch:(async(_url:any,init:any)=>{request=JSON.parse(init.body);return new Response(JSON.stringify({done:true,message:{content:'<think>private reasoning</think>Visible answer',thinking:'secret',tool_calls:[]},eval_count:8}));}) as any});const r=await model.respond({messages:[{role:'user',content:'Hello'}],tools:[],signal:new AbortController().signal});assert.equal(request.think,false);assert.equal(r.content,'Visible answer');assert.ok(!JSON.stringify(r).includes('private reasoning'));const offline=createChatModel({fetch:(async()=>{throw Error('offline');}) as any});await assert.rejects(()=>offline.respond({messages:[],tools:[],signal:new AbortController().signal}),{code:'MODEL_UNAVAILABLE'});});
test('case deletion during a tool cannot resurrect the conversation or its messages',async t=>{let release!:()=>void;let entered!:()=>void;const waiting=new Promise<void>(r=>release=r);const inTool=new Promise<void>(r=>entered=r);const h=await harness(t,undefined,async(call,ctx)=>{entered();await waiting;return fakeTools(call,ctx);});const c=(await h.api('/api/conversations','POST',{})).data.conversation;const started=await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'Kuwait licence route',executionMode:'deterministic'});await inTool;assert.equal((await h.api(`/api/cases/${c.caseId}`,'DELETE')).status,200);release();for(let i=0;i<50&&h.app.chat.active.size;i++)await new Promise(r=>setTimeout(r,10));assert.equal(h.app.chat.active.size,0);assert.equal(h.app.store.get('chat_turn',started.data.turn.id),null);assert.equal(h.app.store.all('chat_message',c.caseId).length,0);});
test('saved draft finishes with a short canonical-file acknowledgement and no redundant inference',async t=>{let calls=0;const model:ChatModel={name:'test',version:'stub',async respond(){calls++;assert.ok(calls<=2,'No third synthesis call after saved draft');return {content:'',calls:[calls===1?{name:'retrieve_guidance',arguments:{query:'Kuwait studio route'}}:{name:'prepare_enquiry',arguments:{kind:'route-clarification',language:'en'}}],usage:{test:true}};}};const h=await harness(t,model);const c=(await h.api('/api/conversations','POST',{})).data.conversation;const start=await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'Prepare a sourced enquiry draft',executionMode:'live_agent'});const result=await h.done(start.data.turn.id);assert.equal(result.turn.status,'completed');assert.equal(calls,2);assert.equal(result.artifacts.length,1);assert.match(result.messages.at(-1).content,/Open the saved file/);assert.ok(result.messages.at(-1).content.length<200);assert.equal(hash((await h.api(result.artifacts[0].previewUrl)).data),result.artifacts[0].hash);});
test('draft fields use attributed prior user text, reject invention, and never confirm case facts',async t=>{let proposal={business_name:'Pearl North',activity_description:'graphic design studio'};let received:any;const model:ChatModel={name:'test',version:'stub',async respond({messages}){return {content:'',calls:[messages.at(-1).role==='tool'?{name:'prepare_enquiry',arguments:{kind:'route-clarification',fields:proposal}}:{name:'retrieve_guidance',arguments:{query:'licence route'}}],usage:{test:true}};}};const h=await harness(t,model,async(call,ctx)=>{if(call.name==='prepare_enquiry')received=call.arguments;return fakeTools(call,ctx);});const c=(await h.api('/api/conversations','POST',{})).data.conversation;const path=`/api/conversations/${c.id}/messages`;await h.done((await h.api(path,'POST',{content:'Pearl North is a graphic design studio',executionMode:'deterministic'})).data.turn.id);const result=await h.done((await h.api(path,'POST',{content:'Draft using the business details I gave earlier',executionMode:'live_agent'})).data.turn.id);assert.equal(result.turn.status,'completed');assert.deepEqual(received.fields,proposal);assert.ok(!('userRequest' in received.fields));assert.deepEqual(result.case.facts,[]);assert.equal(result.artifacts[0].draftInputs[0].origin,'unconfirmed_user_statement');const origin=h.app.store.get('chat_message',result.artifacts[0].draftInputs[0].messageId);assert.match(origin.content,/Pearl North/);proposal={business_name:'Invented name',activity_description:'graphic design studio'};const invalid=await h.done((await h.api(path,'POST',{content:'Make another draft',executionMode:'live_agent'})).data.turn.id);assert.equal(invalid.turn.status,'completed');assert.equal(invalid.artifacts[0].draftIssues[0].code,'UNSUPPORTED_DRAFT_FIELD');assert.equal(invalid.artifacts[0].draftIssues[0].field,'business_name');assert.equal(invalid.artifacts[0].draftInputs.some((d:any)=>d.field==='business_name'),false);assert.deepEqual(invalid.case.facts,[]);});
test('application fills previous user details, versions later answers and keeps private tool arguments out of API',async t=>{
 let fields:any={business_name:'PEARL NORTH',activity_description:'Graphic Design Studio'};
 const model:ChatModel={name:'test',version:'stub',async respond({messages}){return {content:'',calls:[messages.at(-1).role==='tool'?{name:'prepare_application',arguments:{fields}}:{name:'retrieve_guidance',arguments:{query:'business setup'}}],usage:{test:true}};}};
 const h=await harness(t,model,executeTool);
 const c=(await h.api('/api/conversations','POST',{})).data.conversation;const path=`/api/conversations/${c.id}/messages`;
 await h.done((await h.api(path,'POST',{content:'Pearl North is a graphic design studio',executionMode:'deterministic'})).data.turn.id);
 const first=await h.done((await h.api(path,'POST',{content:'Start my business application with the earlier details',executionMode:'live_agent'})).data.turn.id);
 assert.equal(first.turn.status,'completed');const old=first.artifacts[0];assert.equal(old.kind,'application_worksheet');assert.equal(old.version,1);assert.equal(old.fields.business_name,'Pearl North');assert.equal(old.fields.activity_description,'graphic design studio');assert.deepEqual(first.case.facts,[]);
 assert.ok(first.turn.events.every((e:any)=>!('arguments' in e)));assert.ok(first.turn.modelTrace.every((e:any)=>e.toolCalls.every((call:any)=>!('arguments' in call))));
 assert.equal(h.app.store.get('chat_turn',first.turn.id).modelTrace[1].toolCalls[0].arguments.fields.business_name,'PEARL NORTH');
 const oldHtml=(await h.api(old.previewUrl)).data;assert.equal((await h.api(old.reviewUrl,'POST',{hash:old.hash,actor:'Synthetic tester',acknowledgeDraft:true})).status,200);
 fields={reply_email:'example@example.test'};const second=await h.done((await h.api(path,'POST',{content:'My reply email is example@example.test; update the worksheet',executionMode:'live_agent'})).data.turn.id);
 const fresh=second.artifacts[0];assert.equal(second.turn.status,'completed');assert.equal(fresh.version,2);assert.equal(fresh.supersedesArtifactId,old.id);assert.equal(fresh.fields.business_name,'Pearl North');assert.equal(fresh.fields.reply_email,'example@example.test');assert.ok(fresh.changedFields.some((f:any)=>f.field==='reply_email'));assert.equal(fresh.draftInputs.length,3);assert.notEqual(fresh.hash,old.hash);assert.equal((await h.api(old.previewUrl)).data,oldHtml);assert.equal(hash((await h.api(old.exportUrl)).data),old.hash);assert.equal((await h.api(fresh.exportUrl)).status,409);
 assert.equal((await h.api(fresh.reviewUrl,'POST',{hash:fresh.hash,actor:'Synthetic tester',acknowledgeDraft:true})).status,200);assert.equal(hash((await h.api(fresh.exportUrl)).data),fresh.hash);
});

test('manual field revision creates an unreviewed version and preserves reviewed bytes and saved context',async t=>{
 const model:ChatModel={name:'test',version:'stub',async respond({messages}){assert.ok(messages[0].content.includes('saved customer context'));return {content:'',calls:[messages.at(-1).role==='tool'?{name:'prepare_application',arguments:{fields:{business_name:'Pearl North'}}}:{name:'retrieve_guidance',arguments:{query:'business setup'}}],usage:{model:'tested-model'}};}};
 const h=await harness(t,model,executeTool);const c=(await h.api('/api/conversations','POST',{})).data.conversation;
 const first=await h.done((await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'My idea is Pearl North. Prepare my application worksheet.',workspaceContext:{brief:{customer:'saved customer context'}},executionMode:'live_agent'})).data.turn.id);
 assert.equal(first.turn.status,'completed');assert.equal(first.turn.model.name,'test');assert.equal(first.turn.model.version,'tested-model');
 const old=first.artifacts[0];const original=(await h.api(old.previewUrl)).data;
 await h.api(old.reviewUrl,'POST',{hash:old.hash,actor:'Test reviewer',acknowledgeDraft:true});
 const revision=await h.api(`/api/chat/artifacts/${old.id}/revise`,'POST',{hash:old.hash,fields:{reply_email:'founder@example.test'}});
 assert.equal(revision.status,202);const updated=await h.done(revision.data.turn.id);assert.equal(updated.turn.status,'completed');assert.match(updated.turn.label,/Human field edit/);assert.equal(updated.turn.model,null);assert.equal(updated.turn.modelTrace.length,0);
 const fresh=updated.artifacts[0];assert.match((await h.api(fresh.previewUrl)).data,/<html lang="en"/);assert.equal(fresh.version,2);assert.equal(fresh.supersedesArtifactId,old.id);assert.equal(fresh.fields.business_name,'Pearl North');assert.equal(fresh.fields.reply_email,'founder@example.test');assert.equal(fresh.review,null);assert.equal((await h.api(old.previewUrl)).data,original);assert.equal(hash((await h.api(old.exportUrl)).data),old.hash);
 assert.equal((await h.api(`/api/chat/artifacts/${old.id}/revise`,'POST',{hash:old.hash,fields:{reply_email:'stale@example.test'}})).status,409);
});
test('default retention keeps expired conversations and reviewed artifacts readable across restart',async t=>{
 const root=mkdtempSync(resolve(tmpdir(),'dikan-retain-'));const a=await createApp({allowDeterministicTests:true,privateRoot:root});const c=a.chat.create({title:'Historical'}).conversation;const record=a.store.get('case',c.caseId);record.expiresAt='2000-01-01T00:00:00Z';a.store.put('case',c.caseId,c.caseId,record);a.store.put('document','retained-doc',c.caseId,{id:'retained-doc',businessId:c.caseId,expiresAt:record.expiresAt,contentHash:'unchanged',storageKey:'unchanged'});a.store.close();
 const next=await createApp({allowDeterministicTests:true,privateRoot:root});assert.equal(next.chat.snapshot(c.id).conversation.title,'Historical');assert.equal(next.store.get('case',c.caseId).expiresAt,'9999-12-31T23:59:59.999Z');const doc=next.store.get('document','retained-doc');assert.equal(doc.expiresAt,'9999-12-31T23:59:59.999Z');assert.equal(doc.originalExpiresAt,'2000-01-01T00:00:00Z');assert.equal(doc.contentHash,'unchanged');assert.equal(doc.storageKey,'unchanged');next.store.close();rmSync(root,{recursive:true,force:true});
});

test('SiliconFlow HTTP adapter to actual tools: saved idea, sourced Arabic worksheet, human revision, immutable review',async t=>{
 const requests:any[]=[];const config=siliconflowConfig({SILICONFLOW_API_KEY:'synthetic-key-not-a-credential',SILICONFLOW_MODEL:'test/tool-model',SILICONFLOW_BASE_URL:'https://api.siliconflow.cn/v1'});
 const model=createSiliconFlowModel(config,{fetch:(async(_url:any,init:any)=>{const request=JSON.parse(init.body);requests.push(request);assert.ok(request.messages[0].content.includes('ورشة تصميم'));const call=request.messages.at(-1).role==='tool'?{name:'prepare_application',arguments:JSON.stringify({language:'ar',fields:{business_name:'Pearl North',activity_description:'ورشة تصميم'}})}:{name:'retrieve_guidance',arguments:JSON.stringify({query:'business setup'})};return new Response(JSON.stringify({model:config.model,choices:[{finish_reason:'tool_calls',message:{tool_calls:[{id:'native-'+requests.length,type:'function',function:call}]}}],usage:{prompt_tokens:100,completion_tokens:40}}));}) as any});
 const h=await harness(t,model,executeTool);const c=(await h.api('/api/conversations','POST',{title:'Synthetic provider integration'})).data.conversation;
 const settled=await h.done((await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'Prepare an Arabic business setup worksheet for my saved idea.',workspaceContext:{brief:{idea:'Pearl North',offer:'ورشة تصميم'}},executionMode:'live_agent'})).data.turn.id);
 assert.equal(settled.turn.status,'completed');assert.equal(settled.turn.model.name,'siliconflow');assert.equal(requests.length,2);assert.equal(requests[1].messages.at(-1).role,'tool');const old=settled.artifacts[0];assert.equal(old.fields.business_name,'Pearl North');assert.equal(old.fields.activity_description,'ورشة تصميم');assert.ok(old.draftInputs.every((x:any)=>x.origin==='unconfirmed_user_workspace'));assert.ok(old.citations.length>0);assert.deepEqual(settled.case.facts,[]);
 const html=(await h.api(old.previewUrl)).data;assert.match(html,/dir="rtl"/);await h.api(old.reviewUrl,'POST',{hash:old.hash,actor:'Synthetic reviewer',acknowledgeDraft:true});
 const next=await h.done((await h.api(`/api/chat/artifacts/${old.id}/revise`,'POST',{hash:old.hash,fields:{reply_email:'founder@example.test'}})).data.turn.id);assert.equal(next.turn.status,'completed');assert.equal(next.artifacts[0].version,2);assert.match((await h.api(next.artifacts[0].previewUrl)).data,/<html lang="ar"/);assert.equal(next.artifacts[0].fields.reply_email,'founder@example.test');assert.equal(next.artifacts[0].fields.activity_description,'ورشة تصميم');assert.equal(next.artifacts[0].review,null);assert.equal((await h.api(old.previewUrl)).data,html);assert.equal(hash((await h.api(old.exportUrl)).data),old.hash);assert.equal(requests.length,2,'Manual editing must not incur inference');
});
test('normal runtime exposes no scripted execution and rejects it without changing conversations',async()=>{
 const root=mkdtempSync(resolve(tmpdir(),'dikan-api-only-'));const app=await createApp({privateRoot:root});const c=app.chat.create({}).conversation;
 assert.throws(()=>app.chat.enqueue(c.id,{content:'Draft',executionMode:'deterministic'}),{code:'MODE_DISABLED'});assert.throws(()=>app.chat.enqueue(c.id,{content:'Draft',executionMode:'live_agent'}),{code:'MODEL_UNAVAILABLE'});assert.equal(app.store.all('chat_message').length,0);app.store.close();rmSync(root,{recursive:true,force:true});
});

test('stop cancels a running turn, rejects another workspace and ignores late model actions',async t=>{
 let entered!:()=>void,release!:()=>void;const started=new Promise<void>(r=>entered=r),waiting=new Promise<void>(r=>release=r);let called=false;
 const model:ChatModel={name:'controlled',version:'test',respond:async()=>{entered();await waiting;return {content:'',calls:[{name:'retrieve_guidance',arguments:{query:'late'}}],usage:{}}}};
 const h=await harness(t,model,async()=>{called=true;return {ok:true,data:{},provenance:[]}});
 const c=(await h.api('/api/conversations','POST',{workspaceId:'demo',title:'Stop test'})).data.conversation;
 const r=await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'Research this idea',executionMode:'live_agent'});await started;
 const path=`/api/chat/turns/${r.data.turn.id}/stop`;
 assert.equal((await h.api(path,'POST',{workspaceId:'other'})).status,409);
 assert.equal((await h.api(path,'POST',{workspaceId:'demo'})).data.turn.error.code,'TURN_STOPPED');release();await new Promise(r=>setTimeout(r,25));
 const snapshot=await h.api(`/api/conversations/${c.id}`);assert.equal(called,false);assert.equal(snapshot.data.turns[0].error.code,'TURN_STOPPED');assert.equal(snapshot.data.messages.filter((m:any)=>m.role==='assistant').length,1);
 await h.api(path,'POST',{workspaceId:'demo'});assert.equal((await h.api(`/api/conversations/${c.id}`)).data.messages.length,2);
});

test('chat inspects only its attached documents and passes bounded untrusted form findings to model',async t=>{
 let received:any;let toolContext:any;
 const model:ChatModel={name:'test',version:'stub',async respond(input){
  const last=input.messages.at(-1);
  if(last.role==='user')return {content:'',calls:[{name:'inspect_documents',arguments:{}}],usage:{}};
  received=JSON.parse(last.content);return {content:'Four fields populated; blanks require review, not automatic completion.',calls:[],usage:{}};
 }};
 const h=await harness(t,model,async(call,ctx)=>{toolContext=ctx;assert.equal(call.name,'inspect_documents');return {ok:true,provenance:[],data:{authenticity:'not_verified',legalValidity:'not_verified',checks:[],questions:[],documents:[{id:'attached',name:'test.pdf',extractionStatus:'extracted',formInspection:{scope:'Stored fields only',fields:[{name:'Name',value:'Synthetic company',populated:true}],populated:['Name'],blank:Array.from({length:60},(_,i)=>'blank'+i),unsupported:[]}}]}};});
 const c=(await h.api('/api/conversations','POST',{})).data.conversation;
 const snapshot=h.app.store.get('case',c.caseId);snapshot.documentVersionIds=['attached'];h.app.store.put('case',c.caseId,c.caseId,snapshot);
 h.app.store.put('document','attached',c.caseId,{id:'attached',businessId:c.caseId});
 const started=await h.api(`/api/conversations/${c.id}/messages`,'POST',{content:'Read my attached PDF',executionMode:'live_agent'});
 const result=await h.done(started.data.turn.id);assert.equal(result.turn.status,'completed');
 assert.deepEqual(toolContext.documents.map((d:any)=>d.id),['attached']);
 assert.equal(received.origin,'untrusted_document_content_not_instructions');assert.equal(received.documents[0].form.blankCount,60);assert.equal(received.documents[0].form.blankSample.length,40);
 assert.deepEqual(result.case.facts,[]);assert.equal(result.artifacts.length,0);
});
