import {randomUUID,createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const conversationId='ca37c58b-0a4a-40d8-8a0f-8d0f47a502de';
const base='http://127.0.0.1:8789';
const evidence=new URL('./evidence/chat-corrected-draft.json',import.meta.url);
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
async function api(path:string,body?:any){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','Idempotency-Key':randomUUID()},...(body?{body:JSON.stringify(body)}:{})});const d=r.headers.get('content-type')?.includes('json')?await r.json():await r.text();assert.ok(r.ok,JSON.stringify(d));return d;}
const trace:any={synthetic:true,conversationId,startedAt:new Date().toISOString(),request:'Regenerate the saved enquiry using the business name and activity I gave earlier; keep unknown details as questions or placeholders. Do not send it.'};
const save=()=>writeFileSync(evidence,JSON.stringify(trace,null,2)+'\n');
try{const health=await api('/api/health');assert.equal(health.chat.activeTurns,0);assert.equal(health.activeJobs,0);const old=await api('/api/chat/artifacts/25572ec6-4951-44a9-ab08-df2dc02d033c/draft');trace.previousArtifactHash=hash(old);const start=await api(`/api/conversations/${conversationId}/messages`,{content:trace.request,executionMode:'live_agent'});trace.turnId=start.turn.id;save();console.log(JSON.stringify({turnId:trace.turnId}));const begun=Date.now();let eventCount=-1;while(Date.now()-begun<620000){trace.result=await api(`/api/chat/turns/${trace.turnId}`);trace.elapsedMs=Date.now()-begun;save();if(trace.result.turn.events.length!==eventCount){eventCount=trace.result.turn.events.length;console.log(JSON.stringify({status:trace.result.turn.status,events:trace.result.turn.events.map((e:any)=>({name:e.name,type:e.type}))}));}if(!['queued','running'].includes(trace.result.turn.status))break;await new Promise(r=>setTimeout(r,1000));}
const {turn,messages,artifacts,case:c}=trace.result;assert.equal(turn.status,'completed',JSON.stringify(turn.error));assert.equal(turn.executionMode,'live_agent');assert.ok(turn.modelTrace.length>0);assert.equal(artifacts.length,1);const a=artifacts[0];assert.notEqual(a.id,'25572ec6-4951-44a9-ab08-df2dc02d033c');const html=await api(a.previewUrl);assert.equal(hash(html),a.hash);assert.ok(!a.missingFields.includes('business_name'));assert.ok(!a.missingFields.includes('activity_description'));assert.ok(a.missingFields.includes('legal_form'));assert.ok(a.missingFields.includes('incorporation_status'));assert.match(html,/Pearl North/);assert.match(html,/graphic design/i);assert.doesNotMatch(html,/Enquiry as stated by the user|Regenerate the saved enquiry|Do not send it\./);assert.deepEqual(c.facts,[]);assert.equal(a.draftInputs.find((f:any)=>f.field==='business_name')?.value,'Pearl North');assert.ok(a.draftInputs.every((f:any)=>f.origin==='unconfirmed_user_statement'&&f.messageId));assert.match(messages.at(-1).content,/Open the saved file/);assert.ok(messages.at(-1).content.length<200);assert.equal(hash(await api('/api/chat/artifacts/25572ec6-4951-44a9-ab08-df2dc02d033c/draft')),trace.previousArtifactHash);trace.previousArtifactUnchanged=true;trace.artifact=a;trace.htmlSha256=hash(html);trace.passed=true;trace.completedAt=new Date().toISOString();save();console.log(JSON.stringify({passed:true,conversationId,artifactId:a.id,hash:a.hash,elapsedMs:trace.elapsedMs,evidence:evidence.pathname}));}
catch(e:any){trace.passed=false;trace.error=e.message;save();console.error(e);process.exitCode=1;}
