import {createHash,randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync,readdirSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const sha=(s:Buffer|string)=>createHash('sha256').update(s).digest('hex');
function historyHashes(dir:string):Record<string,string>{const out:Record<string,string>={};for(const entry of readdirSync(dir,{withFileTypes:true})){const path=resolve(dir,entry.name);if(entry.isDirectory())Object.assign(out,historyHashes(path));else if(entry.isFile())out[path.slice(root.length+1)]=sha(readFileSync(path));}return out;}
const evidence=resolve(root,'test/evidence');mkdirSync(evidence,{recursive:true});const trace:any={synthetic:true,title:'Example: opening a design studio (synthetic)',startedAt:new Date().toISOString(),base:'http://127.0.0.1:8789',store:'.private-chat-demo',previousStore:'.private',previousStoreHashes:historyHashes(resolve(root,'.private')),turns:[]};
const tracePath=resolve(evidence,'chat-live-rehearsal.json');if(process.argv[2]==='resume'){const previous=JSON.parse(readFileSync(tracePath,'utf8'));writeFileSync(resolve(evidence,'chat-live-first-attempt.json'),JSON.stringify(previous,null,2)+'\n');Object.assign(trace,previous);delete trace.error;delete trace.passed;trace.resumedAt=new Date().toISOString();}const save=()=>writeFileSync(tracePath,JSON.stringify(trace,null,2)+'\n');
async function api(path:string,method='GET',body?:any){const r=await fetch(trace.base+path,{method,headers:{'Content-Type':'application/json','Idempotency-Key':randomUUID()},...(body?{body:JSON.stringify(body)}:{})});const data=r.headers.get('content-type')?.includes('json')?await r.json():await r.text();assert.ok(r.ok,JSON.stringify({status:r.status,data}));return data;}
async function turn(content:string){const begin=Date.now();const started=await api(`/api/conversations/${trace.conversationId}/messages`,'POST',{content,executionMode:'live_agent'});trace.turns.push({id:started.turn.id,content});save();let lastEvents=-1;while(Date.now()-begin<620000){const snapshot=await api(`/api/chat/turns/${started.turn.id}`);if(snapshot.turn.events.length!==lastEvents){lastEvents=snapshot.turn.events.length;console.log(JSON.stringify({turnId:started.turn.id,status:snapshot.turn.status,events:snapshot.turn.events.map((e:any)=>({type:e.type,name:e.name}))}));}trace.turns[trace.turns.length-1]={...snapshot,elapsedMs:Date.now()-begin};save();if(!['queued','running'].includes(snapshot.turn.status)){assert.equal(snapshot.turn.status,'completed',JSON.stringify(snapshot.turn.error));assert.ok(snapshot.turn.modelTrace.length>0);assert.ok(snapshot.messages.at(-1).citations.length>0);return snapshot;}await new Promise(r=>setTimeout(r,1000));}throw Error('Live rehearsal timed out');}
try{const health=await api('/api/health');assert.equal(health.chat.activeTurns,0);assert.equal(health.activeJobs,0);const created=trace.conversationId?{conversation:{id:trace.conversationId,caseId:trace.caseId}}:await api('/api/conversations','POST',{title:trace.title});trace.conversationId=created.conversation.id;trace.caseId=created.conversation.caseId;save();console.log(JSON.stringify({conversationId:trace.conversationId,caseId:trace.caseId,tracePath}));
await turn((process.argv[2]==='resume'?'Please answer the earlier question now. ':'')+'Synthetic example, not my real business: I am exploring a small graphic design studio in Kuwait called Pearl North. I have not chosen a legal form, incorporated a company or signed a lease. Using your collected official sources, what should I clarify first about the commercial licence route and premises? Do not assume I qualify for a one-person company.');
const second=await turn('For that same synthetic studio, prepare an English enquiry draft to the relevant official contact asking which licence route and premises evidence apply. Keep unknown legal form and incorporation details as questions or placeholders. Include the captured sources. Do not send it.');assert.ok(second.artifacts.length>0);const artifact=second.artifacts[0];const html=await api(artifact.previewUrl);assert.equal(sha(html),artifact.hash);assert.ok(!/Madar Design Studio/.test(html));assert.ok(/Pearl North/.test(html));assert.deepEqual(second.case.facts,[]);trace.artifact=artifact;trace.artifactPreviewHash=sha(html);trace.snapshot=await api(`/api/conversations/${trace.conversationId}`);assert.equal(trace.snapshot.messages.length,process.argv[2]==='resume'?6:4);trace.historicalBytesUnchanged=JSON.stringify(trace.previousStoreHashes)===JSON.stringify(historyHashes(resolve(root,'.private')));assert.equal(trace.historicalBytesUnchanged,true);trace.completedAt=new Date().toISOString();trace.passed=true;save();console.log(JSON.stringify({passed:true,conversationId:trace.conversationId,artifactId:artifact.id,hash:artifact.hash,tracePath}));}
catch(e:any){trace.passed=false;trace.error=e.message;save();console.error(e);process.exitCode=1;}
