import test from 'node:test';
import assert from 'node:assert/strict';
import {chatToolNames} from '../contracts/chat.ts';
import {schema} from '../src/chat.ts';
import {workspaceModelContext} from '../src/workspace-model-context.ts';
import {chatRequestSizeDiagnostics,fitChatRequestMessages,foldEarlierResearchResults,guidanceContextForModel,recentEvidenceContext,researchContextForModel} from '../src/chat-context.ts';
import {wireMessages} from '../src/siliconflow.ts';

const source=(index:number)=>({id:`MK-SOURCE-${index}`,title:`Kuwait retail evidence ${index}`,publisher:'Synthetic Statistics Office',url:`https://example.test/reports/${index}`,passage:`Synthetic evidence passage ${index}. `.repeat(28),limitations:['Aggregate information does not establish demand for an individual business.','Observation applies to the published population and period only.'],dataPeriod:'2024',scope:'Kuwait',structuredData:{authority:'Synthetic Statistics Office',rows:[{ageGroup:'all ages',allResidents:{total:4881254},unit:'persons',observationDate:'2025-01-01',geography:'Kuwait',pdfPage:1}]},citation:{sourceID:`MK-SOURCE-${index}`,chunkID:`MK-SOURCE-${index}:p${index}`,title:`Kuwait retail evidence ${index}`,url:`https://example.test/reports/${index}`,authority:'Synthetic Statistics Office',page:index,capturedAt:'2026-09-20',publicationDate:'2025-05-01',dataPeriod:'2024',localCitation:`market/text/MK-SOURCE-${index}.txt#L${index}`,rawSha256:`raw-${index}`,passageSha256:`passage-${index}`}});
const searchData=(count:number)=>{const sources=Array.from({length:count},(_,i)=>source(i+1));return {query:'Kuwait retail customer need',phase:'validation',abstained:false,sources,citations:sources.map(s=>s.citation),caveats:['Public aggregate statistics do not validate private demand.'],phaseGuidance:{authority:'Dukkan-authored method',decision:'Test a material customer assumption.',output:['A proposed test'],gate:'Evidence is not validation',steps:['Speak to customers']}};};
const asToolPair=(name:string,args:any,result:any)=>[{role:'assistant',content:'',tool_calls:[{function:{name,arguments:args}}]},{role:'tool',tool_name:name,content:JSON.stringify(result)}];

test('continuation context retains founder choice, proposed test and complete source references',()=>{
 const citations=Array.from({length:9},(_,i)=>({sourceID:`S${i+1}`,chunkID:`S${i+1}:p${i+1}`,title:`Source ${i+1}`,url:`https://example.test/${i+1}`,publisher:'Publisher',page:i+1,publicationDate:'2025-05-01',dataPeriod:'2024',capturedAt:'2026-09-20',excerpt:`Excerpt ${i+1}`,limitations:['Aggregate data is indirect evidence.']}));
 const history=[{role:'assistant',citations}];const artifacts=[{citations:citations.slice(0,3)}];
 const context=recentEvidenceContext(history,artifacts);assert.equal(context.length,9);assert.equal(context[0].sourceID,'S1');assert.equal(context[0].chunkID,'S1:p1');assert.equal(context[0].page,1);assert.equal(context[0].dataPeriod,'2024');assert.equal(context[0].capturedAt,'2026-09-20');assert.equal(context[0].limitations[0],'Aggregate data is indirect evidence.');
 const proposed=researchContextForModel(searchData(3));assert.equal(proposed.evidence.length,3);assert.equal(proposed.evidence[0].sourceID,'MK-SOURCE-1');assert.equal(proposed.evidence[0].chunkID,'MK-SOURCE-1:p1');assert.equal(proposed.evidence[0].page,1);assert.equal(proposed.evidence[0].capturedAt,'2026-09-20');assert.ok(proposed.evidence[0].limitations.length);assert.equal(proposed.evidence[0].structuredData.rows[0].allResidents.total,4881254);assert.equal(proposed.evidence[0].structuredData.rows[0].unit,'persons');assert.equal(proposed.evidence[0].structuredData.rows[0].observationDate,'2025-01-01');assert.ok(!JSON.stringify(proposed.evidence[0].structuredData).includes('rawSha256'));
});

test('large repaired-draft request fits the full provider body and tools without losing current intent or evidence IDs',t=>{
 const current='Prepare a validation draft for the same idea. Keep our adopted starter-kit test and decision rule, and use the sources retrieved in this turn.';
 const sources=searchData(9);const legal={query:'official route',abstained:false,route:'clarification required',evidence:Array.from({length:3},(_,i)=>({id:`ACT-${i+1}`,chunkID:`ACT-${i+1}:p${i+1}`,title:`Official guidance ${i+1}`,publisher:'Synthetic Ministry',url:`https://example.test/legal/${i+1}`,page:i+1,publicationDate:'2024-01-01',dataPeriod:'2024',capturedAt:'2026-09-19',passage:'Synthetic legal guidance '.repeat(100),limitations:['Captured guidance may not be current or applicable.']})),citations:[],caveats:['Applicability needs official confirmation.']};
 const failedArgs={stage:'validate',title:'Proposed customer test',content:'Test the selected starter-kit offer with shop owners. '.repeat(45),assumptions:['Owners have this problem'],unknowns:['Willingness to pay'],citationIds:['incorrect-id'],proposedTest:{hypothesis:'Owners will consider a fixed-scope starter kit.',method:'Show a sample and ask about current alternatives.',audience:'Small shop owners in Kuwait',decisionRule:'Record explicit interest and objections; this is directional, not validation.'}};
 const savedIdea={stage:'idea',title:'Starter kit idea review',content:'Prior critique detail '.repeat(1400),assumptions:Array(8).fill('Assumption to validate '.repeat(8)),unknowns:Array(8).fill('Unknown to resolve '.repeat(8)),proposedTest:{hypothesis:'Owners will consider a fixed-scope starter kit.',method:'Show a sample and ask about current alternatives.',audience:'Small shop owners in Kuwait',decisionRule:'Record explicit interest and objections; this is directional, not validation.'},ideaReview:{dimensions:Array.from({length:5},(_,i)=>({key:`dimension-${i}`,score:1,reason:'Evidence remains indirect. '.repeat(12),evidenceNeeded:'Talk to owners. '.repeat(12)})),criticalRisks:Array(6).fill('Demand remains unverified. '.repeat(12)),options:Array.from({length:6},(_,i)=>({title:`Option ${i}`,kind:'feature',benefit:'Potential benefit. '.repeat(10),tradeoff:'Delivery cost and capacity. '.repeat(10),test:'Ask customers. '.repeat(10)})),recommendation:'test',rationale:'Test before expansion. '.repeat(20)},citations:Array.from({length:20},(_,i)=>({sourceID:`OLD-${i}`,chunkID:`OLD-${i}:p1`,title:`Old source ${i}`,url:`https://example.test/old/${i}`}))};
 const actualWorkspace:any={updatedAt:'2026-10-07',brief:{idea:'FOUNDER CHOICE: start with a fixed-scope starter kit.',customer:'Independent shop owners',problem:'Setup is difficult',alternative:'Do it themselves',offer:'Starter kit',boundary:'No expansion before testing.',sector:'Retail & ecommerce',location:'Kuwait'},profile:{stage:'Testing demand',budget:''},costs:{price:'60',variable:'8',fixed:'25',units:'10'},nextAction:{task:'Run starter-kit test',owner:'Founder',due:'',dependency:'Speak to shop owners'},hypotheses:Array.from({length:10},(_,i)=>({id:`H${i}`,title:`Old hypothesis ${i}`,area:'Demand',priority:'Important',status:'Testing',reviewReason:'',test:{method:'Old method',audience:'Old audience',rule:'Old rule',result:''}})),decisions:Array.from({length:15},(_,i)=>({id:`D${i}`,hypothesisId:`H${i}`,date:`2026-09-${String(i+1).padStart(2,'0')}`,outcome:'Keep testing',reason:`Old validation decision ${i}`,assumption:'Old assumption',rule:'Old rule',evidence:[]})),ideaReviewDecisions:Array.from({length:15},(_,i)=>({id:`IR${i}`,artifactId:`OLD-A${i}`,conversationId:'old-conversation',date:`2026-09-${String(i+1).padStart(2,'0')}`,choice:'revise',reason:`Old review reason ${i} `+'Earlier saved state '.repeat(30),selectedOption:`Old option ${i}`,reviewSummary:'Old review summary',customOption:{title:'Old custom',kind:'feature',tradeoff:'Old tradeoff'}})),lifecycle:Array.from({length:20},(_,i)=>({id:`L${i}`,revision:1,at:'2026-09-01',values:{title:`Saved record ${i}`,details:'Old saved state '.repeat(40),category:'business_decision'},history:[]}))};
 actualWorkspace.hypotheses.push({id:'H-ADOPTED',title:'Starter kit demand',area:'Demand',priority:'Critical',status:'Testing',reviewReason:'',test:{method:'ADOPTED: show a starter-kit sample to shop owners.',audience:'Independent shop owners in Kuwait',rule:'Record interest and objections before expansion.',result:'',provenance:{artifactId:'ARTIFACT-IDEA',conversationId:'CONVERSATION-FOUNDER',title:'Idea critique',adoptedAt:'2026-10-07T09:00:00Z'}}});actualWorkspace.ideaReviewDecisions.push({id:'IR-LATEST',artifactId:'ARTIFACT-IDEA',conversationId:'CONVERSATION-FOUNDER',date:'2026-10-30T09:05:00Z',choice:'test',reason:'We chose this because shop owners need a low-risk first setup.',selectedOption:'Entry-level starter kit for independent shops',reviewSummary:'Test the core offer before expanding.',customOption:{title:'One-day onboarding',kind:'feature',tradeoff:'Requires founder time.'}});actualWorkspace.decisions.push({id:'D-LATEST',hypothesisId:'H-ADOPTED',date:'2026-10-31T09:10:00Z',outcome:'Keep testing',reason:'No customer evidence yet; run the adopted test first.',assumption:'Shop owners need setup help.',rule:'Record interest and objections.',evidence:[]});
 const contextPayload={workspaceContext:{origin:'user_workspace_unverified',data:workspaceModelContext(actualWorkspace,'starter kit',7000)},confirmedCaseFacts:[],businessRevision:1,hasDocuments:false,priorArtifacts:Array.from({length:20},(_,i)=>({id:`A${i}`,title:`Artifact ${i}`,hash:`hash-${i}`,reviewed:false,sent:false})),generatedDrafts:{origin:'untrusted_ai_draft_not_founder_fact',drafts:[savedIdea,{...savedIdea,stage:'validate',title:'Previous validation draft'},{...savedIdea,stage:'plan',title:'Previous plan'}]},recentEvidence:Array.from({length:9},(_,i)=>({sourceID:`PRIOR-${i}`,chunkID:`PRIOR-${i}:p1`,title:`Prior source ${i}`,url:`https://example.test/prior/${i}`,publisher:'Synthetic publisher',page:i+1,publicationDate:'2025-05-01',dataPeriod:'2024',capturedAt:'2026-09-20',scope:'Kuwait',excerpt:'Prior passage '.repeat(20),limitations:['Aggregate information does not establish demand. '.repeat(8)],currentness:'Captured; current applicability not established.'}))};
 const messages:any[]=[{role:'system',content:'Dukkan fixed instructions. Cite only current-turn evidence. Preserve the selected test and founder choice.\n'+JSON.stringify(contextPayload)}];
 for(let i=0;i<5;i++){messages.push({role:'user',content:(i===3?'We chose the starter kit first and will not expand until we hear from shop owners. ':'Earlier founder context ').padEnd(3900,'u')});messages.push({role:'assistant',content:('Critical evidence review with assumptions and next steps. ').padEnd(1450,'a')});}
 messages.push({role:'user',content:current});const founderMessageIndex=messages.length-1;
 const first=asToolPair('search_business_knowledge',{query:'retail demand'},researchContextForModel(searchData(3)));messages.push(...first);
 const second=asToolPair('search_business_knowledge',{query:'shop design alternatives'},researchContextForModel(sources));messages.push(...second);foldEarlierResearchResults(messages);
 const projectedLegal=guidanceContextForModel(legal);assert.equal(projectedLegal.evidence[0].publicationDate,'2024-01-01');assert.equal(projectedLegal.evidence[0].capturedAt,'2026-09-19');assert.equal(projectedLegal.evidence[0].limitations[0],'Captured guidance may not be current or applicable.');messages.push(...asToolPair('retrieve_guidance',{query:'official route'},projectedLegal));messages.push({role:'user',content:'Repair instruction: correct the rejected citation IDs using evidence already retrieved. Keep the founder request and evidence.'});
 messages.push({role:'assistant',content:'',tool_calls:[{function:{name:'prepare_stage_draft',arguments:failedArgs}}]},{role:'tool',tool_name:'prepare_stage_draft',content:JSON.stringify({error:{code:'UNRETRIEVED_CITATION',message:'Draft citations must match evidence retrieved during this turn.'},saved:false,instruction:'Correct the citation IDs and retry prepare_stage_draft. Do not invent citations.'})});
 const tools=chatToolNames.map(schema);const model='synthetic/model';const body=(list:any[])=>({model,messages:wireMessages(list),tools,stream:false,enable_thinking:false,max_tokens:1200});const originalBytes=Buffer.byteLength(JSON.stringify(body(messages)));assert.ok(originalBytes>60000,`fixture should reproduce an over-cap request, was ${originalBytes} bytes`);
 const fitted=fitChatRequestMessages(messages,tools,model,founderMessageIndex);const request=body(fitted);const requestBytes=Buffer.byteLength(JSON.stringify(request));assert.ok(requestBytes<60000,`request is ${requestBytes} bytes`);assert.ok(requestBytes<=48000,`compactor targets 48 KB; fitted body is ${requestBytes} bytes`);const sizes=chatRequestSizeDiagnostics(fitted,tools,model);assert.ok(sizes.systemBytes<=24000,`system message JSON is ${sizes.systemBytes} bytes`);assert.ok(sizes.systemDynamicContextBytes<=10000,`dynamic system context is ${sizes.systemDynamicContextBytes} bytes`);
 assert.ok(JSON.stringify(request).includes('Captured guidance may not be current or applicable.'));assert.ok(JSON.stringify(request).includes('2026-09-19'));
 t.diagnostic(`serialized body ${originalBytes} bytes before, ${requestBytes} after; system ${sizes.systemBytes} bytes (${sizes.systemInstructionBytes} fixed + ${sizes.systemDynamicContextBytes} dynamic), tools ${sizes.toolSchemaBytes} bytes (${tools.length} tools)`);
 assert.ok(request.messages.some((m:any)=>m.role==='user'&&m.content===current),'current founder request must remain exact after injected user instructions');assert.ok(request.messages.some((m:any)=>m.role==='user'&&m.content.includes('Repair instruction: correct the rejected citation IDs')),'repair instruction must remain in the current transcript');assert.ok(JSON.stringify(request).includes('FOUNDER CHOICE: start with a fixed-scope starter kit.'));assert.ok(JSON.stringify(request).includes('ADOPTED: show a starter-kit sample to shop owners.'));assert.ok(JSON.stringify(request).includes('We chose this because shop owners need a low-risk first setup.'));assert.ok(JSON.stringify(request).includes('Entry-level starter kit for independent shops'));assert.ok(JSON.stringify(request).includes('Independent shop owners in Kuwait'));assert.ok(JSON.stringify(request).includes('Record interest and objections before expansion.'));
 for(let i=1;i<=9;i++){assert.ok(JSON.stringify(request).includes(`MK-SOURCE-${i}`));assert.ok(JSON.stringify(request).includes(`2026-09-20`));assert.ok(JSON.stringify(request).includes('Aggregate information does not establish demand for an individual business.'));}
 assert.ok(JSON.stringify(request).includes('incorrect-id'),'failed tool arguments remain available for repair');assert.ok(JSON.stringify(request).includes('UNRETRIEVED_CITATION'),'citation validation error remains available');assert.ok(JSON.stringify(request).includes('validating')||JSON.stringify(request).includes('validation'));
 const calls=new Set<string>();for(const message of request.messages){if(message.role==='assistant')for(const call of message.tool_calls||[])calls.add(call.id);if(message.role==='tool')assert.ok(calls.has(message.tool_call_id),`tool result ${message.tool_call_id} must follow its assistant call`);}
 assert.match(messages.find((m:any)=>m.role==='tool'&&m.tool_name==='search_business_knowledge').content,/included in the latest aggregated market evidence/);
});
