import {randomUUID,createHash} from 'node:crypto';
import {writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const base='http://127.0.0.1:8789';
const mode=process.argv[2]||'deterministic';
async function api(path:string,body?:any){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','Idempotency-Key':randomUUID()},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d as any;}
async function wait(id:string){const start=Date.now();while(Date.now()-start<250000){const d=await api(`/api/jobs/${id}`);if(!['queued','running','retry_wait'].includes(d.job.status))return {...d,elapsedMs:Date.now()-start};await new Promise(r=>setTimeout(r,500));}throw Error('Job timed out');}
const businessId=`rehearsal-${mode}-${Date.now()}`;const fixture=await api('/api/demo-fixture');const created=await api('/api/cases',{businessId,facts:fixture.facts});const upload=await api(`/api/cases/${businessId}/documents`,{expectedRevision:created.case.businessRevision,synthetic:true,files:fixture.files});const started=await api(`/api/cases/${businessId}/jobs`,{expectedRevision:upload.case.businessRevision,executionMode:mode});console.log(JSON.stringify({stage:'started',mode,businessId,jobId:started.job.jobId}));
const initial=await wait(started.job.jobId);console.log(JSON.stringify({stage:'initial',status:initial.job.status,error:initial.job.error,elapsedMs:initial.elapsedMs,trace:initial.job.trace.map((x:any)=>x.name),modelTurns:initial.job.modelTrace?.length}));
if(initial.job.status!=='needs_input')throw Error('Initial job must pause for actual unit mismatch');
const successor=await api(`/api/cases/${businessId}/answers`,{expectedRevision:initial.case.businessRevision,supersedesJobId:initial.job.jobId,facts:fixture.correction.facts,executionMode:mode});const corrected=await wait(successor.job.jobId);console.log(JSON.stringify({stage:'corrected',status:corrected.job.status,error:corrected.job.error,elapsedMs:corrected.elapsedMs,trace:corrected.job.trace.map((x:any)=>x.name),modelTurns:corrected.job.modelTrace?.length,packHash:corrected.pack?.hash}));
if(corrected.job.status!=='blocked'||!corrected.pack)throw Error('Corrected job must produce source-blocked pack');
const reviewed=await api(`/api/jobs/${corrected.job.jobId}/review`,{expectedRevision:corrected.case.businessRevision,packHash:corrected.pack.hash,actor:'Mariam (synthetic rehearsal)',acknowledgeIncomplete:true});const exportResponse=await fetch(`${base}/api/jobs/${corrected.job.jobId}/export?packHash=${corrected.pack.hash}`);if(!exportResponse.ok)throw Error('Export failed');const html=await exportResponse.text();if(createHash('sha256').update(html).digest('hex')!==corrected.pack.hash)throw Error('Export hash differs from reviewed hash');
const receipt={schemaVersion:1,mode,businessId,at:new Date().toISOString(),initial,corrected,reviewed,export:{status:exportResponse.status,bytes:Buffer.byteLength(html),sha256:corrected.pack.hash},limitations:['No active legal requirements','No readiness, submission or official receipt','UI reviewed separately']};const directory=resolve(import.meta.dirname,'..',process.env.ASSIS_PRIVATE_ROOT||'.private-chat-demo','cases',businessId,'rehearsal');mkdirSync(directory,{recursive:true,mode:0o700});writeFileSync(resolve(directory,`${mode}.json`),JSON.stringify(receipt,null,2),{mode:0o600});writeFileSync(resolve(directory,`${mode}.html`),html,{mode:0o600});console.log(JSON.stringify({stage:'reviewed-exported',businessId,jobId:corrected.job.jobId,status:reviewed.job.status,handoff:reviewed.handoff.state,label:reviewed.review.label,packHash:corrected.pack.hash,receipt:resolve(directory,`${mode}.json`)}));
