import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createApp} from '../src/server.ts';
import {assertTransition,hash} from '../contracts/index.ts';
import type {ToolExecutor} from '../contracts/index.ts';
const fact=(value='21')=>({field:'premises.unit',value,origin:'founder',sourceRef:null,confirmedBy:'Synthetic founder',confirmedAt:new Date().toISOString()});
const tool:ToolExecutor=async(call,ctx)=>{const mismatch=ctx.caseSnapshot.facts.find(f=>f.field==='premises.unit')?.value==='21';const checks=[{status:mismatch?'mismatch':'checked'}];return {ok:true,data:call.name==='assemble_pack'?{html:'<!doctype html><html><body><h1>Incomplete synthetic preparation</h1></body></html>',checks,blockers:[],sources:[]}:call.name==='inspect_documents'?{checks,questions:mismatch?[{field:'premises.unit',reasonCode:'DOCUMENT_MISMATCH'}]:[]}:call.name==='request_information'?{questions:mismatch?[{field:'premises.unit',reasonCode:'DOCUMENT_MISMATCH'}]:[]}: {},provenance:[]};};
async function harness(t:any,executor=tool){const root=mkdtempSync(resolve(tmpdir(),'assis-runtime-'));const app=await createApp({allowDeterministicTests:true,expireCases:true,privateRoot:root,executor});await new Promise<void>(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(app.server.address() as any).port}`;t.after(async()=>{await new Promise<void>(r=>app.server.close(()=>r()));rmSync(root,{recursive:true,force:true});});let n=0;async function api(path:string,method='GET',body?:any,key?:string,headers:any={}){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json','Idempotency-Key':key||`request-${++n}`,...headers},...(body?{body:JSON.stringify(body)}:{})});const content=await response.text();return {status:response.status,data:response.headers.get('content-type')?.includes('json')?JSON.parse(content):content};}async function done(id:string){for(let n=0;n<200;n++){const r=await api(`/api/jobs/${id}`);if(!['queued','running','retry_wait'].includes(r.data.job.status))return r.data;await new Promise(r=>setTimeout(r,10));}throw Error('Job did not settle');}return {...app,root,api,done};}
test('validates transitions, confirmation and stale input before mutation',async t=>{assert.throws(()=>assertTransition('blocked','completed'));const h=await harness(t);assert.equal((await h.api('/api/cases','POST',{facts:[{field:'x',value:'unconfirmed'}]})).status,400);const created=await h.api('/api/cases','POST',{businessId:'test-case',facts:[fact()]});assert.equal(created.status,201);assert.equal((await h.api('/api/cases/test-case/jobs','POST',{expectedRevision:99})).status,409);assert.equal(h.store.all('job').length,0);assert.equal((await h.api('/api/cases/test-case/jobs','POST',{expectedRevision:1,executionMode:'live_agent'})).data.error.code,'MODEL_UNAVAILABLE');});
test('idempotency, successor correction, exact review, blocked export and invalidation',async t=>{const h=await harness(t);await h.api('/api/cases','POST',{businessId:'madar',facts:[fact()]});const path='/api/cases/madar/jobs';const first=await h.api(path,'POST',{expectedRevision:1},'same');const duplicate=await h.api(path,'POST',{expectedRevision:1},'same');assert.equal(first.data.job.jobId,duplicate.data.job.jobId);assert.equal((await h.api(path,'POST',{expectedRevision:1,executionMode:'deterministic'},'same')).status,409);const original=await h.done(first.data.job.jobId);assert.equal(original.job.status,'needs_input');const corrected=await h.api('/api/cases/madar/answers','POST',{expectedRevision:1,supersedesJobId:original.job.jobId,facts:[fact('12')]});assert.equal(corrected.status,202);const current=await h.done(corrected.data.job.jobId);assert.equal(current.job.status,'blocked');assert.equal(current.case.businessRevision,2);assert.equal((await h.api(`/api/jobs/${original.job.jobId}`)).data.job.status,'superseded');const exportPath=`/api/jobs/${current.job.jobId}/export?packHash=${current.pack.hash}`;assert.equal((await h.api(exportPath)).data.error.code,'REVIEW_REQUIRED');assert.equal((await h.api(`/api/jobs/${current.job.jobId}/review`,'POST',{expectedRevision:2,packHash:'wrong',actor:'Mariam',acknowledgeIncomplete:true})).status,409);const review=await h.api(`/api/jobs/${current.job.jobId}/review`,'POST',{expectedRevision:2,packHash:current.pack.hash,actor:'Mariam',acknowledgeIncomplete:true});assert.equal(review.data.job.status,'blocked');assert.equal(review.data.handoff.state,'blocked');assert.equal((await h.api(exportPath)).status,200);const newer=await h.api('/api/cases/madar/answers','POST',{expectedRevision:2,supersedesJobId:current.job.jobId,facts:[fact('13')]});await h.done(newer.data.job.jobId);assert.equal((await h.api(exportPath)).status,409);assert.equal((await h.api(`/api/jobs/${current.job.jobId}`)).data.review.valid,false);});
test('PDF private storage, deletion, bad origin and upload limits',async t=>{const h=await harness(t);await h.api('/api/cases','POST',{businessId:'privacy',facts:[fact()]});assert.equal((await h.api('/api/health','GET',undefined,undefined,{Origin:'https://evil.example'})).status,403);const files=[{name:'../fake.pdf',mime:'application/pdf',base64:Buffer.from('%PDF-1.7\nsynthetic').toString('base64')}];const upload=await h.api('/api/cases/privacy/documents','POST',{expectedRevision:1,synthetic:true,files});assert.equal(upload.status,201);assert.equal(upload.data.documents[0].storageKey,undefined);const doc=h.store.get('document',upload.data.documents[0].id);assert.ok(doc.storageKey.startsWith(h.root));assert.ok(existsSync(doc.storageKey));const invalid=await h.api('/api/cases/privacy/documents','POST',{expectedRevision:2,synthetic:true,files:Array(10).fill(files[0])});assert.equal(invalid.status,400);assert.equal(h.store.all('document').length,1);assert.equal((await h.api('/api/cases/privacy','DELETE')).status,200);assert.equal(existsSync(doc.storageKey),false);assert.equal(h.store.all('document').length,0);assert.equal((await h.api('/api/cases/privacy')).status,404);assert.equal(h.store.db.prepare('SELECT count(*) as n FROM receipts').get()!.n,0);});
test('transient tool failure retries at most three and retains checkpoint',async t=>{let attempts=0;const h=await harness(t,async(call,context)=>{if(call.name==='inspect_documents'){attempts++;return {ok:false,error:{code:'TEMP_UNAVAILABLE',message:'Injected transient failure',retryable:true},provenance:[]};}return tool(call,context);});await h.api('/api/cases','POST',{businessId:'retry',facts:[fact()]});const started=await h.api('/api/cases/retry/jobs','POST',{expectedRevision:1});const settled=await h.done(started.data.job.jobId);assert.equal(attempts,3);assert.equal(settled.job.status,'failed');assert.equal(settled.job.error.code,'TEMP_UNAVAILABLE');assert.ok(settled.job.resultRefs.retrieve_guidance);assert.equal(settled.pack,null);});
test('expiry purges documents and jobs without requiring export',async t=>{const h=await harness(t);await h.api('/api/cases','POST',{businessId:'expired',facts:[fact()]});const c=h.store.get('case','expired');c.expiresAt='2000-01-01T00:00:00Z';h.store.put('case','expired','expired',c);assert.equal((await h.api('/api/cases/expired')).status,404);assert.equal(h.store.all('case').length,0);});
test('restart preserves completed checkpoints and marks interrupted jobs',async()=>{const root=mkdtempSync(resolve(tmpdir(),'assis-restart-'));const first=await createApp({allowDeterministicTests:true,expireCases:true,privateRoot:root,executor:tool});first.store.put('case','persist','persist',{businessId:'persist',expiresAt:'2099-01-01T00:00:00Z'});first.store.put('job','interrupted','persist',{jobId:'interrupted',businessId:'persist',status:'running',resultRefs:{retrieve_guidance:'saved-hash'}});first.store.close();const next=await createApp({allowDeterministicTests:true,expireCases:true,privateRoot:root,executor:tool});assert.equal(next.store.get('job','interrupted').status,'failed');assert.equal(next.store.get('job','interrupted').resultRefs.retrieve_guidance,'saved-hash');next.store.close();rmSync(root,{recursive:true,force:true});});
test('changed pinned source invalidates review and blocks old export',async t=>{const h=await harness(t);await h.api('/api/cases','POST',{businessId:'source-change',facts:[fact('12')]});const started=await h.api('/api/cases/source-change/jobs','POST',{expectedRevision:1});const current=await h.done(started.data.job.jobId);await h.api(`/api/jobs/${current.job.jobId}/review`,'POST',{expectedRevision:1,packHash:current.pack.hash,actor:'Synthetic reviewer',acknowledgeIncomplete:true});const stored=h.store.get('job',current.job.jobId);stored.sourceSnapshotHash='obsolete-source-snapshot';h.store.put('job',stored.jobId,stored.businessId,stored);const changed=await h.api(`/api/jobs/${stored.jobId}`);assert.equal(changed.data.job.status,'superseded');assert.equal(changed.data.job.reasonCode,'SOURCE_CHANGED');assert.equal(changed.data.review.valid,false);assert.equal((await h.api(`/api/jobs/${stored.jobId}/export?packHash=${current.pack.hash}`)).status,409);});
