import assert from 'node:assert/strict';
import {hash} from '../contracts/index.ts';
import {writeFileSync} from 'node:fs';
const base='http://127.0.0.1:8789';
async function api(path:string,data?:any){const r=await fetch(base+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},...(data?{body:JSON.stringify(data)}:{})});const body=r.headers.get('content-type')?.includes('json')?await r.json():await r.text();assert.equal(r.ok,true,`Local HTTP ${r.status}: ${body?.error?.code||''}`);return body;}
async function done(id:string){const end=Date.now()+610000;while(Date.now()<end){const r=await api('/api/chat/turns/'+id);if(!['queued','running'].includes(r.turn.status)){assert.notEqual(r.turn.status,'failed',r.turn.error?.code);return r;}await new Promise(r=>setTimeout(r,1500));}throw Error('Turn deadline exceeded');}
const health=await api('/api/health');assert.equal(health.chat.model?.name,'siliconflow','Configure a working SiliconFlow API provider first; no other mode will run');
const {conversation}=await api('/api/conversations',{title:'SiliconFlow verification: synthetic idea'});
const first=await done((await api(`/api/conversations/${conversation.id}/messages`,{content:'Synthetic test: start my business setup application. Use the saved idea and activity. Research the collected sources, then prepare an Arabic worksheet. Keep legal form and incorporation unknown. Do not send or submit anything.',workspaceContext:{brief:{idea:'Pearl North',offer:'ورشة تصميم',location:'Kuwait'},profile:{stage:'Exploring the idea'}},executionMode:'live_agent'})).turn.id);
assert.equal(first.turn.model.name,'siliconflow');assert.ok(first.turn.events.some((e:any)=>e.name==='load_business_context'&&e.type==='tool_completed'));assert.ok(first.turn.events.some((e:any)=>e.name==='retrieve_guidance'&&e.type==='tool_completed'));
const old=first.artifacts.find((a:any)=>a.kind==='application_worksheet');assert.ok(old,'Provider did not produce the requested worksheet');assert.equal(old.fields.business_name,'Pearl North');assert.ok(old.citations.length);const html=await api(old.previewUrl);assert.equal(hash(html),old.hash);
const next=await done((await api(`/api/chat/artifacts/${old.id}/revise`,{hash:old.hash,fields:{reply_email:'founder@example.test'}})).turn.id);const fresh=next.artifacts[0];assert.equal(fresh.supersedesArtifactId,old.id);assert.equal(fresh.version,old.version+1);assert.equal(fresh.fields.reply_email,'founder@example.test');assert.equal(fresh.review,null);assert.equal(await api(old.previewUrl),html);assert.equal(next.turn.modelTrace.length,0);
const evidence={verifiedAt:new Date().toISOString(),conversationId:conversation.id,provider:first.turn.model,modelTrace:first.turn.modelTrace,firstDocument:{id:old.id,hash:old.hash},revisedDocument:{id:fresh.id,hash:fresh.hash},originalUnchanged:true,submitted:false};writeFileSync(new URL('./evidence/siliconflow-live.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({passed:true,conversationId:conversation.id,provider:first.turn.model,originalUnchanged:true}));
