import test from 'node:test';
import assert from 'node:assert/strict';
import {workspaceModelContext} from '../src/workspace-model-context.ts';
test('populated bilingual workspace stays bounded without changing authoritative data',()=>{
 const w={updatedAt:'snapshot',brief:{idea:'Fictional lighting',offer:'LED panels'},costs:{price:'60'},lifecycle:Array.from({length:60},(_,i)=>({id:'record-'+i,revision:2,values:{title:i===8?'supplier quote':'Other record',details:'تجريبي '.repeat(1200),basis:'simulated'},history:Array(5).fill({private:'old history'})}))};
 const before=JSON.stringify(w);const p=workspaceModelContext(w,'supplier quote');
 assert.ok(Buffer.byteLength(JSON.stringify(p))<=11000);assert.equal(p.updatedAt,'snapshot');assert.equal(p.projection.totalLifecycle,60);assert.ok(p.lifecycle.some((r:any)=>r.id==='record-8'));assert.ok(p.lifecycle.every((r:any)=>!r.history));assert.equal(JSON.stringify(w),before);
});
test('bounded workspace preview keeps the latest founder choice, selected option and adopted validation test',()=>{
 const w:any={updatedAt:'2026-10-07',brief:{idea:'Fixed-scope starter kit',customer:'Small shop owners',problem:'Setup is difficult',alternative:'Do it themselves',offer:'Starter kit',boundary:'No expansion before testing',sector:'Retail & ecommerce',location:'Kuwait'},profile:{stage:'Testing demand',budget:'unknown'},costs:{price:'60',variable:'8',fixed:'25',units:'10'},nextAction:{task:'Run the starter-kit test',owner:'Founder',due:'',dependency:'Interview shop owners'},hypotheses:Array.from({length:12},(_,i)=>({id:`H${i}`,title:`Old assumption ${i}`,area:'Demand',priority:'Important',status:'Testing',reviewReason:'',test:{method:'Old method',audience:'Old audience',rule:'Old rule',result:'',provenance:{artifactId:`A${i}`,conversationId:`C${i}`,title:`Draft ${i}`,adoptedAt:'2026-10-01'}}})),ideaReviewDecisions:Array.from({length:12},(_,i)=>({id:`IR${i}`,artifactId:`A${i}`,conversationId:'conversation-live',date:`2026-10-${String(i+1).padStart(2,'0')}`,choice:'revise',reason:`Earlier founder reason ${i}`,selectedOption:`Earlier option ${i}`,reviewSummary:'Prior idea review',customOption:{title:'Earlier custom',kind:'feature',tradeoff:'Earlier tradeoff'}})),decisions:Array.from({length:12},(_,i)=>({id:`D${i}`,hypothesisId:`H${i}`,date:`2026-10-${String(i+1).padStart(2,'0')}`,outcome:'Keep testing',reason:`Earlier validation reason ${i}`,assumption:`Earlier assumption ${i}`,rule:`Earlier rule ${i}`,evidence:[{id:`E${i}`,hypothesisId:`H${i}`,kind:'Observation',text:'Earlier observation',source:'Founder',date:'2026-10-01',signal:'Unclear',limitation:'Small sample'}]})),lifecycle:[],ideaReviewDecisionsTruncated:false};
 w.hypotheses.push({id:'H-ADOPTED',title:'Starter-kit demand',area:'Demand',priority:'Critical',status:'Testing',reviewReason:'',test:{method:'Show the starter-kit sample to shop owners.',audience:'Independent shop owners in Kuwait',rule:'Record explicit interest and objections before expanding.',result:'',provenance:{artifactId:'ARTIFACT-IDEA',conversationId:'CONVERSATION-FOUNDER',title:'Idea critique',adoptedAt:'2026-10-07T09:00:00Z'}}});
 w.ideaReviewDecisions.push({id:'IR-LATEST',artifactId:'ARTIFACT-IDEA',conversationId:'CONVERSATION-FOUNDER',date:'2026-10-31T09:05:00Z',choice:'test',reason:'We chose this because shop owners need a low-risk first setup.',selectedOption:'Starter kit for independent shops',reviewSummary:'Test the core offer before expanding.',customOption:{title:'One-day onboarding',kind:'feature',tradeoff:'Requires founder time.'}});
 w.decisions.push({id:'D-LATEST',hypothesisId:'H-ADOPTED',date:'2026-10-31T09:10:00Z',outcome:'Keep testing',reason:'No customer evidence yet; run the adopted test first.',assumption:'Shop owners need setup help.',rule:'Record interest and objections.',evidence:[{id:'E-LATEST',hypothesisId:'H-ADOPTED',kind:'Assumption',text:'No interviews have been run.',source:'Founder',date:'2026-10-07',signal:'Unclear',limitation:'Not customer evidence'}]});
 const before=JSON.stringify(w);const preview=workspaceModelContext(w,'starter kit',6000);assert.ok(Buffer.byteLength(JSON.stringify(preview))<=6000);assert.equal(preview.ideaReviewDecisions.at(-1).id,'IR-LATEST');assert.equal(preview.ideaReviewDecisions.at(-1).choice,'test');assert.equal(preview.ideaReviewDecisions.at(-1).reason,'We chose this because shop owners need a low-risk first setup.');assert.equal(preview.ideaReviewDecisions.at(-1).selectedOption,'Starter kit for independent shops');assert.equal(preview.ideaReviewDecisions.at(-1).customOption.title,'One-day onboarding');assert.equal(preview.decisions.at(-1).id,'D-LATEST');assert.equal(preview.decisions.at(-1).rule,'Record interest and objections.');const adopted=preview.hypotheses.find((h:any)=>h.id==='H-ADOPTED');assert.equal(adopted.test.audience,'Independent shop owners in Kuwait');assert.equal(adopted.test.method,'Show the starter-kit sample to shop owners.');assert.equal(adopted.test.rule,'Record explicit interest and objections before expanding.');assert.equal(adopted.test.provenance.artifactId,'ARTIFACT-IDEA');assert.equal(JSON.stringify(w),before);
});
