import {blank,newHypothesis,type Workspace} from './workspace.ts'
import {saveLifecycle} from '../../../shared/lifecycle.ts'
import type {LifecycleValues} from '../../../shared/lifecycle.ts'
import {reconcileContext} from './business-impact.ts'
export const pearlPdfPrompt='Prepare the actual KDIPA Application B PDF for this explicitly fictional demonstration. Template pearl-delta-official-form. Name: Mingyuan Lighting Co., Ltd. - fictional. Nationality: China - demonstration. Objectives: Commercial LED lighting supply and technical support - proposed. Head Office: Shenzhen, China - fictional; address unconfirmed. Email: contact@mingyuan.example. Type of economic activity: Proposed LED lighting supply; eligibility to be confirmed. Objectives_2: Explore Kuwait commercial lighting distribution and project supply. Leave all other fields blank. Keep the demonstration watermark. Do not sign or submit.'
export function pearlDeltaExample():Workspace{
 const w=blank();w.brief={idea:'Mingyuan Lighting · Fictional China-to-Kuwait example',customer:'Kuwait fit-out studios, hotel groups, independent lighting retailers and project suppliers',problem:'Whether buyers need a new LED supplier with technical support is untested.',alternative:'Existing local distributors and established importers.',offer:'Commercial LED panels, downlights and strip lighting shipped from a Shenzhen factory, with installation training for local partners and after-sales support in Arabic and English.',boundary:'Synthetic company. No validated demand, legal eligibility, budget or official submission. Public leads are research candidates, not customers.',sector:'Retail & ecommerce',location:'Kuwait; fictional headquarters in Shenzhen, China'}
 w.profile={stage:'Testing demand',budget:''};w.hypotheses=[{...newHypothesis('Do Kuwait lighting buyers need another supplier?','Demand'),id:'pearl-demand',test:{method:'Customer conversations',audience:'Qualified commercial lighting buyers',rule:'Record buyer problems and procurement requirements before deciding on a pilot.',result:''}},{...newHypothesis('Is the proposed activity eligible for the intended Kuwait route?','Kuwait setup'),id:'pearl-route'}]
 const rows=[{category:'licence',title:'Confirm the appropriate Kuwait route',details:'KDIPA Application B is a source-backed preparation example. Verify activity eligibility, entity details and required attachments before any application.',source:'https://kdipa.gov.kw/investors-service-center/investment-licensing-procedures/'},{category:'hiring',title:'Define local technical support needs',details:'Fictional role brief: identify installation support skills, local coverage and responsibilities. Headcount, budget and employment route remain unknown.'},{category:'business_decision',title:'Test distributor interest before committing to launch',details:'Prepared decision for review: interview qualified buyers before committing inventory or a local office.',evidence:'Synthetic planning assumption. Public company listings establish potential contacts only; no conversations or customer demand have been verified.'}]
 rows.forEach((row,i)=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row,status:'prepared'},'pearl-demo-'+i,'2026-09-26')})
 // Fictional finance records so the Finance area is not empty in this worked example. All simulated, none actual.
 const financeRows:Array<{id:string;values:LifecycleValues}>=[
  {id:'pearl-fin-income-1',values:{category:'operation',entityType:'finance',title:'Sample order deposit: Distributor A (fictional)',details:'Fictional distributor sample-order deposit for demonstration only. No real transaction.',direction:'income',date:'2026-07-10',amount:'850.000',basis:'simulated',evidence:'Simulated distributor order; no bank record exists.'}},
  {id:'pearl-fin-income-2',values:{category:'operation',entityType:'finance',title:'Sample order deposit: Distributor B (fictional)',details:'Fictional distributor sample-order deposit for demonstration only. No real transaction.',direction:'income',date:'2026-08-14',amount:'620.000',basis:'simulated',evidence:'Simulated distributor order; no bank record exists.'}},
  {id:'pearl-fin-expense-freight',values:{category:'operation',entityType:'finance',title:'Freight: sample shipment (fictional)',details:'Fictional freight cost for the demonstration sample shipment. No real shipment took place.',direction:'expense',date:'2026-07-15',amount:'145.500',basis:'simulated'}},
  {id:'pearl-fin-expense-samples',values:{category:'operation',entityType:'finance',title:'Product samples cost (fictional)',details:'Fictional cost of producing LED lighting samples for demonstration only.',direction:'expense',date:'2026-07-05',amount:'90.000',basis:'simulated'}},
  {id:'pearl-fin-expense-translation',values:{category:'operation',entityType:'finance',title:'Literature translation (fictional)',details:'Fictional translation of product literature for demonstration only.',direction:'expense',date:'2026-08-05',amount:'60.000',basis:'simulated'}},
  {id:'pearl-fin-expense-licence',values:{category:'operation',entityType:'finance',title:'Licence consultation fee (fictional)',details:'Fictional consultation fee on the Kuwait licensing route, for demonstration only.',direction:'expense',date:'2026-08-20',amount:'120.000',basis:'simulated'}},
  {id:'pearl-fin-expense-desk-aug',values:{category:'operation',entityType:'finance',title:'Co-working desk: August (fictional)',details:'Fictional monthly co-working desk cost for demonstration only.',direction:'expense',date:'2026-08-01',amount:'45.000',basis:'simulated'}},
  {id:'pearl-fin-expense-desk-sep',values:{category:'operation',entityType:'finance',title:'Co-working desk: September (fictional)',details:'Fictional monthly co-working desk cost for demonstration only.',direction:'expense',date:'2026-09-01',amount:'45.000',basis:'simulated'}},
  {id:'pearl-budget-marketing',values:{category:'operation',entityType:'budget',title:'Marketing budget: September (fictional)',details:'Fictional planned marketing spend for the demonstration. Not an actual transaction.',direction:'expense',date:'2026-09-01',amount:'200.000',basis:'simulated'}},
  {id:'pearl-budget-samples',values:{category:'operation',entityType:'budget',title:'Samples budget: August (fictional)',details:'Fictional planned sample-production spend for the demonstration. Not an actual transaction.',direction:'expense',date:'2026-08-01',amount:'150.000',basis:'simulated'}},
  {id:'pearl-quote-led',values:{category:'operation',entityType:'quote',title:'Supplier quote: LED fixtures (fictional)',details:'Fictional supplier quote for LED fixture stock, for demonstration only. No purchase agreed.',date:'2026-08-25',quantity:'40',unitPrice:'9.000',basis:'simulated'}},
  {id:'pearl-order-led',values:{category:'operation',entityType:'order',title:'Purchase order: LED fixtures pilot (fictional)',details:'Fictional pilot purchase request linked to the supplier quote, for demonstration only. Not ordered or paid.',date:'2026-09-05',quantity:'20',unitPrice:'9.000',basis:'simulated',relatedId:'pearl-quote-led'}},
 ]
 financeRows.forEach(row=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row.values,status:'prepared'},row.id,'2026-09-26')})
 // Fictional sales pipeline: contacts, leads, proposals and follow-ups so the sales area is not empty. All simulated, none actual.
 const growthRows:Array<{id:string;values:LifecycleValues}>=[
  {id:'pearl-contact-marina-fitout',values:{category:'sales',entityType:'contact',title:'Contact: Marina Fit-Out Studio (fictional)',details:'Fictional Kuwaiti fit-out and interior studio contact for demonstration only. No real company or relationship.',basis:'simulated',stage:'new',contact:'marina.fitout@example.com',channel:'Email',date:'2026-07-08'}},
  {id:'pearl-contact-salmiya-fitout',values:{category:'sales',entityType:'contact',title:'Contact: Salmiya Fit-Out Studio (fictional)',details:'Fictional Kuwaiti fit-out and joinery studio contact for demonstration only. No real company or relationship.',basis:'simulated',stage:'active',contact:'salmiya.fitout@example.com',channel:'Phone',date:'2026-07-12'}},
  {id:'pearl-contact-gulfcoast-hotels',values:{category:'sales',entityType:'contact',title:'Contact: Gulf Coast Hotels Group (fictional)',details:'Fictional Kuwait hotel group procurement contact for demonstration only. No real company or relationship.',basis:'simulated',stage:'active',contact:'procurement.gulfcoast@example.com',channel:'Email',date:'2026-07-20'}},
  {id:'pearl-contact-qurain-retail',values:{category:'sales',entityType:'contact',title:'Contact: Qurain Home Retail (fictional)',details:'Fictional Kuwaiti home and lighting retailer contact for demonstration only. No real company or relationship.',basis:'simulated',stage:'inactive',contact:'buying.qurain@example.com',channel:'Email',date:'2026-07-25'}},
  {id:'pearl-lead-marina-fitout',values:{category:'sales',entityType:'lead',title:'Lead: Marina Fit-Out Studio LED enquiry (fictional)',details:'Fictional early-stage interest from a Kuwaiti fit-out studio in LED fixture supply. No real enquiry received.',basis:'simulated',stage:'prospect',date:'2026-07-09',evidence:'Simulated pipeline note; no real enquiry logged.',relatedId:'pearl-contact-marina-fitout'}},
  {id:'pearl-lead-salmiya-fitout',values:{category:'sales',entityType:'lead',title:'Lead: Salmiya Fit-Out Studio outreach (fictional)',details:'Fictional outreach call logged with a Kuwaiti fit-out studio about LED fixture supply. No real call took place.',basis:'simulated',stage:'contacted',date:'2026-07-18',evidence:'Simulated call log; no real conversation occurred.',relatedId:'pearl-contact-salmiya-fitout'}},
  {id:'pearl-lead-gulfcoast-hotels',values:{category:'sales',entityType:'lead',title:'Lead: Gulf Coast Hotels Group refurbishment (fictional)',details:'Fictional qualified opportunity for LED retrofit across a Kuwait hotel group refurbishment. No real opportunity confirmed.',basis:'simulated',stage:'qualified',date:'2026-08-10',evidence:'Simulated qualification note; no real project confirmed.',relatedId:'pearl-contact-gulfcoast-hotels'}},
  {id:'pearl-lead-qurain-retail',values:{category:'sales',entityType:'lead',title:'Lead: Qurain Home Retail stocking enquiry (fictional)',details:'Fictional stocking enquiry from a Kuwaiti retailer that went with an existing supplier. No real enquiry occurred.',basis:'simulated',stage:'lost',date:'2026-08-05',evidence:'Simulated lost-reason note; no real enquiry occurred.',relatedId:'pearl-contact-qurain-retail'}},
  {id:'pearl-proposal-gulfcoast-hotels',values:{category:'sales',entityType:'proposal',title:'Proposal: Gulf Coast Hotels Group LED retrofit (fictional)',details:'Fictional draft proposal for LED retrofit across hotel group properties, for demonstration only. Not sent.',basis:'simulated',stage:'draft',date:'2026-08-12',quantity:'150',unitPrice:'12.000',relatedId:'pearl-lead-gulfcoast-hotels'}},
  {id:'pearl-proposal-salmiya-fitout',values:{category:'sales',entityType:'proposal',title:'Proposal: Salmiya Fit-Out Studio fixture supply (fictional)',details:'Fictional proposal sent for LED fixture supply to a Kuwaiti fit-out studio, for demonstration only. No real proposal sent.',basis:'simulated',stage:'sent',date:'2026-08-22',quantity:'60',unitPrice:'11.500',evidence:'Simulated proposal record; no real document sent.',relatedId:'pearl-lead-salmiya-fitout'}},
  {id:'pearl-followup-marina-checkin',values:{category:'sales',entityType:'followup',title:'Follow-up: Marina Fit-Out Studio check-in (fictional)',details:'Fictional planned follow-up call with a Kuwaiti fit-out studio prospect, for demonstration only. Not yet due.',basis:'simulated',stage:'planned',due:'2026-10-15',relatedId:'pearl-lead-marina-fitout'}},
  {id:'pearl-followup-gulfcoast-proposal',values:{category:'sales',entityType:'followup',title:'Follow-up: Gulf Coast Hotels Group proposal response (fictional)',details:'Fictional follow-up call due to check on the draft proposal, for demonstration only. Not yet completed.',basis:'simulated',stage:'due',due:'2026-10-04',relatedId:'pearl-proposal-gulfcoast-hotels'}},
  {id:'pearl-followup-salmiya-confirmation',values:{category:'sales',entityType:'followup',title:'Follow-up: Salmiya Fit-Out Studio proposal confirmation (fictional)',details:'Fictional completed follow-up call confirming receipt of the sent proposal, for demonstration only. No real call took place.',basis:'simulated',stage:'done',date:'2026-09-10',evidence:'Simulated call note; no real conversation occurred.',relatedId:'pearl-proposal-salmiya-fitout'}},
 ]
 growthRows.forEach(row=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row.values,status:'prepared'},row.id,'2026-09-26')})
 // Fictional hiring pipeline: roles, candidates and onboarding so the people area is not empty. All simulated, none actual.
 const peopleRows:Array<{id:string;values:LifecycleValues}>=[
  {id:'pearl-role-tech-support',values:{category:'hiring',entityType:'role',title:'Role: Technical support specialist (fictional)',details:'Fictional part-time role to support Kuwait customers with LED installation guidance, for demonstration only. Not recruited.',basis:'simulated',stage:'open',date:'2026-07-15',evidence:'Simulated role brief; no real recruitment activity.',owner:'Founder'}},
  {id:'pearl-role-sales-coordinator',values:{category:'hiring',entityType:'role',title:'Role: Part-time sales coordinator (fictional)',details:'Fictional part-time role to manage Kuwait buyer outreach and proposals, for demonstration only. Not recruited.',basis:'simulated',stage:'draft',date:'2026-07-20',owner:'Founder'}},
  {id:'pearl-candidate-tech-support-1',values:{category:'hiring',entityType:'candidate',title:'Candidate: Technical support specialist applicant (fictional)',details:'Fictional sourced candidate profile for the technical support role, for demonstration only. No real applicant.',basis:'simulated',stage:'sourced',date:'2026-08-01',relatedId:'pearl-role-tech-support'}},
  {id:'pearl-candidate-sales-coordinator-1',values:{category:'hiring',entityType:'candidate',title:'Candidate: Sales coordinator applicant (fictional)',details:'Fictional candidate shortlisted for interview for the sales coordinator role, for demonstration only. No real applicant.',basis:'simulated',stage:'interview',date:'2026-08-20',evidence:'Simulated shortlisting note; no real applicant exists.',relatedId:'pearl-role-sales-coordinator'}},
  {id:'pearl-onboarding-tech-support',values:{category:'hiring',entityType:'onboarding',title:'Onboarding: Technical support specialist checklist (fictional)',details:'Fictional onboarding task list for the technical support role, for demonstration only. No real hire yet.',basis:'simulated',stage:'not_started',date:'2026-08-01',relatedId:'pearl-role-tech-support'}},
 ]
 peopleRows.forEach(row=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row.values,status:'prepared'},row.id,'2026-09-26')})
 // Fictional operations: suppliers, launch tasks, extra decisions and a launch milestone so the operations area is not empty. All simulated, none actual.
 const opsRows:Array<{id:string;values:LifecycleValues}>=[
  {id:'pearl-supplier-shenzhen-led',values:{category:'operation',entityType:'supplier',title:'Supplier: Shenzhen LED factory (fictional)',details:'Fictional Shenzhen-based LED fixture manufacturer under review as a production partner, for demonstration only. No real supplier relationship.',basis:'simulated',stage:'selected',date:'2026-07-05',evidence:'Simulated supplier assessment; no real supplier engaged.',relatedId:'pearl-order-led'}},
  {id:'pearl-supplier-kuwait-logistics',values:{category:'operation',entityType:'supplier',title:'Supplier: Kuwait logistics firm (fictional)',details:'Fictional Kuwait-based freight and customs clearance firm under review for import logistics, for demonstration only. No real supplier relationship.',basis:'simulated',stage:'shortlisted',date:'2026-07-10'}},
  {id:'pearl-task-samples-kit',values:{category:'operation',entityType:'task',title:'Task: Prepare Kuwait sample kit (fictional)',details:'Fictional task to prepare an LED sample kit for Kuwait buyer meetings, for demonstration only. Not started.',basis:'simulated',stage:'todo',due:'2026-10-20'}},
  {id:'pearl-task-website-arabic',values:{category:'operation',entityType:'task',title:'Task: Translate product literature to Arabic (fictional)',details:'Fictional task to translate LED product literature into Arabic for Kuwait buyers, for demonstration only. Underway.',basis:'simulated',stage:'in_progress',due:'2026-10-12'}},
  {id:'pearl-task-kdipa-clarification',values:{category:'operation',entityType:'task',title:'Task: Await KDIPA activity eligibility clarification (fictional)',details:'Fictional task blocked pending clarification of activity eligibility for the Kuwait route, for demonstration only. Awaiting response.',basis:'simulated',stage:'blocked',due:'2026-10-08'}},
  {id:'pearl-task-supplier-shortlist',values:{category:'operation',entityType:'task',title:'Task: Shortlist Kuwait logistics suppliers (fictional)',details:'Fictional completed task to shortlist logistics suppliers for import handling, for demonstration only. No real supplier engaged.',basis:'simulated',stage:'done',date:'2026-08-15',evidence:'Simulated task log; no real supplier work occurred.',relatedId:'pearl-supplier-kuwait-logistics'}},
  {id:'pearl-decision-avoid-inventory',values:{category:'business_decision',title:'Decision: Avoid holding inventory before demand is proven (fictional)',details:'Fictional decision to test buyer demand through sample orders before committing to bulk inventory, for demonstration only.',basis:'simulated',date:'2026-07-28',evidence:'Simulated trade-off note weighing capital risk against speed to market; no real capital committed.'}},
  {id:'pearl-decision-arabic-literature',values:{category:'business_decision',title:'Decision: Translate literature before wider outreach (fictional)',details:'Fictional decision to prioritise Arabic product literature before expanding buyer outreach, for demonstration only.',basis:'simulated',date:'2026-08-18',evidence:'Simulated trade-off note weighing outreach speed against buyer clarity; no real outreach conducted.'}},
  {id:'pearl-launch-milestone-pilot',values:{category:'launch',title:'Milestone: Kuwait pilot sample shipment (fictional)',details:'Fictional milestone marking the target date for the first Kuwait pilot sample shipment, for demonstration only. Not yet scheduled for real.',basis:'simulated',due:'2026-10-15'}},
 ]
 opsRows.forEach(row=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row.values,status:'prepared'},row.id,'2026-09-26')})
 // Fictional licence and document records so that area also shows a checklist and a source-linked requirement. All simulated, none actual.
 const complianceRows:Array<{id:string;values:LifecycleValues}>=[
  {id:'pearl-document-cr-checklist',values:{category:'document',title:'Checklist: Commercial registration documents (fictional)',details:'Fictional checklist of commercial registration documents anticipated for the Kuwait entity, for demonstration only. Requirements unconfirmed.',basis:'simulated',date:'2026-07-30'}},
  {id:'pearl-licence-kdipa-requirement',values:{category:'licence',title:'Requirement: KDIPA Application B supporting documents (fictional)',details:'Fictional requirement note listing supporting documents anticipated for the KDIPA Application B route, for demonstration only. Confirm the exact list with KDIPA before applying.',basis:'simulated',date:'2026-08-01',source:'https://kdipa.gov.kw/investors-service-center/investment-licensing-procedures/',relatedId:'pearl-demo-0'}},
 ]
 complianceRows.forEach(row=>{w.lifecycle=saveLifecycle(w.lifecycle,{...row.values,status:'prepared'},row.id,'2026-09-26')})
 w.costs={price:'15',variable:'9',fixed:'300',units:'40'}
 w.costScenarios=[{id:'pearl-scenario-base',name:'Base case (fictional)',note:'Fictional base-case unit economics for the demonstration: KWD 15 price, KWD 9 variable cost, KWD 300 monthly fixed cost, 40 units a month.',date:'2026-09-26T00:00:00.000Z',archived:false,costs:{price:'15',variable:'9',fixed:'300',units:'40'}}]
 w.nextAction={task:'Test distributor interest and confirm the licence route.',owner:'Founder',due:'',dependency:'Buyer conversations and official eligibility clarification'};return reconcileContext(blank(),w)
}
