import type {LifecycleRecord} from '../../../shared/lifecycle.ts'
export type BusinessArea='market'|'finance'|'sales'|'people'|'operations'|'licences'
export type RecordView={id:string;label:[string,string];category:string;entityType?:string;fields:string[];prompt:string}
export const areaLabels:Record<BusinessArea,[string,string]>={market:['Idea & market','الفكرة والسوق'],finance:['Finance','المالية'],sales:['Customers & sales','العملاء والمبيعات'],people:['People','الفريق'],operations:['Operations','العمليات'],licences:['Licences & documents','التراخيص والمستندات']}
export const recordViews:Record<Exclude<BusinessArea,'market'>,RecordView[]>={
 finance:[{id:'finance',label:['Transactions','المعاملات'],category:'operation',entityType:'finance',fields:['amount','direction','date','basis','evidence','relatedId'],prompt:'Prepare a recorded income or expense entry. Use only supplied amount, date and receipt. Distinguish actual, estimate and simulated. Never move money.'},{id:'budget',label:['Budgets','الميزانيات'],category:'operation',entityType:'budget',fields:['amount','direction','date','basis','evidence'],prompt:'Prepare a budget from my supplied assumptions, with its period, amount and purpose. Do not invent figures or treat the budget as actual cash.'}],
 sales:[{id:'contact',label:['Contacts','جهات الاتصال'],category:'sales',entityType:'contact',fields:['contact','channel','stage','source','nextAction'],prompt:'Prepare a contact record from supplied public business information. Keep unknown details blank. Do not contact anyone.'},{id:'lead',label:['Pipeline','فرص البيع'],category:'sales',entityType:'lead',fields:['contact','channel','stage','nextAction','due','owner','source'],prompt:'Prepare a lead record from the contact and evidence I supply. Record the sales stage, next action and follow-up date if known. Do not contact anyone.'},{id:'proposal',label:['Proposals','العروض'],category:'sales',entityType:'proposal',fields:['relatedId','contact','amount','quantity','unitPrice','basis','due','source'],prompt:'Prepare a reviewable sales proposal with scope, price only if supplied, assumptions and a linked lead. Do not send or promise delivery.'},{id:'followup',label:['Follow-ups','المتابعات'],category:'sales',entityType:'followup',fields:['relatedId','contact','nextAction','due','owner'],prompt:'Prepare a follow-up task linked to the saved lead. Keep the proposed message as a draft; do not send.'}],
 people:[{id:'role',label:['Hiring','التوظيف'],category:'hiring',entityType:'role',fields:['owner','due','amount','basis'],prompt:'Scope a role from actual workload and budget. Prepare outcomes, responsibilities and interview criteria. Do not invent a salary or post a job.'},{id:'candidate',label:['Candidates','المرشحون'],category:'hiring',entityType:'candidate',fields:['contact','stage','relatedId','nextAction','due','evidence'],prompt:'Prepare a candidate record from job-relevant information supplied by me. Record evidence, interview next step and linked role. Do not infer sensitive traits or make a hiring decision.'},{id:'onboarding',label:['Onboarding','تهيئة الموظفين'],category:'hiring',entityType:'onboarding',fields:['relatedId','owner','due','nextAction'],prompt:'Prepare an onboarding task linked to the role or candidate, with owner, due date if known and completion evidence. Do not provision accounts or access.'}],
 operations:[{id:'launch',label:['Launch','الإطلاق'],category:'launch',fields:['owner','due','evidence','relatedId'],prompt:'Prepare the next launch action based on saved customer evidence, licence work and plans. Keep dependencies explicit and unknown dates blank.'},{id:'decision',label:['Decisions','القرارات'],category:'business_decision',fields:['owner','due','evidence','relatedId'],prompt:'Prepare a business decision with options, evidence, trade-offs, chosen direction and review date. Preserve earlier decisions and do not invent evidence.'},{id:'task',label:['Tasks','المهام'],category:'operation',entityType:'task',fields:['owner','due','relatedId','nextAction'],prompt:'Prepare an operating task with a clear outcome, owner, dependency and due date if known. Do not mark it done without evidence.'},{id:'supplier',label:['Suppliers','المورّدون'],category:'operation',entityType:'supplier',fields:['contact','channel','source','nextAction','due'],prompt:'Prepare a supplier record from supplied or cited public information. Separate capabilities from unverified claims. Do not contact the supplier.'},{id:'quote',label:['Quotes','عروض الأسعار'],category:'operation',entityType:'quote',fields:['relatedId','amount','quantity','unitPrice','basis','due','source'],prompt:'Prepare a supplier quote record from the supplied quote. Preserve terms and currency; leave unknown amounts blank. Do not approve a purchase.'},{id:'order',label:['Purchasing','المشتريات'],category:'operation',entityType:'order',fields:['relatedId','amount','quantity','unitPrice','basis','owner','due','evidence'],prompt:'Prepare a purchase request linked to the supplier quote, with cost, rationale and required approval. Do not order or pay.'}],
 licences:[{id:'licence',label:['Requirements','المتطلبات'],category:'licence',fields:['source','due','owner','evidence'],prompt:'Research the applicable official licence route for my saved business. Prepare sourced requirements, missing details and questions. Do not infer eligibility or submit.'},{id:'document',label:['Documents','المستندات'],category:'document',fields:['source','relatedId','due','evidence'],prompt:'Prepare a document checklist linked to the relevant licence requirement. Identify the source, missing documents and review action. Do not sign or submit.'}]
}
export function matchesView(row:LifecycleRecord,view:RecordView){const values=row.values as Record<string,string|undefined>;if(values.category!==view.category)return false;if(!view.entityType)return true;return values.entityType===view.entityType||(!values.entityType&&((view.category==='operation'&&view.entityType==='finance')||(view.category==='hiring'&&view.entityType==='role')))}
export const recordFieldLabels:Record<string,[string,string]>={title:['Title','العنوان'],details:['Details and dependencies','التفاصيل والمتطلبات السابقة'],contact:['Contact','جهة الاتصال'],channel:['Contact channel','وسيلة التواصل'],stage:['Stage','المرحلة'],nextAction:['Next action','الإجراء التالي'],due:['Due or follow-up date','موعد التنفيذ أو المتابعة'],owner:['Owner','المسؤول'],source:['Public source URL','رابط المصدر العام'],evidence:['Receipt or outcome evidence','إيصال أو دليل النتيجة'],amount:['Amount (KWD)','المبلغ (د.ك)'],quantity:['Quantity','الكمية'],unitPrice:['Unit price (KWD)','سعر الوحدة (د.ك)'],basis:['Evidence basis','أساس البيانات'],direction:['Direction','نوع التدفق'],date:['Event or budget date','تاريخ المعاملة أو الميزانية'],relatedId:['Linked record','السجل المرتبط']}
